### ISSUE TITLE
Support SARIF + GitHub Code Scanning

### ISSUE THREAD

**Issue by danielcompton** [clj-kondo/clj-kondo#1035]
To upvote this issue, give it a thumbs up. See [this list](https://github.com/clj-kondo/clj-kondo/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) for the most upvoted issues.

**Is your feature request related to a problem? Please describe.**

GitHub has just launched [third-party code scanning](https://github.blog/2020-10-05-announcing-third-party-code-scanning-tools-static-analysis-and-developer-security-training/). This lets code analysis tools (like clj-kondo) to [upload](https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/uploading-a-sarif-file-to-github#example-workflow-that-runs-the-eslint-analysis-tool) SARIF results for code scanning.

**Describe the solution you'd like**

clj-kondo supports reporting analysis results in the [SARIF](https://docs.oasis-open.org/sarif/sarif/v2.0/sarif-v2.0.html) format.

<details>

<summary>SARIF example</summary>

```json
{
  "version": "2.1.0",
  "$schema": "http://json.schemastore.org/sarif-2.1.0-rtm.4",
  "runs": [
    {
      "tool": {
        "driver": {
          "name": "ESLint",
          "informationUri": "https://eslint.org",
          "rules": [
            {
              "id": "no-unused-vars",
              "shortDescription": {
                "text": "disallow unused variables"
              },
              "helpUri": "https://eslint.org/docs/rules/no-unused-vars",
              "properties": {
                "category": "Variables"
              }
            }
          ]
        }
      },
      "artifacts": [
        {
          "location": {
            "uri": "file:///C:/dev/sarif/sarif-tutorials/samples/Introduction/simple-example.js"
          }
        }
      ],
      "results": [
        {
          "level": "error",
          "message": {
            "text": "'x' is assigned a value but never used."
          },
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "file:///C:/dev/sarif/sarif-tutorials/samples/Introduction/simple-example.js",
                  "index": 0
                },
                "region": {
                  "startLine": 1,
                  "startColumn": 5
                }
              }
            }
          ],
          "ruleId": "no-unused-vars",
          "ruleIndex": 0
        }
      ]
    }
  ]
}
```

</details>

**Describe alternatives you've considered**

There is already support for Github Actions [workflow commands](https://github.com/borkdude/clj-kondo/blob/master/doc/ci-integration.md#github) in clj-kondo.

**Additional context**

It looks like [SARIF](https://github.com/microsoft/sarif-tutorials/blob/master/docs/1-Introduction.md#why-sarif) may become a widely used analysis standard that will integrate into editors, e.g. https://github.com/microsoft/sarif-vscode-extension.

**Update:** https://sarifweb.azurewebsites.net/Validation is a validator for SARIF files.

**Comment by borkdude** [comment]
@danielcompton Thanks, I'll have a read.

**Comment by danielcompton** [comment]
One note is that the code analysis results will [show up](https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/managing-code-scanning-alerts-for-your-repository#viewing-an-alert) in the Security tab which may be slightly confusing.

**Comment by nvuillam** [comment]
I'd also love SARIF output, it would improve [clk-kondo integration within MegaLinter](https://megalinter.github.io/latest/descriptors/clojure_clj_kondo/) :)

**Comment by borkdude** [comment]
I encourage you to upvote this issue by giving it a thumbs up. It allows me get an idea of the most wanted features. See [this list](https://github.com/clj-kondo/clj-kondo/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) for the most upvoted issues.

**Comment by nvuillam** [comment]
Not stale :)

**Comment by ypencheva** [comment]
we badly need this in our org/company, any chance it can happen?

**Comment by borkdude** [comment]
@ypencheva This is the second most popular issue so I'll have a look for the next release then

**Comment by borkdude** [comment]
Here is a simple example: https://github.com/microsoft/sarif-tutorials/blob/main/docs/1-Introduction.md#simple-example

**Comment by borkdude** [comment]
commit `8512c86fcf6d546c9890e04560a483ad4c0ecb09` in branch `sarif` now supports `{:output {:format :sarif}}`

how to best test this? can anyone try it out?

**Comment by nvuillam** [comment]
@borkdude I should be able to do that someday in MegaLinter :)

**Comment by borkdude** [comment]
Seems to work as expected by viewing it in the SARIF viewer in VSCode. Early pre-release testing would be good though

<img width="1578" alt="Screenshot 2024-04-04 at 16 49 35" src="https://github.com/clj-kondo/clj-kondo/assets/284934/e07a36fd-9a99-48a9-bf8d-5298f15057f7">
