### ISSUE TITLE
Detect duplicate key in '{[1 2] 3, (1 2) 4}

### ISSUE THREAD

**Issue by borkdude** [clj-kondo/clj-kondo#1056]

**Comment by jysandy** [comment]
@borkdude I'm planning on picking this up. From the looks of it, I'll have to make a change in this `lint-map-keys` function https://github.com/clj-kondo/clj-kondo/blob/master/src/clj_kondo/impl/linters/keys.clj#L17. I'm a new contributor, so I just wanted to run this by you and make sure you didn't have something else in mind.

**Comment by jysandy** [comment]
It doesn't look like this particular case is unit tested, so I was thinking of adding a test or two to cover it as well.

**Comment by borkdude** [comment]
@jysandy That's the correct place to look. Thanks for looking into it!
