### ISSUE TITLE
Feature request: add a case expression linter to prevent us from confusing case with cond(p)

### ISSUE THREAD

**Issue by saitouena** [clj-kondo/clj-kondo#1066]
**Is your feature request related to a problem? Please describe.**
```clojure
;; I sometimes confuse case with cond(p)
(let [x (+ 2 3)]
  (case x
    1 "1"
    ;; I wrote (+ 2 3) here to be evaluated to 5 but it's wrong
    (+ 2 3) "5"
    "default"))
;; => "default"
```

**Describe the solution you'd like**
I think it is a solution to add a linter to restrict test expression of `cond` to be simple literal like `1`, `:abc` or `"abc"` not `(+ 1 2)`.

**Additional context**
I'm curious about the frequency of such kind of mistakes in general. I think this might be a specific mistake of me.

**Comment by borkdude** [comment]
Related: #593

**Comment by tomdl89** [comment]
Unfortunately I don't think this can work. You can supply multiple cases to match against using parens, so I'm not sure there is a way to differentiate this from accidentally thinking you're using `condp`.
E.g.
```
(case :foo 
  (:foo :bar) "Yes"
  (:baz :qux) "No")
```
would return "Yes" which is desired. The only way you could lint for your case would be to disallow symbols in parens, but as linked above, this is perfectly legitimate behaviour.
