### ISSUE TITLE
Feature request: detect invalid multi-arity forms

### ISSUE THREAD

**Issue by yuhan0** [clj-kondo/clj-kondo#1070]
**Is your feature request related to a problem? Please describe.**

Multi-arity function definitions are invalid if some of their arglists clash or share the same arity. This appears to be a runtime error (macroexpanding the defn / fn form does not throw an exception).

An intuitive way to define a reducing function might be the following, but it turns out to be illegal because the vararg arity has too few args.
```clj
(defn plus
  ([n] n)
  ([n1 n2] (+ n1 n2))
  ([n & ns] (reduce plus n ns)))
```
The vararg arity has to be written in the more redundant form `([n1 n2 & ns] (reduce plus (plus n1 n2) ns))`.

Another plausible but invaild construction:
```clj
(defn foo
  ([x [y]] ...)
  ([x [y z]] ...))
```

**Describe the solution you'd like**
clj-kondo could detect these cases and produce some sort of "invalid arity" lint error.

**Describe alternatives you've considered**
Catch the error during evaluation - it's probably not a common mistake and easy enough to spot and fix.

**Additional context**

The error messages produced by Clojure are:
> Can't have fixed arity function with more params than variadic function

> Can't have 2 overloads with same arity

> Can't have more than 1 variadic overload

**Comment by borkdude** [comment]
This is now supported in the latest clj-kondo.

![Screenshot 2022-01-02 at 20 22 54](https://user-images.githubusercontent.com/284934/147887041-b74b691d-8179-4945-8595-f0bb112cd7a2.png)
