### ISSUE TITLE
Redundant get-in

### ISSUE THREAD

**Issue by SevereOverfl0w** [clj-kondo/clj-kondo#1076]
**Is your feature request related to a problem? Please describe.**

I just found `(get-in config [:foobar])` in my code, that frustrates me!

**Describe the solution you'd like**

A kondo warning for use of redundant `get-in`, which could be just `get`.

**Describe alternatives you've considered**

Writing better code first time around :)

**Comment by borkdude** [comment]
@SevereOverfl0w There's already a linter for this. It's called `:single-key-in` and is disabled by default. Let me know if that works for you.
