### ISSUE TITLE
Redundant `get` when using with keyword

### ISSUE THREAD

**Issue by SevereOverfl0w** [clj-kondo/clj-kondo#1077]
Is your feature request related to a problem? Please describe.

I just found (get config :foobar) in my code, that frustrates me!

Describe the solution you'd like

A warning for use of `get` which could just be `(<key> config)`.  In particular, I think this should only apply to literal keywords, rather than symbols/bindings where there's ambiguity and they're possibly null.

Describe alternatives you've considered

Writing better code first time around :)

**Comment by borkdude** [comment]
Seems like a useful optional lint to me!
