### ISSUE TITLE
Missing error for requiring lib under prefix

### ISSUE THREAD

**Issue by DeLaGuardo** [clj-kondo/clj-kondo#1078]
**version**

clj-kondo v2020.11.07

**problem**

require block in namespace declaration can have a prefixed form. Like this

```
(ns prefix.core
  (:require [prefix
             [lib :as lib]
             [core :as core]]))
```

in this form lib names should not have dots otherwise compiler will throw an exception. However clj-kondo is not generating an error or warning for namespace declaration like this:

```
(ns prefix.core
  (:require [prefix
             [lib :as lib]
             [lib.core :as lib.core]]))
```

**repro**

```
echo '(ns some.ns (:require [prefix [lib :as lib] [lib.core :as lib.core]])) (lib/init) (lib.core/init)' | clj-kondo --lint -
```

**expected behavior**

```
(ns prefix.core
  (:require [prefix
             [lib :as lib]
             [lib.core :as lib.core]]))
              ~~~~~~~~
              ^ 
              Found lib name 'lib.core' containing period with prefix 'prefix'.  lib names inside prefix lists must not contain periods  
```

**Comment by jysandy** [comment]
@borkdude shall I pick up this as well? It looks like a change would be needed somewhere here https://github.com/clj-kondo/clj-kondo/blob/master/src/clj_kondo/impl/analyzer/namespace.clj#L246

What would be the correct approach here: throw an exception and stop further linting, or report the error without halting analysis?

In case you were wondering BTW — I have some time available this month, so I thought I might stop by and pick up some issues.

**Comment by borkdude** [comment]
@jysandy Sure!

**Comment by borkdude** [comment]
@jysandy The approach in clj-kondo is always try to continue linting despite errors. Try to make the best of it.
