### ISSUE TITLE
:single-operand-comparison -like linter for `or`, `and`

### ISSUE THREAD

**Issue by vemv** [clj-kondo/clj-kondo#1099]
**Is your feature request related to a problem? Please describe.**

These single-operand expressions:

```clj
(or x)
(and x)
```

...are akin to `(> x)` in that they aways evaluate to a predictable value.

**Describe the solution you'd like**

A  :single-operand-comparison -like linter for `or`, `and`

**Describe alternatives you've considered**

Perhaps the whole notion of single-operand can be extended to even more clojure.core constructs?

Don't know if it has been considered yet.

**Additional context**

As a realistic use case, I sometimes make the mistake of leaving these "stray" ops, because I planned to add a second operand at some point:

```clj
(or x
 ;; <--- I planned to implement some substantial logic here, but defered it, then `git commit`ed the code as-is. Then I can forget about it for a long time
)
```

**Comment by tomdl89** [comment]
Sorry for the noise. Had a go at this one. Feedback very much welcome.

**Comment by borkdude** [comment]
Do we need to merge these linters into a single `:single-operand` linter or should we keep them separate? Would there be a reason for someone to disable one linter for `<` but to enable the other for `and`?

**Comment by tomdl89** [comment]
> Would there be a reason for someone to disable one linter for < but to enable the other for and?

I think that would be very rare, if at all. I think my preference would be to merge them, but I'm not sure about a name for the one linter. `:single-operand...` works for the mathsy comparators, but I feel that `:single-argument...` is more generic..? If we rename the linter, is that not considered a breaking change? If people have configs which disable `:single-operand-comparison`, putting it under a new name will re-enable it. Or is that not a major concern?

**Comment by vemv** [comment]
Thanks for this one! 🙌Thrilled to see this feature :)

> :single-operand... works for the mathsy comparators, but I feel that :single-argument... is more generic..? If

FWIW, `Logical operator` is a pretty common concept, which makes the idea of a `logical operand` also plausible.

`"logical operand"` returns a good amount of Google hits.

**Comment by borkdude** [comment]
OK, let's leave the `:single-operand-comparison` and add a `:single-operand-logical` linter. Both are enabled by default and people can switch those off if they want. More linters = finer grained control over enabling / disabling.

**Comment by borkdude** [comment]
`:single-logical-operand` sounds good.

**Comment by tomdl89** [comment]
Yes that's better. Updated the PR accordingly. Thanks both.
