### ISSUE TITLE
Performance linting rules

### ISSUE THREAD

**Issue by borkdude** [clj-kondo/clj-kondo#1104]
It would be useful to have some assistance of clj-kondo for writing more performant clojure:

- [ ] assoc with more than one kv pair: use only assoc with 1 k/v pair + ->
- [ ] get-in with vector of statically known length: use nested gets

There are many factors in which these rules are or are not good to apply: JIT, bytecode size. So maybe the warnings should not prescribe one specific solution, but should point to some docs in clj-kondo (that could then point to other docs).

Usually these rules will only enabled inside certain performance critical namespaces, so they have to support the namespace local config.

cc @bsless @ikitommi 

Also see https://github.com/bsless/clj-fast.

**Comment by bsless** [comment]
I had some thoughts on the subject recently, does clj-kondo have any means of plugging in profiling data?
If you could cross reference it with some profiling / tracing output we'll know what should be linted

**Comment by borkdude** [comment]
Currently it does not. But it does have a way to run custom hooks and those hooks could perhaps be generated from the data?

**Comment by bsless** [comment]
Needs some hammock time. Profiling guided linting :thinking:

**Comment by borkdude** [comment]
Currently you may start doing this through the `:discouraged-var` linter.

**Comment by bsless** [comment]
I think particular vars and their usage can be discouraged with different severity, i.e. `satisfies?` should have a high severity but `(get-in m [x y z])` should have low severity. `flatten` should probably be mid.
Do you think this linting could be refined to accommodate it?

**Comment by borkdude** [comment]
Yes, we could accommodate a level for each var I think.

**Comment by bsless** [comment]
I can prepare a list of suggestions and severity per var

**Comment by borkdude** [comment]
My thought was that users can configure that themselves.

**Comment by bsless** [comment]
meant the defaults and rules, e.g. `(get-in m xs)` shouldn't be linted but `(get-in m [x y z])` should be
