### ISSUE TITLE
Docker binary statically linked

### ISSUE THREAD

**Issue by GaboFDC** [clj-kondo/clj-kondo#1106]
**Is your feature request related to a problem? Please describe.**
The docker binary built now is not statically linked anymore, since https://github.com/borkdude/clj-kondo/commit/9631d8bbd451050af44b8036ad2e77fb76f05a4b

Is there any specific reason why the static linking was removed?

This makes that the built binary cant be used as-is on other images.

**Describe the solution you'd like**
I think the docker binary could be statically linked again.

**Describe alternatives you've considered**
Use the Linux static asset, but this is not the most reliable solution, for another container wanting to include the binary is way better to just copy it from the official container, instead of doing curl or get to the github generated like, or building it again.

[ Optional: if you are interested in doing a PR yourself, please leave a note. ]
I can create a PR including the static linking again if there is no issue from the maintainer's side.

**Comment by borkdude** [comment]
@GaboFDC This has been done on purpose, since the reverse option (using an alpine / busybox + statically linked clj-kondo) caused problems for other environments. I've chosen a more mainstream base (ubuntu). Users that want a statically linked Docker image can just create one for themselves from the static clj-kondo available through Github releases.

**Comment by borkdude** [comment]
@GaboFDC Informing you that @lispyclouds and I are working on bringing the static docker image back to life under a different tag. Will report here when it's done.

**Comment by borkdude** [comment]
@GaboFDC We now pushed an image to `cljkondo/clj-kondo:2020.12.13-SNAPSHOT-alpine` on Dockerhub. From the next stable version on, you will find the images using the `$VERSION-alpine` tags.

**Comment by GaboFDC** [comment]
Thanks. Will update super linte to use it

**Comment by borkdude** [comment]
@GaboFDC Note that we didn't push `latest` tags yet, we will do that one a new release of clj-kondo comes out (hopefully within at least a few weeks)

**Comment by borkdude** [comment]
@GaboFDC The alpine images now have been released to Dockerhub.
