### ISSUE TITLE
Automatically add .gitignore file in .clj-kondo to ignore .cache directory

### ISSUE THREAD

**Issue by borkdude** [clj-kondo/clj-kondo#1113]

**Comment by PEZ** [comment]
Would this be done for whatever cache-directory the user configures clj-kondo to use?

**Comment by borkdude** [comment]
@PEZ It could be done that way, I think.

**Comment by jr0cket** [comment]
LSP and clj-kondo are tools that work across multiple projects and so assumed any patterns for dot files or directories would be contained within a `.gitignore_global`

If there are configuration files for these tools, then it's assumed they are useful for many projects.  Therefore I would assume their user-level configuration files would be used, e.g `~/.lsp` and `~/.clj-kondo`

Should a team require shared user level config, it can then be shared in a separate repo.  This avoids polluting project with tool specific commits and configs.

**Comment by PEZ** [comment]
I think it can be a good way to prevent people from ignoring too broadly. (Which I almost advised someone to do in another repo. 🤦 )

**Comment by borkdude** [comment]
Another pro argument: people checking out open source project won't accidentally add the cache to their PRs. Not that this ever happened to me, but still.

**Comment by didibus** [comment]
This does not seem to have been done? So I'm assuming for now I should add `.clj-kondo/.cache/` to my `.gitignore`?

**Comment by borkdude** [comment]
Correct, clj-kondo doesn't edit `.gitignore` files
