### ISSUE TITLE
lint-missing-else-branch and lint-single-key-in not called on cljs fns

### ISSUE THREAD

**Issue by tomdl89** [clj-kondo/clj-kondo#1116]
**version**

master

**platform**

native & JVM

**editor**

emacs

**problem**

The `lint-specific-calls!` case form is missing `cljs.core` versions of the fns it checks for `lint-missing-else-branch` and `single-key-in`. Probably just a simple oversight 

**repro**

Lint a cljs file where you have an if-let with a missing else branch, for example

**config**

You need to have `:single-key-in` set to `:warning` to repro `lint-single-key-in`

**expected behavior**

lint cljs too

PR to follow...

**Comment by borkdude** [comment]
@tomdl89 I usually don't close issues until the next release. See https://github.com/clj-kondo/clj-kondo/projects/1
