### ISSUE TITLE
Signature String Analysis

### ISSUE THREAD

**Issue by snoe** [clj-kondo/clj-kondo#1123]
**Is your feature request related to a problem? Please describe.**
In clojure-lsp we display docstrings on hover. Many of clojure.core (and other) functions refer to args by name in the docs. Without knowing how the args are written the docstrings are inscrutible.
See [`get`](https://github.com/clojure/clojure/blob/clojure-1.10.1/src/clj/clojure/core.clj#L1494)

**Describe the solution you'd like**
A `:signatures true` flag on the `:analysis` key could return a list of the arity signatures as written under `:var-definitions`.

**Describe alternatives you've considered**
You could take the sexpr but the fixed-arities and other keys are better at interpreting the signatures for analysis, the string is more useful as is.

Finding arities is one of the trickier bits in analysis, I think kondo analysis is well positioned to provide this.

PR incoming.

**Comment by borkdude** [comment]
@snoe It isn't clear to my why you are not using the sexprs? `:arglists` may be a better name for this which then has the stringified version of what `:arglists` in clojure does?

```
user=> (:arglists (meta #'get))
([map key] [map key not-found])
```

Note that `str` uses a custom printer in clj-kondo, since clj-kondo strips away all whitespace during the rewrite-clj parsing (this is a patch in the fork of rewrite-clj that is vendored in clj-kondo) so there could be whitespace changes between what the user typed and how you return the string.

**Comment by snoe** [comment]
I feel that namespaced keywords obscure the intention of the author who is probably using the `::` syntax for legibility of their arguments, which when considered as a companion of the docstring is why I prefer the string. I believe the sexpr can always be recovered by the string (and the ns), but not vice-versa. In lsp, the sexpr version of the signatures were only useful for linting.

`(defn f1 [{::keys [d]}] d)` => `:signatures [[#:user{:keys [d]}]]`

Good point about arglists, in lsp I combined the two in my analysis, so if `arglists` are defined, it would be returned instead of the written args.

I'm not sure what names would be best here? If we go with arglists or similar, should the feature flag be renamed?

**Comment by borkdude** [comment]
@snoe But if you show `::foo` on hover when you are in a different namespace, this does not accurately reflect what the input should be. `#:foo{:keys ...}` would actually be more appropriate in that case?

**Comment by borkdude** [comment]
All in all, maybe `:arglists-str` is a better name, since that is what this reflects: the original source arglists?

**Comment by snoe** [comment]
@borkdude I've updated the pr.

**Comment by borkdude** [comment]
@snoe @ericdallo Note: I have renamed `:arglists-str` (one string containing all arglists) to `:arglist-strs` (multiple strings representing the source of each arglist).

**Comment by ericdallo** [comment]
Thanks @borkdude, I'll update on clojure-lsp
