### ISSUE TITLE
Support deprecated nss metadata warnings

### ISSUE THREAD

**Issue by SevereOverfl0w** [clj-kondo/clj-kondo#1125]
**Is your feature request related to a problem? Please describe.**

If I require a namespace that's marked deprecated (e.g. clojure.parallel would be after CLJ-706) then it would be nice to know when it's required that it's deprecated.

**Describe the solution you'd like**

A warning similar to the one when using a deprecated namespace, at the point I require a deprecated namespace.

**Additional context**

https://clojure.atlassian.net/browse/CLJ-706 discussing adding this to Clojure itself.

**Comment by borkdude** [comment]
Reopen
