### ISSUE TITLE
spec fdef arity linter

### ISSUE THREAD

**Issue by borkdude** [clj-kondo/clj-kondo#113]
Linter that checks if arities from fdef spec align with function.

**Comment by vemv** [comment]
Other things worth linting:

* duplicated fdef
* fdef that matches no defn in the given ns

WDYT?

**Comment by vemv** [comment]
> Other things worth linting [...]

I was thinking that probably these two could be simply queried at runtime with vanilla clojure, it's simpler than any sort of analysis and also unmistakably accurate.

The atom to be inspected is private though.

**Comment by borkdude** [comment]
I'm considering a combination of runtime info + static analysis. E.g. this feature could also be supported by https://github.com/clj-kondo/inspector.

**Comment by vemv** [comment]
Sounds neat, thanks!
