### ISSUE TITLE
Add `:alias` key to `var-usages`

### ISSUE THREAD

**Issue by snoe** [clj-kondo/clj-kondo#1131]
**Is your feature request related to a problem? Please describe.**
In order to rename an alias in a namespace-usage, clojure-lsp needs to know all the occurrences of that alias. Right now it does not seem possible to differentiate between a var that uses the fully qualified namespace or the alias.

**Describe the solution you'd like**
For the var-usages that refer to an external var using an alias, attach an `:alias` keyword to the analyzed data.

So in the following code, the usage for `bar/a` would not have an alias, and `b/b` would have a ns of `bar` and alias of `b`

```clojure
(ns foo (:require [bar :as b]))
bar/a 
b/b
```

I'm not sure if this should be behind a feature flag or not? 

**Describe alternatives you've considered**

There could be an `alias-usages` bucket for these things, but as far as I know aliases are only used by `keywords` (added in #1129) and `var-usages`.

PR incoming, hopefully in a few days

**Comment by borkdude** [comment]
The proposed solution seems good to me.

**Comment by borkdude** [comment]
Will review tomorrow! Getting late here :)

**Comment by ericdallo** [comment]
I think we can close this, I tested and fix our clojure-lsp issue here https://github.com/clojure-lsp/clojure-lsp/pull/261/files :)
