### ISSUE TITLE
Repeated arities in multi-arity function

### ISSUE THREAD

**Issue by SevereOverfl0w** [clj-kondo/clj-kondo#1136]
**Is your feature request related to a problem? Please describe.**

Doesn't detect error for this code:

```
(defn foo
  ([x] x)
  ([y] (inc y)))
```

**Describe the solution you'd like**

A warning when this is detected.

**Additional context**

Clojure will catch this on eval, so not a big deal really.

**Comment by didibus** [comment]
I'd vote for this to be an `:error`, since it throws an exception when evaluated.
