### ISSUE TITLE
Is JVM clj-kondo parallelizable?

### ISSUE THREAD

**Issue by vemv** [clj-kondo/clj-kondo#1139]
Hi!

As a question (possibly a FAQ or worth reflecting for posterity anyway),

can one invoke clj-kondo through a vanilla JVM (per https://github.com/clj-kondo/clj-kondo/blob/71cfe617c2c11d08c17461b8d445c7169e39c23a/doc/jvm.md#api) in a parallel fashion? Is it thread-safe?

My pattern of usage boils down to `(kondo/run! {:lint the-files})`, while lately I'm wondering if I could speed it up by running `the-files` over a `pmap` or such.

As some context, analyzing a very large project, entirely, even from a properly warmed up JVM can take surprisingly long - think 80s. I was more used to analyzing entire projects with a vanilla JVM in 1-5s.

To be clear, this performance characteristic doesn't have a great importance to me - normally I only run clj-kondo out of `git diff --name-only $branch master` so linting a whole project isn't a representative workload.

Thanks - V

**Comment by borkdude** [comment]
@vemv clj-kondo has a `:parallel true` option which should do this automatically for you. If you are solely linting for the side effect of populating the cache, then also enable `:no-warnings true`, then clj-kondo will skip already linted jar files.

**Comment by vemv** [comment]
Oh TIL!

Will try out, thank you.
