### ISSUE TITLE
Compilation fails after v2021.01.20 release

### ISSUE THREAD

**Issue by avirogalsky** [clj-kondo/clj-kondo#1142]
Hi it looks like the compilation stage fails when running `lein clj-kndo --lint`,
it has the following errors:

Syntax error (FileNotFoundException) compiling at (edamame/impl/parser.cljc:1:1).
Could not locate clojure/tools/reader/impl/inspect__init.class, clojure/tools/reader/impl/inspect.clj or clojure/tools/reader/impl/inspect.cljc on classpath.

Adding `[borkdude/edamame "0.0.11-alpha.28"]` to the dependencies solves the issue.
We cannot find any mention of that in the change log.

**Comment by borkdude** [comment]
clj-kondo 2021.01.20 depends on sci 0.2.1 and sci 0.2.1 depends on borkdude/edamame "0.0.11-alpha.28". So I'm not sure why your error appears. I cannot reproduce this with 

```
:dependencies [[clj-kondo "2021.01.20"]]
:aliases {"clj-kondo" ["run" "-m" "clj-kondo.main"]}
```
in my `.lein/profiles.clj`.

**Comment by borkdude** [comment]
It could be that you are using an older version of tools.reader in one of your deps and this gets prioritized somehow.

**Comment by avirogalsky** [comment]
You right it was our problem,
old version of `org.clojure/core.async` issue
thanks for the help!
