### ISSUE TITLE
Suggestion: warn if the name of a binding that *is* in use starts with an underscore

### ISSUE THREAD

**Issue by aviflax** [clj-kondo/clj-kondo#1149]
**Is your feature request related to a problem? Please describe.**

I find it very handy when clj-kondo warns me of unused bindings. Sometimes I’ll just prepend an underscore to the name of the binding, as it can sometimes be handy as a form of documentation.

Then, sometimes I will later end up using the binding for something, and sometimes I will forget to remove the underscore from the front of the name.

It’s an edge case of an edge case, but it feels to me like the kind of thing that would match cli-kondo’s “I’ve got your back” ethos.

**Describe the solution you'd like**

A warning if/when the name of a binding starts with an underscore (_) *and* the binding is in use (referenced).

**Describe alternatives you've considered**

It’s quite an edge case, so we could just skip it. It’s not a big deal at all.

**Additional context**

🤷

----

Thanks!

**Comment by borkdude** [comment]
@aviflax This question has come up a couple of times, so I'll leave this open. Do you have a suggestion for this linter? Maybe `:used-underscored-binding`?

**Comment by aviflax** [comment]
Yeah, that’ll work nicely. A slightly different possible variation might be `underscored-binding-in-use` but I’d think consistency with the rest of the linter rules is more important, and I’m not super familiar with them right now.

**Comment by borkdude** [comment]
Released.
