### ISSUE TITLE
Sugeestions: Support namespace aliasing and implicitly importing namespace for linter (For Babashka)

### ISSUE THREAD

**Issue by glyh** [clj-kondo/clj-kondo#1158]
**Is your feature request related to a problem? Please describe.**

Although babashka acts nearly as if it's clojure, there's some namespace stuff built-in in babashka.

I know I can just ignore the unresolved namespace, but this seems disable some further linting which have relationship with the namespace. 

**Describe the solution you'd like**

+ **Namespace aliasing**

  Say, we have namespace "csv", this would be linted to "clojure.data.csv"

  I've tried current lint-as options, it seems it wants some "Expected fully qualified symbol" rather than a namespace. 

+ **Implicitly importing namespace**
  
  Also for "clojure.data.csv", this is actually built-in in bb, so refer to the function in it won't result in unknown namespace errors or whatever. 

  I guess it could be done through ignore some namespace, but I find if we ignore some namespace, further linting are not possible. 

Since you know nothing about the namespace, excepte it exists. 

**Describe alternatives you've considered**

Existed `unresolved-namespace` options. 

**Additional context**

I really like your projects, thank you for your contribution to the community dude. 

[ Optional: if you are interested in doing a PR yourself, please leave a note. ]

**Comment by glyh** [comment]
Also, I think it would be great if clj-kondo can just recognize the shebang in the Babashka script. 

But seems like this requires more work.

**Comment by borkdude** [comment]
Hi @glyh, babashka recommends requiring the namespaces for clarity: https://book.babashka.org/#_explicit_requires

Not everyone reading your scripts might be familiar with some of the default aliases in the user namespace.
I think it's better if you stick with explicit requires in scripts. The default aliases are there only for quick one-liners on the command line.

**Comment by glyh** [comment]
Thank you, @borkdude . I'll add some explicit requires in the scripts.
