### ISSUE TITLE
[Analysis] Support custom :def on keywords

### ISSUE THREAD

**Issue by ericdallo** [clj-kondo/clj-kondo#1159]
**Is your feature request related to a problem? Please describe.**
ATM clojure-lsp check if the keywords analysis bucket has a `:def` and mark as a definition for find definition, we don't even need to check what is the value. it'd be nice to have this functionality for some macros that define vars with keywords, like `re-frame.core/reg-event-fx :foo/bar`.

**Describe the solution you'd like**
clj-kondo do that automatically or provide a way to inform which macros register defs like that.

Slack discussion about that https://clojurians.slack.com/archives/CPABC1H61/p1612530939344500

**Comment by borkdude** [comment]
@ericdallo It might be better to just take screenshots from Slack discussions as these links tend to go stale. 

Was your idea to have a config like `{:keyword-defs [re-frame.core/reg-event-fx]}` to indicate which functions "define" keywords?

**Comment by borkdude** [comment]
We can already do this with hooks, but maybe adding built-in support for popular libraries like `re-frame` is a good alternative, I think it's the most requested library for this feature.

**Comment by ericdallo** [comment]
![image](https://user-images.githubusercontent.com/7820865/115924382-056b6880-a456-11eb-9e98-9898fba4c3e9.png)
![image](https://user-images.githubusercontent.com/7820865/115924412-0f8d6700-a456-11eb-8922-1340c22eb3dd.png)

**Comment by borkdude** [comment]
@ericdallo Thank, but I actually meant the link in the original post: https://clojurians.slack.com/archives/CPABC1H61/p1612530939344500 :)

**Comment by eval-on-point** [comment]
Some clarifying information in the re-frame Slack channel:

> Mitch:
> There is some discussion in the #lsp about adding code navigation to re-frame registry and a few questions are popping up. Light testing shows that the two scenarios below work in re-frame, but it is unclear whether they are defined behavior: 
> 1. Is it specified whether you are allowed to register the same id to different kinds? (e.g. Could I register :start as a subscription and a coeffect?)
> 2. Is it specified whether id's need to be keywords? For example, registering 'a-symbol as an event handler works.

> p-himik:
> 1. You can. All handler kinds are independent. You can use :start as a subscription ID, an event ID, an effect ID, a coeffect ID - all at the same time.
> 2. IDs can be anything.

> mikethompson: confirmed

1. To handle the case where there are multiple registrations of he same keyword (e.g. a keyword could be both a re-frame event and a spec), `:def` might extended to allow for a collection of definitions, and an additional linter might be made to warn against multiple definitions. I am not too familiar with kondo internals (including how the `:def` keyword currently gets used by kondo), so do not know how feasible this would be.
2. Handling non-keyword registrations is out of the scope of this issue. I doubt that there are many users who would actually need this feature.

As for the naming of the `:def` key, `:registrations` might be a better description. Both re-frame and spec use that terminology, after all.

**Comment by borkdude** [comment]
I agree about the name, `:def` is a poor name and I've literally spent a few hours coming up with an alternative.
But I gave up, because naming is too hard. https://github.com/clj-kondo/clj-kondo/issues/1211

Instead of `:def` we could use `:reg` and for keyword references we could use `:ref`. But that would be breaking for people already using the analysis output, although I suspect LSP is only big user of that.

https://twitter.com/borkdude/status/1383330126549577731
