### ISSUE TITLE
Keyword analysis generates invalid symbols

### ISSUE THREAD

**Issue by rvlo** [clj-kondo/clj-kondo#1160]
**version**

master branch
commit 7856980a26f5b278b4b793401cc8a765ff8bc652

**problem**

Keyword analysis generates invalid symbols when keyword names start with digits.

The generated symbols can be serialized, but can't be parsed back by the reader.

Neither symbols nor keywords can start with a numeric character. But
somehow the reader doesn't complain when keywords do and throws an
exception when symbols do.

Reference: https://clojure.org/reference/reader#_symbols
"Symbols begin with a non-numeric character and can contain alphanumeric
characters and *, +, !, -, _, ', ?, <, > and = (other characters may be
allowed eventually)."

The keywords topic (https://clojure.org/reference/reader#_literals)
states: "Keywords - Keywords are like symbols, except...". And there is
no exception regarding beginning with a numeric character.

This particular bug is preventing clojure-lsp from reloading previous
analysis from sqlite.db, when analyzed code had keywords starting with
digits.

An example of such invalid keywords in a popular library is (latest master commit, as of today):
https://github.com/ptaoussanis/timbre/blob/7bb3d648e1a49cf835233785fe2c07e43b2395da/project.clj

I'm submitting a PR with a test and a fix that inserts an underscore before the digit so the symbol won't be invalid. This at least stops breaking code that relies on the analysis. I believe that clj-kondo should report such keywords as invalid, but I don't know the best path to take.

**Comment by borkdude** [comment]
@rvlo I'll merge your PR and will add some syntax error linting around this. I think it's best if the keyword is then not reported in the analysis, since it wasn't a proper keyword to begin with. You might also want to create a PR for timbre to fix this.

/cc @ptaoussanis

**Comment by rvlo** [comment]
@borkdude 
> I think it's best if the keyword is then not reported in the analysis, since it wasn't a proper keyword to begin with.

I agree. Could you point me to the right place (file/function) to implement the check? It seems to me that you're relying on `clojure.edn/read-string` to detect an invalid keyword. And I don't know why it does not (per the docs I referenced).

Just after I made this, I loaded a project of mine and encountered a new case, in another popular lib (latest commit as of today):
https://github.com/day8/re-frame-10x/blob/dce83cf758bdd7a80a75a3f3bd19418ee48ea977/src/day8/re_frame_10x/view/history.cljs

The keyword found in the file is `:#--re-frame-10x--`. When trying to read the serialized result, the reader thinks it's a reader macro and throws.

I already implemented a check that follows what is described in the reader reference page and had no more problems. If you point me in the right direction to insert the check, I can submit a new PR.

PS: Thank you for your work on clj-kondo et al!

**Comment by borkdude** [comment]
For now I reverted the PR. The reason you cannot read symbols that start with a number is that anything that starts with a number parses as a number.

``` clojure
(type (clojure.edn/read-string (str (symbol (keyword "1"))))) ;;=> java.lang.Long
```

```
(type (clojure.edn/read-string (str (symbol (keyword "1foobar"))))) ;;=> invalid number
```

I'm not sure yet what is the best place to fix it and how to detect this reliably. Maybe it's safest to produce the name as a string and leave it as such.

**Comment by borkdude** [comment]
Maybe something like `(try (symbol (name the-keyword)) (catch Exception e (findings/reg-finding! ctx ... )))` will work.

Where `reg-finding!` emits a `:syntax` lint warning with the message `"Invalid keyword: ..."`.

**Comment by rvlo** [comment]
> I'm not sure yet what is the best place to fix it and how to detect this reliably. Maybe it's safest to produce the name as a string and leave it as such.

So there is no reason it is converted to a symbol in the first place?

Leaving it as a string would avoid exceptions being thrown when reading. But as a few comments on clojure docs say: "somewhere, some time, your code may blow up in the future". Since the keywords are nonetheless invalid, per the clojure reader doc.

One of the problems is this: `(symbol "2wrong")` works. Try it out in the repl.

**Comment by borkdude** [comment]
For now this is fixed by saving the `:name` of the keyword as a string. We might add more linting for invalid keywords. Feel free to add an issue about this as an enhancement to clj-kondo.
