### ISSUE TITLE
BREAKING: hook + lint-as discrepancy

### ISSUE THREAD

**Issue by borkdude** [clj-kondo/clj-kondo#1170]
The way it currently works is that you can build hooks for foo/bar and if you lint-as foo/baz as foo/bar, you will automatically also get the hook expansion for foo/baz as well.

I guess we could change this as follows:

Users should just configure foo/baz to use the foo/bar hook explicitly, instead of relying on lint-as.

The use case is when users build a hook for clojure.core/defn but also have a lint-as for foo.bar/defn -> clojure.core/defn, you currently can't see what the original call was, if the call was not qualified.

**Comment by borkdude** [comment]
We will have to change this config: https://github.com/clj-kondo/config/blob/master/resources/clj-kondo.exports/clj-kondo/rum/config.edn

**Comment by thumbnail** [comment]
I tested 4994ccb with a custom hook on `def` and it seems to work. Awesome ⚡ !
