### ISSUE TITLE
excluding clojure.test from the `:refer` linter

### ISSUE THREAD

**Issue by NickeZ** [clj-kondo/clj-kondo#1172]
**Is your feature request related to a problem? Please describe.**
When I use clj-kondo together with less clever linters like "joker" I cannot find a way to include clojure.test that satisfies both linters and my own aesthetics.

**Describe the solution you'd like**
I would like to be able to write `(:require [clojure.test :refer [deftest])`, but at the same time disallow `:refer` in general.

**Describe alternatives you've considered**
`(:require [clojure.test :as t])` and `(:require [clojure.test :refer :all])`. The first one I find "ugly", the second one doesn't work with joker since it is not as clever as clj-kondo.

**Comment by borkdude** [comment]
Pushed to master.
