### ISSUE TITLE
[analysis] Missing position for findings in some cases 

### ISSUE THREAD

**Issue by ericdallo** [clj-kondo/clj-kondo#1193]
**version**

`2021.03.03`

**platform**

JVM

**editor**

command line

**problem**

It seems for some cases where user use hooks and macros, clj-kondo doesn't return the row and col for a finding.

**repro**

[repro](https://github.com/lucywang000/bugs-repro/blob/master/repro-clojure-lsp/src/repro.clj)

First we scan the whole classpath:
```bash
$ clj -Sdeps '{:deps {clj-kondo {:mvn/version "2021.03.03"}}}' -m clj-kondo.main  --lint $(lein classpath)
```
Then we lint that specific file and get the findings to check what is returned by clj-kondo to clojure-lsp:
```bash
$ clj -Sdeps '{:deps {clj-kondo {:mvn/version "2021.03.03"}}}' -m clj-kondo.main  --lint src/repro.clj --config '{:output {:format :json}}' | jq .

{
  "findings": [
    {
      "type": "unused-binding",
      "filename": "src/repro.clj",
      "message": "unused binding foo",
      "row": null,
      "col": null,
      "end-row": null,
      "end-col": null,
      "level": "warning"
    },
    {
      "type": "unresolved-symbol",
      "filename": "src/repro.clj",
      "message": "Unresolved symbol: foo1",
      "row": 15,
      "col": 7,
      "end-row": 15,
      "end-col": 11,
      "level": "error"
    }
  ],
  "summary": {
    "error": 1,
    "warning": 1,
    "info": 0,
    "type": "summary",
    "duration": 363,
    "files": 1
  }
}

```
We can see that the `unused binding foo` has no row/col, clojure-lsp can't return the finding to LSP client, so we are ignoring that finding ATM.

**config**

[clj-kondo config](https://github.com/lucywang000/bugs-repro/blob/master/repro-clojure-lsp/.clj-kondo/config.edn)
[custom hook code](https://github.com/lucywang000/bugs-repro/blob/master/repro-clojure-lsp/.clj-kondo/hooks/custom.clj)

**expected behavior**

Return at least the `row` and `col` for that finding.

Related to https://github.com/clojure-lsp/clojure-lsp/pull/354

**Comment by borkdude** [comment]
This can happen in hook code if the user doesn't add row/col metadata to a generated node. 

I'll take a look.

**Comment by ericdallo** [comment]
Oh, good to know, thanks!
