### ISSUE TITLE
Expose config key to hook function argument

### ISSUE THREAD

**Issue by not-in-stock** [clj-kondo/clj-kondo#1198]
**Is your feature request related to a problem? Please describe.**
Fundamentally there're two ways of building a new linter. It is either a `hook` or `analysis`-based linter.
While `analysis`-based linter can process most of the useful linting context keys, at the same time `hooks` are limited by only 5: `:node`, `:expr`, `:cljc`, `:lang`, `:filename`. 
Also in a `hook` a `reg-finding!` function can be used, but the corresponding keyword has to be mentioned in the config to enable its presence in the output. Looks like a good place for a configuration, but unfortunately, the `config` can't be reached from it.  
On the other side `analysis`-based linter can be used to access the `config`, but it deals with the information provided by `analysis`, and `findings` which is also a limiting to access individual `node`. The other downside is that I wasn't able to configure `flycheck-clj-kondo` to include my custom `analysis`-based linter to in-editor static analysis. 

**Describe the solution you'd like**
Initially, I'd suggest exposing `config` key to hook function to gather configuration from it.
I suppose there're some other useful keys, but I came up with this one.
This would also can help to broaden point 5 from Design Principles to hooks.  

**Describe alternatives you've considered**
1. Considering keeping my custom linter configuration in the hook source file. I find that an ugly practice because the configuration is split between two files now, would like to keep it in `config.edn`
2. Considering using `analysis`-based linter for the case where I'm processing `ns` form. It's enough information in `config` and `analysis` keys but in this case I'm losing `flycheck-clj-kondo` highlights in my editor.

I'd like to make PR myself since the change looks trivial.

**Comment by borkdude** [comment]
> Also in a hook a reg-finding! function can be used, but the corresponding keyword has to be mentioned in the config to enable its presence in the output. Looks like a good place for a configuration, but unfortunately, the config can't be reached from it.

This is by design. Users should opt in on new linters from hook code themselves. 

What would you do with the config if this was available in the hook input map?

**Comment by not-in-stock** [comment]
Thanks for the answer!

Basically, I'd like to configure hooks with a similar degree of control as built-in linters,
and have results shown in the editor.

e.g. Let's assume I have several libs in my codebase which I need to deliberately substitute or deprecate.
It looks like that it can be highlighted in the editor and in CI pipeline by linting. It also makes it available for other developers.

In `config.edn`
```clojure
{:linters {:foo/linter {:level :warning
                       :namespaces {libnamespace.to.substitute suggested.new.lib
                                    deprecated.old.lib nil}}}
 :hooks {:analyze-call {clojure.core/ns lint-hooks/foo-linter}}}
```
In `lint_hooks.clj`

```clojure

(defn used-namesapces [ns-node]
  ...)

(defn foo-linter [{:keys [node config]}]
  (let [ns->replacement (-> config :linters :my/linter :namespaces)]
    (doseq [used-namespace (used-namesapces node)
            :when (contains? ns->replacement used-namespace)
            {:keys [row col]} (meta used-namespace)]
      (if-let [replacement (ns->replacement used-namespace)]
        (api/reg-finding! {:message (str "Namespace " used-namespace " is deprecated.")
                           :type :my/linter
                           :row row
                           :col col})
        (api/reg-finding! {:message (str "Namespace " used-namespace " is deprecated."
                                         " Please use " replacement ".")
                           :type :foo/linter
                           :row row
                           :col col})))))
```
In editor

<img width="503" alt="Screenshot 2021-03-08 at 14 13 58" src="https://user-images.githubusercontent.com/2552874/110314227-a2924f00-8018-11eb-9f7c-78e4adc87b91.png">

**Comment by borkdude** [comment]
Aah, I see. So you want to check the config if you should emit a warning. Yes, I think that makes sense.

**Comment by not-in-stock** [comment]
Yes, exactly.

**Comment by borkdude** [comment]
OK, PR welcome.

**Comment by borkdude** [comment]
Already fixed.
