### ISSUE TITLE
Ignore unused-binding when a function returns an anonymous function that has the same params.

### ISSUE THREAD

**Issue by sirmspencer** [clj-kondo/clj-kondo#1204]
**Is your feature request related to a problem? Please describe.**
In reagent it is common to create a function that returns an anonymous function with the same parameters.  It would be great if we could ignore `unused-binding` in both declarations if the parameters match.

**Describe the solution you'd like**
In this code there is a unused-binding warning for param1 in the test-function declaration and for param2 in the anonymous function declaration. 

```
(defn test-function [param1 param2]
  (println param2)
  (fn [param1 param2] (println param1)))
```

Since the two declarations match, this is a reagent component so Id like to be able to ignore those warnings.  I dont think its particularly important to check that the function is returning the anonymous function, just that it is defined within its function body. 
 See #1203, If the shadowing rule were to be updated, Id also like to see that be ignorable when the two declarations match.

**Comment by sirmspencer** [comment]
This could be related to #1188 since we are both asking for exceptions to the same rule.

**Comment by borkdude** [comment]
#1188 is specifically about unused function arguments, so it's a different case. 

As for your rule, this would be a case of locals shadowing locals. The `:shadowed-var` linter only warns about locals shadowing vars. So this would be a different kind of linter and your function case would be only one specific example of a more general `:shadowed-binding` linter. I'm not sure if people are going to use that linter much if it exists, since I haven't even heard many people use `:shadowed-var`. I have tried to use it myself, but I found it too strict...

**Comment by borkdude** [comment]
It would be great if we had a way to statically know if something is a reagent component, so we can apply that rule there only. Also see #25.

**Comment by sirmspencer** [comment]
While #25 would also be nice to have, but these are not related. 

I dont think this exception needs to care if it is reagent specifically.  Its a specific use case to define an anonymous function with the same params as the main function.  There could be other libraries that do the same thing (im thinking any react based library might do so).

**Comment by borkdude** [comment]
I'm not aware of any libraries that need this as much as reagent components. It is related to #25 in the sense that we cannot statically know if we're dealing with reagent just by looking at the function.

**Comment by sirmspencer** [comment]
> I'm not aware of any libraries that need this as much as reagent components. It is related to #25 in the sense that we cannot statically know if we're dealing with reagent just by looking at the function.

I still dont think you need to know that its reagent to do this. ANY anonymous function inside a function body with matching params can be ignored.

**Comment by borkdude** [comment]
I can see why you would want this with reagent components, but not so much for other use cases. Can you explain to me what other libraries would benefit from this?

**Comment by sirmspencer** [comment]
> I can see why you would want this with reagent components, but not so much for other use cases. Can you explain to me what other libraries would benefit from this?

I dont use any other libraries that use this.  Heres the counter point, when would anyone ever define a anonymous function in this form unless it was reagent?  It seems pretty safe to add the rule exception without knowing what libraries the project is using.
