### ISSUE TITLE
[analysis] missing defined-by on most var-definition bucket analysis

### ISSUE THREAD

**Issue by ericdallo** [clj-kondo/clj-kondo#1216]
**Is your feature request related to a problem? Please describe.**
I'd like to know which `defined-by` a var-defintion has. ATM clj-kondo only send that for `clojure.test/deftest`

**Describe the solution you'd like**
Maybe always include the `defined-by` with the function/macro symbol that defines it?

**Describe alternatives you've considered**

**Additional context**
[Discussion](https://clojurians.slack.com/archives/CHY97NXE2/p1615997011038300)

**Comment by borkdude** [comment]
PR welcome.

**Comment by ericdallo** [comment]
@borkdude, does that makes sense to you always include the `defined-by` function, even if it's a `defn` or `def`?

**Comment by borkdude** [comment]
Maybe it's nice to see if a var was defined by `clojure.core/def` instead of `clojure.core/defn`

**Comment by ericdallo** [comment]
@borkdude I started to implement that, is there any way to get the `namespace/symbol` of the var on [this function](https://github.com/clj-kondo/clj-kondo/blob/master/src/clj_kondo/impl/analyzer.clj#L427)?
I only found `call` [here](https://github.com/clj-kondo/clj-kondo/blob/master/src/clj_kondo/impl/analyzer.clj#L433) that only has the symbol name, not the ns

**Comment by borkdude** [comment]
@ericdallo I think it's better to pass that as a parameter from here:

https://github.com/clj-kondo/clj-kondo/blob/3f63419f29915018fff4a1611458a6699ca53cad/src/clj_kondo/impl/analyzer.clj#L1463

So add an extra argument at every call of analyze-def(n) so it's easier to track what the original defining macro was.

**Comment by ericdallo** [comment]
Thanks for the help and the patience @borkdude, I'll make the proper changes and tests on `clojure-lsp`
