### ISSUE TITLE
Support for the defcurried functions in clojure.core.reducers

### ISSUE THREAD

**Issue by dpassen** [clj-kondo/clj-kondo#1217]
**Is your feature request related to a problem? Please describe.**
When using clj-kondo v2021.03.03, it appears that the clojure.core.reducers functions defined in terms of `defcurried` (https://github.com/clojure/clojure/blob/57f7c6ea164271d92cec5a12d22043c7029e3de2/src/clj/clojure/core/reducers.clj#L106) are not known and result in an `Unresolved var` warning.

**Describe the solution you'd like**
These eight functions `clojure.core.reducers/(map, mapcat, filter, remove, flatten, take-while, take, drop)` should be recognized by clj-kondo

**Comment by borkdude** [comment]
Fixed on master
