### ISSUE TITLE
Optionally report duplicates

### ISSUE THREAD

**Issue by snoe** [clj-kondo/clj-kondo#1232]
**Is your feature request related to a problem? Please describe.**
In clojure-lsp it's possible to edit a file to produce many unresolved-var or unresolved-symbol lints, but the current behaviour is to only report the first occurence and swallow to subsequent ones. So a user has to find errors, fix the first one then find errors again, then fix the next etc... Many editors provide good support to navigate to all your diagnostics and this behavior neuters this functionality.

**Describe the solution you'd like**
Spoke with @borkdude, we'd like to add a config flag on each affected linter `report-duplicates` that when nil (default) or otherwise non-truthy would maintain the existing behaviour and when truthy would return all of the lint occurrences.

**Describe alternatives you've considered**
Talked about top level configuration for the desired behaviour but since most linters already report duplicates this seems like a nice, specific solution that can be extended anywhere ignoring duplicates is introduced later.

PR incoming

**Comment by borkdude** [comment]
Already fixed.
