### ISSUE TITLE
Consider linting for namespace names that do not match source filename

### ISSUE THREAD

**Issue by lread** [clj-kondo/clj-kondo#1240]
**Is your feature request related to a problem? Please describe.**
While testing out bb 3.1 SNAPSHOT tasks on my rewrite-clj scripts, I noticed that a few of my bb scripts had wonky namespace names. For examples:
- I had accidentally used `clj_tests` instead of `clj-tests` for a `clj_tests.clj` script. 
- Or I had maybe renamed a script filename and not adjusted the namespace name within the file.

I noticed my error because wonky namespace names do not matter for bb scripts, but they do for bb 3.1 SNAPSHOT tasks.

**Describe the solution you'd like**
Warn when a namespace name does not match the dirs/filename.

A linter perhaps called `:namespace-name-mismatch` with message:
`Namespace name foo_booboo.bar does not match expected foo-boo.boo.bar`

**Describe alternatives you've considered**
Could do nothing: one discovers pretty quickly through usage when one's namespace names are wonky, but I think a linter would be nice here. You could discover your error more quickly in the editor.

**Additional context**
I suppose an editor linter integration would have to be smart enough to be aware of filename changes.

**Comment by borkdude** [comment]
Related / duplicate: https://github.com/clj-kondo/clj-kondo/issues/842

But please keep it open since you have more details than the other one.

**Comment by lread** [comment]
@borkdude, I just happened to notice this one is still open, can be closed ya?

**Comment by borkdude** [comment]
Thanks
