### ISSUE TITLE
Keyword analysis for namespaced maps

### ISSUE THREAD

**Issue by borkdude** [clj-kondo/clj-kondo#1251]
The key `:clojure.set/foo` occurs 4 times here:

```
(require '[clojure.set :as foo])

::foo/bar
:clojure.set/bar
{:clojure.set/bar 1}
#:clojure.set{:bar 1}
```

but clj-kondo only reports the first three.

**Comment by borkdude** [comment]
cc @snoe @ericdallo

**Comment by ericdallo** [comment]
I need to say that I didn't even know that full qualified ns namespace keys was possible on clojure 😅

**Comment by borkdude** [comment]
Should work now on master.

**Comment by ericdallo** [comment]
Nice, I'll try soon, thank you!
