### ISSUE TITLE
Consider refinining messaging around importing configs

### ISSUE THREAD

**Issue by lread** [clj-kondo/clj-kondo#1256]
**Is your feature request related to a problem? Please describe.**
I am trying out importing and exporting clj-kondo configs. Very cool, thanks for this!

When I run [clj-kondo as described to import configs](https://github.com/clj-kondo/clj-kondo/blob/master/doc/config.md#exporting-and-importing-configuration), I get the message:
```
Copied config to .clj-kondo/lread/status-line. Consider adding lread/status-line to :config-paths in .clj-kondo/config.edn.
```
This is good, but maybe could be improved based on what steps I've already taken.

**Describe the solution you'd like**
Here are some initial ideas:

Scenario 1: I have not added exported config to my clj-kondo config. Only minor tweaks to existing message:
```
New import config found: .clj-kondo/lread/status-line. To enable linting, add "lread/status-line" to :config-paths in .clj-kondo/config.edn.
```

Scenario 2: I have already added exported config to my clj-kondo config
Scenario 2a: And the exported config has changed
```
Import config has changed: .clj-kondo/lread-status-line. 
```
Scenario 2b: And the exported config is unchanged. Maybe no messaging is necessary here.

**Describe alternatives you've considered**
Always an option to do nothing if you think existing messaging is good.

**Additional context**
None.

I could do this work if there is an interest, lemme know.

**Comment by borkdude** [comment]
I think we only need a message for scenario 1 since with scenario 2 there is no action needed from the user (and it saves us checking if the file has really changed, which can get a little hairy).

**Comment by lread** [comment]
Yeah that would work.  Git diff will tell the story about scenario 2a.

**Comment by borkdude** [comment]
OK, PR welcome!

**Comment by lread** [comment]
Finally working on this.

After playing a bit, I propose a slight rewording:
```
Import config found and copied to .clj-kondo/lread/status-line. To enable linting, add "lread/status-line" to :config-paths in .clj-kondo/config.edn.
```

**Comment by borkdude** [comment]
What about:

> Imported config to .clj-kondo/lread/status-line. To activate, add "lread/status-line" to :config-paths in .clj-kondo/config.edn.

And if the config was already activated, print nothing?
