### ISSUE TITLE
New (musl-based) static Linux binary hangs indefinitely on FreeBSD

### ISSUE THREAD

**Issue by ak-coram** [clj-kondo/clj-kondo#1291]
I'm not sure whether you want to address this issue at all, but I thought it might be useful to know about it nonetheless. The non-static native binary works fine for me, so I have an easy workaround. I'm not even sure if this is related to the recent musl change, but it is the most obvious suspect.

**version**
v2021.06.01

**platform**
Native static Linux binary on FreeBSD 13.0 (amd64)

**problem**
I used to run the static binary without problems using Linux binary compatibility, but it seems to hang indefinitely with the new version.

**Comment by borkdude** [comment]
@ak-coram Any specific usage to trigger this?

**Comment by ak-coram** [comment]
@borkdude: for example `clj-kondo --help` hangs for me, while it works with the non-static build.

**Comment by borkdude** [comment]
@ak-coram Hmm, I can't reproduce this within the Alpine image:

```
$ docker run --rm -it cljkondo/clj-kondo:2021.06.01-alpine /bin/sh
/ # echo '(inc :foo)' | clj-kondo --lint -
<stdin>:1:6: error: Expected: number, received: keyword.
linting took 6ms, errors: 1, warnings: 0
```

**Comment by borkdude** [comment]
Similar when I download the static binary in an ubuntu Docker image.

**Comment by ak-coram** [comment]
@borkdude: I assume this only happens on FreeBSD, using Linux binary compatibility to run the static binary :)

As I mentioned I'm not sure whether you want to do anything about this at all, since it probably doesn't affect many people (and they also have a workaround: running the non-static binary).

**Comment by borkdude** [comment]
Ah, FreeBSD, sorry missed that! I will leave this issue open for anyone with useful feedback on this.
