### ISSUE TITLE
Slightly improve :refer suggestion

### ISSUE THREAD

**Issue by vemv** [clj-kondo/clj-kondo#1293]
When clj-kondo suggests `use :require with alias or :refer with [foo]`, it could say instead:

`use :require with alias or :refer [foo]`

...by removing the `with`, one can copy-paste the `:refer [foo]` suggestion with fewer keystrokes.

wdyt?

Thanks - V

**Comment by borkdude** [comment]
Yes, makes sense.

**Comment by borkdude** [comment]
Still on the TODO list!
