### ISSUE TITLE
:skip-comments false doesn't override :skip-comments true in namespace config

### ISSUE THREAD

**Issue by borkdude** [clj-kondo/clj-kondo#1295]
Repro:

Project config: `{:skip-comments true}` 
Local config: 

``` clojure
(ns foo
  {:clj-kondo/config {:skip-comments false}}
  (:require [clojure.string :as str]))

(comment

  (str/join [])
  )
```

You should not see the namespace `clojure.string` as unused here. 

cc @robert-stuttaford

**Comment by borkdude** [comment]
@robert-stuttaford Fixed on master.

**Comment by robert-stuttaford** [comment]
Thank you @borkdude !
