### ISSUE TITLE
False positive `duplicate element set` for symbols/classes

### ISSUE THREAD

**Issue by vemv** [clj-kondo/clj-kondo#1296]
> **Sponsor**

**version**

[clj-kondo "2021.06.01"]

**platform**

JVM

**problem**

`#{clojure.lang.Util 'clojure.lang.Util}` will report `error: duplicate set element clojure.lang.Util`

**Comment by borkdude** [comment]
Fixed on master.

**Comment by vemv** [comment]
Awesome, thank you!
