### ISSUE TITLE
Alias created namespace - unresolved

### ISSUE THREAD

**Issue by nikolavojicic** [clj-kondo/clj-kondo#1313]
**version**

`clj-kondo-2021.06.18-windows-amd64`

**problem**

Namespace alias is not recognized when the second argument in `alias` function is s-expression.

**repro**

```clojure
(alias 'sn (create-ns 'some-namespace))
::sn/foo ;=> :some-namespace/foo
```

Reports `Unresolved namespace sn. Are you missing a require?` for `::sn/foo`

**workaround**

```clojure
(create-ns 'some-namespace)
(alias 'sn 'some-namespace)
::sn/foo ;=> :some-namespace/foo
```

**Comment by borkdude** [comment]
@nikolavojicic Clojure 1.11.0-alpha2 now supports `:alias-as` for this use case. The newest clj-kondo now supports this. Perhaps you can upgrade to that and get rid of the `(create-ns ..)` altogether.
