### ISSUE TITLE
invalid edn produced in analysis mode where namespace is a shadow-cljs style import spec of a npm scoped package (starts with a @)

### ISSUE THREAD

**Issue by xlfe** [clj-kondo/clj-kondo#1319]
**version**

clj-kondo v2021.06.18

**platform**

native - linux

**problem**

I was having a look at the analysis mode of clj-kondo, but was getting a Exception when trying to pipe the output to jet

looks like when there are requires with [npm scoped packages](https://docs.npmjs.com/about-scopes) using the [shadow-cljs import spec](https://shadow-cljs.github.io/docs/UsersGuide.html#_using_npm_packages) clj-kondo emits the package name as a symbol in edn, but I'm guessing "Invalid leading character: @" means it's not valid?

**repro**

```bash
echo '(ns test (:require ["@material-ui/core" :default mui]))' | ./clj-kondo --lint - --config '{:output {:analysis true :format :edn}}' 
{:findings [{:end-row 1, :ns @material-ui/core, :type :unused-namespace, :level :warning, :filename "<stdin>", :col 21, :end-col 40, :message "namespace @material-ui/core is required but never used", :row 1} {:end-row 1, :ns @material-ui/core, :type :unused-referred-var, :level :warning, :filename "<stdin>", :col 50, :end-col 53, :message "#'@material-ui/core/mui is referred but never used", :refer mui, :row 1}], :summary {:error 0, :warning 2, :info 0, :type :summary, :duration 7, :files 1}, :analysis {:namespace-definitions [{:filename "<stdin>", :row 1, :col 1, :name test, :name-row 1, :name-col 5, :name-end-row 1, :name-end-col 9}], :namespace-usages [{:name-end-col 40, :name-end-row 1, :name-row 1, :alias-end-row nil, :alias-row nil, :filename "<stdin>", :from test, :col 21, :name-col 21, :alias-col nil, :alias-end-col nil, :row 1, :to "@material-ui/core"}], :var-definitions [], :var-usages []}}```

```bash
echo '(ns test (:require ["@material-ui/core" :default mui]))' | ./clj-kondo --lint - --config '{:output {:analysis true :format :edn}}' | ./jet -i
Exception in thread "main" clojure.lang.EdnReader$ReaderException: java.lang.RuntimeException: Invalid leading character: @
        at clojure.lang.EdnReader.read(EdnReader.java:180)
        at clojure.lang.EdnReader.read(EdnReader.java:111)
        at clojure.edn$read.invokeStatic(edn.clj:35)
        at jet.formats$parse_edn.invokeStatic(formats.clj:29)
        at jet.main$_main$fn__10629.invoke(main.clj:114)
        at jet.main$_main.invokeStatic(main.clj:121)
        at jet.main$_main.doInvoke(main.clj:97)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at jet.main.main(Unknown Source)
Caused by: java.lang.RuntimeException: Invalid leading character: @
        at clojure.lang.Util.runtimeException(Util.java:221)
        at clojure.lang.EdnReader.readToken(EdnReader.java:187)
        at clojure.lang.EdnReader.read(EdnReader.java:168)
        at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:766)
        at clojure.lang.EdnReader$MapReader.invoke(EdnReader.java:680)
        at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:757)
        at clojure.lang.EdnReader$VectorReader.invoke(EdnReader.java:672)
        at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:757)
        at clojure.lang.EdnReader$MapReader.invoke(EdnReader.java:680)
        at clojure.lang.EdnReader.read(EdnReader.java:145)
        ... 8 more
```

**expected behavior**

clj-kondo output can be parsed by jet -i edn

**Comment by borkdude** [comment]
Thanks. I think we should just export the namespace names as strings. We've had problems before with symbols not being readable. Maybe it's better if we switched _all_ symbols to strings really, but this could be breaking existing clients like clojure-lsp. What do you think @ericdallo ?

**Comment by ericdallo** [comment]
This will certainly break clojure-lsp, but I agree this looks a better approach for clj-kondo. I'd just need to know for sure which, if not all, fields will be changed to string (`:to`, `:ns`, `:name`, `:from` etc)

**Comment by borkdude** [comment]
It turns out the analysis data already has the ns as string in this case. The error comes from an `:ns` in `:findings`. I wonder since when we added an `:ns` there... perhaps this is used by clojure-lsp? 😂 This ns just has to be a string like in the analysis and this will fix the issue.

**Comment by borkdude** [comment]
<img width="748" alt="Screenshot 2021-07-20 at 11 25 00" src="https://user-images.githubusercontent.com/284934/126297202-90a89cc5-75e1-4173-b7ef-ab2a881eaef3.png">

**Comment by borkdude** [comment]
Should be fixed with https://github.com/clj-kondo/clj-kondo/commit/115873031ed4cfbdc6966633d66cc922e8cb9a35.

@xlfe You can find a new binary from the builds.

**Comment by ericdallo** [comment]
@borkdude nice!
clojure-lsp doesn't use the :ns from findings, but checking the analysis comming from kondo (and the docs) you can see it comes as symbol indeed and not string: https://github.com/clj-kondo/clj-kondo/tree/master/analysis#data am I right?

```clojure
{:fixed-arities #{2},
  :end-row 292,
  :name-end-col 25,
  :name-end-row 288,
  :name-row 288,
  :ns clojure-lsp.queries,
  :name find-unused-refers,
  :defined-by clojure.core/defn,
  :filename "/home/greg/dev/clojure-lsp/src/clojure_lsp/queries.clj",
  :col 1,
  :name-col 7,
  :end-col 13,
  :arglist-strs ["[findings filename]"],
  :bucket :var-definitions,
  :row 288}
```

**Comment by borkdude** [comment]
It's only a string when it needs to be a string.

**Comment by ericdallo** [comment]
Hum, this could be a issue on how clojure-lsp compare, do you know what cases would come as string? also is there valid for `:to` and `:from` as well or they are always symbols?

**Comment by borkdude** [comment]
> do you know what cases would come as string?

if they need to be, in the case of these npm namespaces like described above

**Comment by ericdallo** [comment]
I see, maybe in a future release it'd be better to always send as string to avoid different types on the same field

**Comment by borkdude** [comment]
I agree.

**Comment by borkdude** [comment]
In fact, not entirely sure. I think there might be some value to have the ns in the original form that it was used: as a string or symbol.

**Comment by ericdallo** [comment]
so maybe a new field? 🤷🏻

**Comment by borkdude** [comment]
@ericdallo What is the problem with the current solution? This symbol-or-string format was already uses for the analysis output for a long time now. Can you describe where clojure-lsp is running into trouble with this, if it is?

**Comment by ericdallo** [comment]
Sure, lastest release I improved performance with transducers and better equality comparassion, but as `:ns` could be a string, this for example will not work: https://github.com/clojure-lsp/clojure-lsp/blob/master/src/clojure_lsp/queries.clj#L190, clojure-lsp would need to check the type before and do the proper comparassion

**Comment by borkdude** [comment]
@ericdallo That's not introduced by the solution to this commit, it was already the case. Just try some code with a string namespace and with the currently released clj-kondo it should already blow up. If you are concerned about performance, use `(instance? clojure.lang.Symbol ..)`, instance checks are basically for free.

**Comment by ericdallo** [comment]
Yeah, I didn't know :ns already could be returned as string before 😅 
You mean first `(instance? clojure.lang.Symbol ..)` and then do the comparassion with `(.equals ^clojure.lang.Symbol ...)` right?

**Comment by borkdude** [comment]
Yeah.

**Comment by ericdallo** [comment]
Thanks, I'll do the proper changes on clojure-lsp side

**Comment by xlfe** [comment]
@borkdude thanks that's fixed it obviously. Also thanks for all your work on clj-kondo, jet and babashka. Super useful set of tools. :+1:
