### ISSUE TITLE
Error on use of :or combined with :as for which there are no other destructuring

### ISSUE THREAD

**Issue by didibus** [clj-kondo/clj-kondo#1325]
**Is your feature request related to a problem? Please describe.**

```
(defn baz
 [{:keys [a]}]
 (/ 10 a))

(defn foo
 [{:as bar :or {a 10}}]
 (baz bar))

(foo {})
;> Error trying to divide by zero
```

If a developer assumes that :or can be used to create default keys on the :as map in a destructuring, it can lead.to bugs, as that is an error, :or doesn't do that.

**Describe the solution you'd like**

Error when the destructuring doesn't bind every one of the :or keys to a symbol inside the destructing, because it makes no sense to do so, and probably means they assume it is setting a default key on the :as map, which it is not and can lead to bugs.

**Describe alternatives you've considered**

None

**Comment by borkdude** [comment]
@didibus clj-kondo already warns about bindings that aren't valid in `:or`:

<img width="778" alt="Screenshot 2021-07-23 at 22 26 49" src="https://user-images.githubusercontent.com/284934/126837960-8e2d6c05-b05e-4ee8-a4ff-e71c6e5c7f79.png">

**Comment by borkdude** [comment]
I expect the current warning to be sufficient. If not, feel free to re-open.
