### ISSUE TITLE
Consider supporting macro definitions directly in hooks

### ISSUE THREAD

**Issue by borkdude** [clj-kondo/clj-kondo#1327]
Merged to master. Example usage:

A script with a macro that causes unresolved symbols:

``` clojure
(ns script)
(def sh (js/require "shelljs"))

(defmacro $ [op & args]
  (list* (symbol (str "." op)) 'sh args))

(prn (str ($ which "git"))) ;; which is unresolved, etc.
(prn (str ($ pwd)))
($ cd  "..")
(-> ($ ls) prn)
($ cd "foobar")
(-> ($ ls) prn)
```

<img width="330" alt="Screenshot 2021-07-28 at 11 57 10" src="https://user-images.githubusercontent.com/284934/127303378-2fd6fc28-690d-4522-9ad1-5240ab156c8b.png">

Place the macro in a similar named namespace in your `.clj-kondo` directory:

.clj-kondo/script.clj
``` clojure
(ns script)

(defmacro $ [op & args]
  (list* (symbol (str "." op)) 'sh args))
```

Note: the namespace in `.clj-kondo` doesn't have to have the same name but in general this will work better for the macro expansion.

Configure the macro to be used for expansion:

.clj-kondo/config.edn:
``` clojure
{:hooks {:macroexpand {script/$ script/$}}}
```

Profit!

<img width="324" alt="Screenshot 2021-07-28 at 11 58 00" src="https://user-images.githubusercontent.com/284934/127303477-629b9e90-fc9a-467b-91c5-bd6cd963d55d.png">

**Comment by borkdude** [comment]
@jimka2001 Let me know if you want to test this so we can iterate on it.

**Comment by daveyarwood** [comment]
This seems like it could be a game changer!

One thing that sticks out to me in the screenshot is that the macro definition is duplicated in the hooks namespace. I wonder if there are any tricks you have up your sleeve that could let us avoid that? Otherwise, we would have to keep the two macro definition copies in sync with one another.

**Comment by borkdude** [comment]
@daveyarwood I agree that would be convenient. There are a few challenges:

- Not all macros are "pure" Clojure, so automatically running _all_ macros is out of the question. Perhaps an annotation like `#_:clj-kondo/run-macro` to mark a macro as safe could help. I think a mechanism to execute a "stub" macro will still be necessary for macros that are not pure or rely on library-specific code.
- Macros are often context-sensitive, e.g. they use namespace aliases to generate code.  But perhaps clj-kondo could rewrite this macro before SCI gets to execute it, so these aliases are already resolved.

The above issues are probably a major rabbit hole, so perhaps it would be good to first get the "stub" macro support out the door, before entering the rabbit hole any further. I'm looking for people to test this out and iterate with me on this. If you are volunteering, let me know and I can give you some instructions on how to get going with this.

**Comment by jimka2001** [comment]
I agree that the duplication is bad.  However, I also agree if this idea works, it will be a big step forward. Thereafter the system can be improved.   For example, it may be possible (in the future) to promise the system that the macro is *pure*, in order to avoid the copy.   or there may simply be some additional macrology which uses clojure itself to have two locations define the same macro in two places, using only one golden source.

I don't see this as a stopping problem.

**Comment by jimka2001** [comment]
> @jimka2001 Let me know if you want to test this so we can iterate on it.

I'd love to try it.  But I'm currently pretty much an imbecile with the installation process.  I'll need some help getting started.

**Comment by borkdude** [comment]
@jimka2001 Let's discuss installation, etc. in https://github.com/clj-kondo/clj-kondo/discussions/1329#discussioncomment-1046992 where we can elaborate further. I will capture important details from that discussion in this issue, so we can use this issue as a summary and the discussion can go into more details without obscuring the essentials.

**Comment by glyh** [comment]
Will this slow down clj-kondo? If it will, maybe we can add some databases to store informations about it.

**Comment by borkdude** [comment]
@glyh This feature won't slow down clj-kondo if you don't use it. The slowdown depends on the performance of the macro.

**Comment by AjBreidenbach** [comment]
This worked or me https://github.com/clj-kondo/clj-kondo/issues/904#issuecomment-664638850
