### ISSUE TITLE
Implement analysis for Java classes

### ISSUE THREAD

**Issue by borkdude** [clj-kondo/clj-kondo#1330]
We need filenames, rows/cols, etc for classes + methods.

Perhaps using the javadoc stuff we already used for the built-in Java classes, perhaps using https://javaparser.org/ or some other tool that is GraalVM compatible.

This benefits the arity linting we already support for static method calls, later we can also try to support instance methods.
It will also benefit navigation in clojure-lsp.

If people are using https://github.com/clojure-emacs/enrich-classpath then this will provide Java sources on the classpath.

/cc @ericdallo

**Comment by ericdallo** [comment]
clojure-lsp could benefit of that allowing users to go to definition of methods/classes and find references of those as well

**Comment by borkdude** [comment]
After some discussion [here](https://clojureverse.org/t/analyzing-java-sources-class-files-using-javaparser-or-javap/8131) it seems that using ASM on .class files can help us quite a bit.

@ericdallo threw together an ASM demo here: https://github.com/ericdallo/asm-sample
Run with `gradle run`.

It seems doable to do this in pure Clojure:
https://github.com/univalence/clojure-starter/blob/cbed9eed5ce255f0a88458370455b68ed125f291/src/supaopt/visitor.clj#L31

**Comment by ericdallo** [comment]
Created https://github.com/clojure-lsp/clojure-lsp/issues/762 to track the work on downstream

**Comment by borkdude** [comment]
I think a very cheap solution for clj-kondo could already be:
when it sees foo/bar/Baz.java or foo/bar/Baz.class in foo.jar
and it also sees (foo.bar.Baz. ...) in clojure, we can add something to the analysis which points to foo.jar!/foo/bar/Baz.java

**Comment by borkdude** [comment]
I'll close this issue and continue in https://github.com/clj-kondo/clj-kondo/issues/1623 for an initial approach.
