### ISSUE TITLE
Unused alias

### ISSUE THREAD

**Issue by borkdude** [clj-kondo/clj-kondo#1332]
E.g. `(:require [foo :as f])` and report that `f` was never used.

**Comment by seancorfield** [comment]
This would definitely be useful for us at work for `:as-alias`.

**Comment by borkdude** [comment]
Should this linter distinguish between `:as` and `:as-alias`?

**Comment by seancorfield** [comment]
If you have `(:require [foo.bar :as b])` and don't use `b/` anywhere, this is already flagged as unused -- but if you have `:as-alias` then it isn't flagged:
![image](https://github.com/clj-kondo/clj-kondo/assets/43875/c6438023-489a-48fc-a034-f22597d7b8d9)

That's the whole file so neither `b/` nor `q/` are used -- but only `foo.bar` **is** flagged as `unused-namespace`.

**Comment by bgrabow** [comment]
There is a situation where a required ns is used but its alias is not:
<img width="344" alt="Screenshot 2023-08-31 at 1 27 24 PM" src="https://github.com/clj-kondo/clj-kondo/assets/5761437/59eef0ff-b712-40e7-9870-ae4c346961d9">

I don't personally have a reason to want separate configuration for unused require aliases vs unused as-alias aliases, but I can't prove others wouldn't want that separate configurability.

**Comment by bgrabow** [comment]
n.b. I overlook unused `:as-alias` far more often than I overlook unused require aliases, so linting for unused `:as-alias` is more important to me.

**Comment by borkdude** [comment]
ok, I'll just consider an alias unused regardless of `:as` or `:as-alias` then

**Comment by seancorfield** [comment]
Sounds good. I don't mind getting an _extra_ warning on `[not.used :as x]` if it means I actually do get a warning on `[also.not.used :as-alias y]` 😄
