### ISSUE TITLE
warning: Redundant expression: :post

### ISSUE THREAD

**Issue by jimka2001** [clj-kondo/clj-kondo#1335]
**version**

8b5cf40d1cf92409687f2697b29220435f8cc137

**macro usage**

Using the new :macroexpand experimental feature.

**platform**

Mac OS

**editor**

Using emacs, but the problem is reproducible from the command line.

**problem**

I get the following output from `clojure -M:clj-kondo --lint src/clojure_rte/test.clj`
bash-3.2$ clojure -M:clj-kondo --lint src/clojure_rte/test.clj 
src/clojure_rte/test.clj:35:1: error: Unresolved symbol: %
src/clojure_rte/test.clj:48:6: warning: Redundant expression: :post
linting took 176ms, errors: 1, warnings: 1

In the test case there is a macro usage following by nomal code, which happens to be the equivalent of the macro-expanded code.   The problem here `48:6: warning: Redundant expression: :post` concerns line 48, which is the normal code.

**repro**

The following URL can be used to obtain the test case.

https://gitlab.lrde.epita.fr/jnewton/clojure-rte/-/blob/clj-kondo-issue-1334/src/clojure_rte/test.clj#L48

**config**

I don't believe it is configuration related.

**expected behavior**

The expected behavior is that I shouldn't see the warning about the `:post` condition in this case.

**Comment by borkdude** [comment]
Fixed on master. Also merged the macroexpand feature to there.
