### ISSUE TITLE
~ passed to macro as unquote rather than clojure.core/unquote

### ISSUE THREAD

**Issue by jimka2001** [clj-kondo/clj-kondo#1336]
**version**

8b5cf40d1cf92409687f2697b29220435f8cc137
**macro usage**

experimenting with new :macroexpand feature

**platform**

MacOs

**editor**

emacs
**problem**

I have a macro named `template`.  I don't think that its implementation is important for the purpose of this issue.
The macro is called in my application as `(template (not ~td))`.  When I put a `prn` inside the definition I discover that the macro is called (in normal clojure and in cider) with arguments `(not (clojure.core/unquote td))`.  However, putting the same print statement inside the macro in my `.clj-kondo` directory, I see that the macro argument is missing the `clojure.core` prefix and is simply `(not (unquote td))`.   As one can imagine the `template` macro treats these two inputs differently, returning `(list (quote not) td)` in the good case and `(list (quote not) (list (quote unquote) (quote td)))` in the bad case.

**repro**

I will attach a test case.

**config**

**expected behavior**

I expect that the macro is called with `unquote` having the `clojure.core/` prefix.

**Comment by jimka2001** [comment]
Here is a link to the test case [line 8](https://gitlab.lrde.epita.fr/jnewton/clojure-rte/-/blob/1207d6d8eca201340dc25d57b8f0c3f10f955880/src/clojure_rte/test.clj#L8)

**Comment by borkdude** [comment]
Fixed on master.

**Comment by jimka2001** [comment]
Just to make sure,   are you fully qualifying both `unquote` and also `unquote-splicing` ?

**Comment by borkdude** [comment]
Yep.
