### ISSUE TITLE
Linux static build started failing

### ISSUE THREAD

**Issue by borkdude** [clj-kondo/clj-kondo#1365]
Any ideas of why this might be happening? 

> /usr/bin/ld: cannot find -lstdc++

@lispyclouds @thiagokokada @ericdallo

**Comment by borkdude** [comment]
Also see https://github.com/babashka/babashka/pull/972#issuecomment-903216361

**Comment by lispyclouds** [comment]
I'm having a look

**Comment by ericdallo** [comment]
if the issue is with musl version we should probably pin versions on the CI as well, right?

**Comment by thiagokokada** [comment]
Fix for Babashka: https://github.com/babashka/babashka/pull/974

Probably something similar can be applied here.
