### ISSUE TITLE
Incorrect unresolved-var warning with namespaces manually added to codebase

### ISSUE THREAD

**Issue by kelvinqian00** [clj-kondo/clj-kondo#1377]
clj-kondo version: 2021.08.07-SNAPSHOT
Used with Calva on VSCode

Setup: Currently working on a cljc project that uses the Pedestal library as a dependency. Because Pedestal is Clojure-only, we provide support for ClojureScript by manually rewriting the Pedestal code in ClojureScript and adding them to the project as `.cljs` files:
```
src/main/
+-- [main source files]
+-- io/pedestal/
    +-- http/
    +-- interceptor/
    +-- http.cljs
    +-- interceptor.cljs  
``` 

After updating clj-kondo, it incorrectly highlights within any `.cljc` files any usage of Pedestal functions as unresolved variables. Note that this apparently only occurs for clj, and not cljs:
```clojure
(require '[io.pedestal.interceptor :as i])

#?(:clj i/interceptor   ; highlighted with a clj-kondo warning
   :cljs i/interceptor) ; no warning
```

This sort of excessive highlighting did not occur in previous versions of clj-kondo.

**Comment by borkdude** [comment]
@kelvinqian00 Can you please provide a reproducible example? Else it's very hard for me to diagnose this.

**Comment by borkdude** [comment]
I can't reproduce this with the Clojure JVM version of Pedestal only:

```  clojure
(ns test-program
  (:require [io.pedestal.interceptor :as i]))

i/interceptor ;; resolved, navigation works
i/foobar ;; unresolved var like expected
```

deps.edn:
``` 
{:deps {io.pedestal/pedestal.interceptor {:mvn/version "0.5.9"}}}
```

**Comment by kelvinqian00** [comment]
This would only occur in a `.cljc` file, i.e. where you need to support both Clojure and ClojureScript. The good news is that we just OSS'd the project where this issue was occurring, so it's just a matter of cloning the repo and watching the warnings appear in any source files that uses Pedestal functions: https://github.com/yetanalytics/lrs

Note how we copy-pasted code from Pedestal in order to support cljs, and also note that all of our original source files are `.cljc` (as opposed to `.clj` or `.cljs`): https://github.com/yetanalytics/lrs/tree/master/src/main

**Comment by borkdude** [comment]
Can you please give me a `.cljc` file repro or point me to a file within the repo where I should look at.

**Comment by borkdude** [comment]
If you can make this as obvious as possible for me that would be helpful: just point out one example of an error so I can reproduce, be very specific. I deal with lots of issues on a daily basis so the least amount of time I have to spend on actually seeing a reproducible example, that would be helpful.

**Comment by borkdude** [comment]
I found one in lrs/pedestal/interceptor.cljc. The funny thing is that lsp navigation does work, but clj-kondo "complains", it seems about only the clojure definition.

<img width="629" alt="Screen Shot 2021-09-15 at 16 59 48" src="https://user-images.githubusercontent.com/284934/133458403-5a3b7b33-b9ba-4bc8-b812-06d8c1d78fd2.png">

**Comment by borkdude** [comment]
@kelvinqian00 The issue is solved when you scan the classpath with clj-kondo:

```
mkdir -p .clj-kondo
echo '{}' > .clj-kondo/config.edn
clj-kondo --lint $(clojure -Spath) --dependencies --parallel
```

After that, the cache is populated with analysis from the pedestal library and then clj-kondo can resolve the vars.

**Comment by borkdude** [comment]
Also see https://github.com/clj-kondo/clj-kondo#project-setup

**Comment by kelvinqian00** [comment]
Ok, apologies for wasting your time with the lack of specific examples. Now that you pointed this out, the warnings probably occurred because updating VSCode cleared my `.clj-kondo/.cache/` directory. (I thought that it was a bug in clj-kondo itself introduced [because I saw changes to how namespace imports were handled](https://github.com/clj-kondo/clj-kondo/commit/13066e47b8418072edc15a853164a2ef73ddc75a).) I'll perform the `clj-kondo` command myself to double check that this is indeed the case.

**Comment by borkdude** [comment]
@kelvinqian00 Are you using clojure-lsp within VSCode?

**Comment by kelvinqian00** [comment]
Yes.

**Comment by borkdude** [comment]
In that case it should all automatically. Let me try VSCode myself.

**Comment by kelvinqian00** [comment]
Ok, I ran the `clj-kondo` command and the warnings still appear.

**Comment by borkdude** [comment]
In VSCode it works correctly:

<img width="258" alt="Screen Shot 2021-09-15 at 17 31 37" src="https://user-images.githubusercontent.com/284934/133463624-6106f5bb-505f-4a17-8b7e-7dc70ebca26e.png">

On the command line you should initialize clj-kondo like I suggested here:

https://github.com/clj-kondo/clj-kondo/issues/1377#issuecomment-920105091

Have you done that? After doing so, I didn't see the warning anymore.

**Comment by kelvinqian00** [comment]
Yes, I did that.

Turns out that the clj-kondo initialization procedure created a _second_ folder in the `.cache` directory (`.cache/2021.09.15`). The warnings only went away when I deleted the original folder (`.cache/2021.08.07-SNAPSHOT`).

Furthermore, if I quit and restart VSCode, then the original `SNAPSHOT` folder re-appears upon restart and the excess warnings appear once again. Do the warnings re-appear for you when you quit and restart VSCode?

**Comment by borkdude** [comment]
> created a second folder in the .cache directory

Every version of clj-kondo creates its own cache directory, this is why you are seeing two of them. They should not interfere with each other so there should be no need to delete such a folder.

Please be specific: where you see warning: on the command line or in your editor? Do not mix these two situations.

**Comment by kelvinqian00** [comment]
All the warnings I see are in the VSCode editor.

If you need specific locations, the `com/yetanalytics/lrs/pedestal/interceptor.cljc` file, as you may have seen, has a lot of errors. The first warning occurs at line 25 for `i/interceptor`.

**Comment by borkdude** [comment]
Also, make sure you have a `.clj-kondo` directory (only delete the `.cache` directory within it) before doing all of this. Else clj-kondo cannot store the cache anywhere.

**Comment by kelvinqian00** [comment]
So I also ran the linter from the command line (something that I've previously never done), and I don't get excess warnings:
```
% clj-kondo --lint src/main/com/yetanalytics/
src/main/com/yetanalytics/node_chain_provider.cljs:16:14: warning: namespace cljs.nodejs is required but never used
src/main/com/yetanalytics/node_chain_provider.cljs:20:14: warning: namespace io.pedestal.http is required but never used
src/main/com/yetanalytics/node_chain_provider.cljs:23:14: warning: namespace http is required but never used
src/main/com/yetanalytics/node_chain_provider.cljs:28:3: warning: Unresolved namespace cljs.core.async.impl.channels. Are you missing a require?
src/main/com/yetanalytics/node_chain_provider.cljs:72:12: warning: unused binding servlet-response
src/main/com/yetanalytics/node_chain_provider.cljs:112:6: warning: unused binding body
src/main/com/yetanalytics/node_chain_provider.cljs:161:9: warning: unused binding body-processor
src/main/com/yetanalytics/node_chain_provider.cljs:191:27: warning: unused binding join?
```
All of these errors are from `node_chain_provider.cljs` and are "supposed" to happen.

**Comment by borkdude** [comment]
Let's focus on the unresolved var for now. As you can see the unresolved var errors aren't there. If the other warnings should be there depends on your code, but they seem normal.

**Comment by kelvinqian00** [comment]
Indeed, by "'supposed' to happen" I mean these are actual warnings that are dependent on my code.

Anyways, I was _finally_ able to remove the unresolved var warnings by deleting `.lsp/.cache/sqlite.db`. (Which shouldn't be surprising given my previous comment showing that this problem didn't affect clj-kondo on the CLI.)

**Comment by borkdude** [comment]
I think this should not happen again with the newest version of clojure-lsp. If it does, please make an issue at clojure-lsp or here if you are able to reproduce the error on the command line.
