### ISSUE TITLE
install-clj-kondo: Cannot upgrade to latest version

### ISSUE THREAD

**Issue by manuel-uberti** [clj-kondo/clj-kondo#1391]
Hi,

I am trying to install `v2021.09.25` using `sudo ./install-clj-kondo` as I usually do to upgrade `clj-kondo`. I am using Ubuntu 20.04 LTS, if this can be of any help.

This is the output I get:

```
Downloading https://github.com/borkdude/clj-kondo/releases/download/v2021.09.26-SNAPSHOT/clj-kondo-2021.09.26-SNAPSHOT-linux-amd64.zip to /tmp
[clj-kondo-2021.09.26-SNAPSHOT-linux-amd64.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of clj-kondo-2021.09.26-SNAPSHOT-linux-amd64.zip or
        clj-kondo-2021.09.26-SNAPSHOT-linux-amd64.zip.zip, and cannot find clj-kondo-2021.09.26-SNAPSHOT-linux-amd64.zip.ZIP, period.
```

Sorry for not filling in the bug report properly but this is more of an installation problem. If you think I am missing any details, please feel free to ask.

**Comment by borkdude** [comment]
Thank you. Something went wrong with the file that contains the released version. Should be fixed now.

**Comment by manuel-uberti** [comment]
Thank you for fixing it so quickly!
