### ISSUE TITLE
Conditional Reader macro on var definitions error

### ISSUE THREAD

**Issue by leoiacovini** [clj-kondo/clj-kondo#1414]
**version**
2021.09.25

**platform**

Using from `clojure-lsp`

**editor**

Using from `clojure-lsp` + `calva`

**problem**

`clj-kondo` seems to not parse properly metadata on vars definition that contains the Conditional Reader macro. Depending on the syntax it can go from making the namespace unparsable and the var not identified, to just not being made available for `clj-kondo` analysis afterward.

**repro**

1. First case we get the following error: `missing value for key #?@ (:clj [:deprecated "deprecation message"])`
```clj
(def ^{#?@(:clj [:deprecated "deprecation message"])}
  my-deprecated-var
  :bla)
```

2. Second error the var is parsed, but it is not marked as deprecated in the following usages:
```clj
(def ^#?(:clj {:deprecated "deprecation message"})
  my-deprecated-var
  :bla)
```

**expected behavior**

I would expect the code to be parsed correctly and the var would be displayed as deprecated when used inside the `clj` environment, but not on the `cljs`

**Comment by borkdude** [comment]
@leoiacovini Fixed on master. Note that your second case doesn't work in CLJS: it also needs a `:cljs` or `:default` with an empty map there.

**Comment by borkdude** [comment]
<img width="739" alt="Screen Shot 2021-10-13 at 11 22 48" src="https://user-images.githubusercontent.com/284934/137105637-91e620f8-27ae-4d73-b3f2-a79034429034.png">
