### ISSUE TITLE
Inline support for ignoring specific unresolved symbols

### ISSUE THREAD

**Issue by metasoarous** [clj-kondo/clj-kondo#1443]
**Is your feature request related to a problem? Please describe.**

It's currently possible to ignore a specific warning, such as `:unresolved-symbol` for a particular form using `#_{:clj-kondo/ignore [:unresolved-symbol]}`, but I would like to ignore a _specific_ symbol being bound by a particular macro (that doesn't match the typical `def` or `defn` patterns, so `lint-as` doesn't work).

**Describe the solution you'd like**

It would be great if you could just specify a map of symbols to ignore, something like `#_{:clj-kondo/ignore {:unresolved-symbol #{'the-symbol}}}`.

**Describe alternatives you've considered**

If you wanted to keep it so that `:clj-kondo/ignore` always maps to a vector, you potentially support having map entries in the vector for qualifiers, something like `#_{:clj-kondo/ignore [{:unresolved-symbol #{'the-symbol}}]}`.

Thanks!

**Comment by borkdude** [comment]
@metasoarous There's usually a better solution for this.

1) Write a hook using `:analyze-call` or `:macroexpand`. The latter allows you to just copy paste the macro inside the clj-kondo folder, if it uses pure Clojure.
See https://github.com/clj-kondo/clj-kondo/blob/master/doc/hooks.md#macroexpand

2) Configure the specific symbols like `{:linters {:unresolved-symbol {:exclude [(your.macro [specific-symbol1 specific-symbol2])]}}}`

Can you check if these two solutions work for your macro? I'm curious about the macro, perhaps you can paste it or a similar version here.

**Comment by metasoarous** [comment]
Thanks as always for the rapid response!

For now I think the second approach will work for now (didn't realize you could specify the specific symbols there), but I'm intrigued by `:analyze-call` and `:macroexpand`. That may be a nicer approach long term.

I'm helping with some updates to Clojuratica, and there are some pretty gnarly macros; A couple of examples [here](https://github.com/scicloj/Clojuratica/blob/716738b47e02a86d306c7c5f90310a96a82265e2/src/clojuratica.clj#L64-L77).

Forgive me for my ignorance, but is there a way (other than telling people just to copy the contents of `.clj-kondo`) for a lib to express a set of kindo rules that will get picked up by projects that depend on it?

Thanks again!

**Comment by borkdude** [comment]
> Forgive me for my ignorance, but is there a way (other than telling people just to copy the contents of .clj-kondo) for a lib to express a set of kindo rules that will get picked up by projects that depend on it?

Yes!

See https://github.com/clj-kondo/clj-kondo/blob/master/doc/config.md#exporting-and-importing-configuration

There's a list of examples here:

https://github.com/clj-kondo/clj-kondo/issues/1383

**Comment by metasoarous** [comment]
Amazing :-) Thanks so much!
