### ISSUE TITLE
Relative installation path does not work

### ISSUE THREAD

**Issue by carlzhc** [clj-kondo/clj-kondo#1444]
User may provide relative path as installation directory or download directory.
The script should get the absolute paths before using them, or not change current working directory.

https://github.com/clj-kondo/clj-kondo/blob/7e33b5a59457a0f3593bca28934cf4bbf2f09e89/script/install-clj-kondo#L69
https://github.com/clj-kondo/clj-kondo/blob/7e33b5a59457a0f3593bca28934cf4bbf2f09e89/script/install-clj-kondo#L80

**Comment by borkdude** [comment]
Fixed, thanks.
