### ISSUE TITLE
Lint for redundant doto

### ISSUE THREAD

**Issue by zackteo** [clj-kondo/clj-kondo#1453]
**Is your feature request related to a problem? Please describe.**
```clj
(doto client
  (.start))
```
**Describe the solution you'd like**
Was thinking if it would be worthwhile to add a lint on `doto` here as "redundant doto" since there is only 1 argument.

**Describe alternatives you've considered**
I realise that similar linting could be applied to `->` and `->>`

like in 
```clj
(-> [1 2 3 4 5])

(->> [1 2 3 4 5])
```

**Additional context**
Not sure if this might be a wanted lint, or if there is some strict mode in clj-kondo that already does this

[ Optional: if you are interested in doing a PR yourself, please leave a note. ]
If this might be a desirable feature and given that this should be quite a simple(?) PR, I would be interested in doing the PR myself

**Comment by borkdude** [comment]
I don't think this example is always redundant. E.g. I have one example here:

https://github.com/borkdude/blog/blob/b17e2dc3977da5e2da542e5e5ce68365600a02f3/highlighter.clj#L19

which has only one expression, but is still useful, given that the entire `doto` returns the value which is "done to".

**Comment by zackteo** [comment]
Right! That makes sense :)

How about the case of `->` or `->>` with only 1 argument? But not sure if it is worth linting since people might do so, while REPL driven development.

Otherwise, should I close the issue?

**Comment by borkdude** [comment]
Closing seems good, new topics require new issues. We can open new ones for `->` and `->>`.
