### ISSUE TITLE
"Unresolved symbol" not detecting the let, if-let, and when-let bindings in better-cond

### ISSUE THREAD

**Issue by sstarkey-cataboom** [clj-kondo/clj-kondo#1457]
clj-kondo does not seem to detect the binding in [better-cond](https://github.com/Engelberg/better-cond) for let, if-let, and when-let.

```
(bc/let [abc nil] :foo)
(bc/if-let [defg nil] :foo)
(bc/when-let [hijk nil] :foo)
```

All of these give "Unresolved symbol" errors, like:  `Unresolved symbol: abc (clj-kondo-clj)`

**Comment by borkdude** [comment]
Please fill out the issue template before posting an issue.

**Comment by borkdude** [comment]
That will guide you to this section: https://github.com/clj-kondo/clj-kondo/blob/master/doc/config.md#unrecognized-macros

**Comment by borkdude** [comment]
@sstarkey-cataboom See https://github.com/clj-kondo/clj-kondo/issues/1383 for a list of libraries that export their configurations. Perhaps we can convince the author of better-cond to add such a config to their library so everyone who uses this lib will get the right config.

**Comment by borkdude** [comment]
@genovese Do you also want to support the above mentioned vars in the better-cond config here?

https://github.com/clj-kondo/config/blob/master/resources/clj-kondo.exports/clj-kondo/better-cond/clj_kondo/better_cond.clj

**Comment by borkdude** [comment]
@genovese It's already been taken care of :).

**Comment by genovese** [comment]
Ah, thanks.  👍  Sorry about that :)
