### ISSUE TITLE
auto-load configs

### ISSUE THREAD

**Issue by borkdude** [clj-kondo/clj-kondo#1483]
Use a thumbs up to upvote this issue.

I'm considering to automatically opt in to configs that are found in:

```
.clj-kondo/<org>/</lib>/config.edn
```

From a usability standpoint this would be much better.
But there might be some dangers to this. E.g. a library could accidentally export a config which will make clj-kondo crash or get stuck in a loop while expanding a macro or so. Any thoughts?

Proposal: make option `:auto-configure true` which defaults to true. When triaging issues people can disable the option by setting it to false.

**Comment by ericdallo** [comment]
Just upvoting this and saying that would help clojure-lsp be a more IDEish tool making most clj-kondo configs working out of the box

**Comment by borkdude** [comment]
OK, will try to get this for the next release then. Defaulting the option to true would be the most usable. People can disable it in case of problems.

**Comment by borkdude** [comment]
@ericdallo If you want, you can test with the branch https://github.com/clj-kondo/clj-kondo/tree/auto-config-paths

**Comment by ericdallo** [comment]
I'll give  try later today, thanks!

**Comment by ericdallo** [comment]
It worked perfectly @borkdude I removed clojure-lsp `:config-paths`, and it keeps working as expected :)

**Comment by borkdude** [comment]
Going to fix some tests and then will merge to master...

**Comment by borkdude** [comment]
Merged!
