### ISSUE TITLE
[analysis] Information about defrecord methods

### ISSUE THREAD

**Issue by ericdallo** [clj-kondo/clj-kondo#1484]
**Is your feature request related to a problem? Please describe.**
Consider the code:
```clojure
(defprotocol MyFoo
  (something [this]))

(defrecord MyBar []
  MyFoo
  (something [_]
    123))

(something (MyBar.))
```

For a `lsp-find-implementation` feature from clojure-lsp work, it'd be needed to add analysis for the `defrecord` methods, in this case `something` of line 5. Otherwise we can't relate the `something` from a var-usage or from a var-definition of a `defprotocol`.

**Describe the solution you'd like**
Maybe a new `var-definition` with some info describing it's a implementation? this way both `lsp-find-definition` and `lsp-find-implementation` could be implemented correctly.

**Describe alternatives you've considered**

**Additional context**
Related to https://github.com/clojure-lsp/clojure-lsp/issues/656

**Comment by borkdude** [comment]
It's not going to be a var-definition since line 5 doesn't define a new var, it "mutates" the protocol var with a new implementation. We don't really have something for this in the analysis yet. I'll have to think about this a little bit in the coming time.

**Comment by borkdude** [comment]
Perhaps something like:
`:protocol-impls {:protocol-name MyFoo :method-name <ns> :protocol-ns .... :row :loc`

**Comment by ericdallo** [comment]
I see, yeah, maybe treat as a separate thing sounds better

**Comment by borkdude** [comment]
@ericdallo OK, I'm open to an experimental PR to add this and we can bikeshed over the exact naming, etc. after that.

**Comment by ericdallo** [comment]
@borkdude I'm working on this, what do you think about this:
```clojure
(deftest protocol-impls-test
  (testing "simple defrecord"
    (let [{:keys [:protocol-impls]} (analyze "
(defprotocol MyFoo
  (something [this])
  (^Bla other-thing [this a b]))

(defrecord MyBar []
  MyFoo
  (something [_]
    123)

  (^Bla other-thing [_ a b]
    456
    789))" {:config {:output {:analysis {:protocol-impls true}}}})]
      (assert-submaps
       '[{:protocol-name MyFoo
          :impl-name MyBar
          :method-name something
          :protocol-ns user
          :filename "<stdin>"
          :name-row 8 :name-col 4 :name-end-row 8 :name-end-col 13
          :row 8 :col 3 :end-row 9 :end-col 9}
         {:protocol-name MyFoo
          :impl-name MyBar
          :method-name other-thing
          :protocol-ns user
          :filename "<stdin>"
          :name-row 11 :name-col 9 :name-end-row 11 :name-end-col 20
          :row 11 :col 3 :end-row 13 :end-col 9}]
       protocol-impls))))
```

I intend to add the same to deftype and definterface so maybe we need a new field `defined-by`?

**Comment by borkdude** [comment]
@ericdallo What are you using `:impl-name MyBar` for? It's a bit confusing to me.

**Comment by ericdallo** [comment]
@borkdude since this is a protocol implementation, I thought Impl-name would be the defrecord/deftype name, any suggestion?

**Comment by borkdude** [comment]
impl-name contains only the name of a defrecord, but not its namespace for example.
so I wonder if it's really useful to add. I prefer to start with the least amount of fields possible to get something useful and then add stuff if necessary.

**Comment by ericdallo** [comment]
Sounds good to me, I'll finish the impl for deftype and defintetface and give a try with clojure-lsp and let you know if missing anything

**Comment by ericdallo** [comment]
@borkdude I created https://github.com/clj-kondo/clj-kondo/issues/1484, I ended up adding `protocol-ns` and `protocol-name` in clojure-lsp, LMK what you think (in the future we could add `impl-name` if needed as well)
