### ISSUE TITLE
clojure-lsp would like to have the string from testing in the analysis

### ISSUE THREAD

**Issue by borkdude** [clj-kondo/clj-kondo#1492]
See https://github.com/clojure-lsp/clojure-lsp/issues/653

**Comment by ericdallo** [comment]
As mentioned [here](https://github.com/clj-kondo/clj-kondo/pull/1487#issuecomment-989425964) I was wondering what we would need to change on clj-kondo to achieve that, I think only adding context for those var-usages would solve that? maybe with a different context matching the frameworks namespaces?

**Comment by ericdallo** [comment]
WDYT @borkdude ?

**Comment by borkdude** [comment]
@ericdallo yes, you need to write a hook for `fact`, then add `:context {:marick/midje {:fact-str ..}}` to the name node of that expression and then return the expression as `{:node new-node}`. Then clj-kondo will lint this expression again and will register the context on the var usage in the analysis.

**Comment by borkdude** [comment]
I don't want to have `midje` stuff in clj-kondo but prefer that people write hooks for those that can be added to the library.

**Comment by ericdallo** [comment]
I see, is it possible to clojure-lsp lint passing a custom hook?
For an IDE experience, having native support on clojure-lsp for test tree on midje make sense I think

**Comment by borkdude** [comment]
The support will be there if you include those hooks, or do you mean "built-in"? I'm afraid that when I start adding one thing from midje, I have to support the entire library, which seems to have gone a bit out of fashion.

**Comment by ericdallo** [comment]
No problem on not adding that to kondo, but I'd like to support that on clojure-lsp by default, like not needing to user manually create a hook for that, just like clojure-lsp can pass custom lint fn, is it possible to pass custom hooks on the clj-kondo call?

**Comment by borkdude** [comment]
@ericdallo if the hook is added to midje itself (like other configurations) then the user would get this? that is the mechanism to add hooks to clj-kondo. the custom hook fn is just a function over the analysis at the end.

**Comment by borkdude** [comment]
if you want lsp to have this as a built-in then you need to add these hooks to files in the configuration, which you could perhaps do in a temporary directory

**Comment by ericdallo** [comment]
hum, yeah, it makes sense, user would need to still manually add `:config-paths ["marick/midje"]` to clj-kondo config but looks good enough to me

**Comment by borkdude** [comment]
There is an issue for automatically including the configs. I was thinking we could do: `:auto-configure true` and then all directories with a `config.edn` is added automatically.

**Comment by ericdallo** [comment]
that would be so great!

**Comment by borkdude** [comment]
ok, please upvote: https://github.com/clj-kondo/clj-kondo/issues/1483

**Comment by borkdude** [comment]
I'm closing this. Let me know if you need help with the hook, but the built-in hook should work exactly similar.
