### ISSUE TITLE
Include analysis of var-usages used inside potemkin import-vars

### ISSUE THREAD

**Issue by ericdallo** [clj-kondo/clj-kondo#1498]
To upvote this issue, give it a thumbs up. See [this list](https://github.com/clj-kondo/clj-kondo/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) for the most upvoted issues.

**Is your feature request related to a problem? Please describe.**
It seems clj-kondo doesn't include the `var-usages` analysis of usages inside `potemkin/import-vars`, not making available those analysis cause clojure-lsp consider the definition of those usages as unused-public-var.
Example:

```clojure
(ns my-api
  (:require [my-ns]))

(import-vars
  my-ns/foo)
```

```clojure
(ns my-ns)

(defn foo []) ;; clojure-lsp/unused-public-var
```

**Describe the solution you'd like**
If clj-kondo include analysis of those var-usages of the `my-api`,  that would solve the unused-public-var custom linter on clojure-lsp side.

**Describe alternatives you've considered**

**Additional context**

I'm interested in helping to fix but I don't know what's the correct fix or where to start

**Comment by borkdude** [comment]
The code for potemkin is here: https://github.com/clj-kondo/clj-kondo/blob/master/src/clj_kondo/impl/analyzer/potemkin.clj
All we need to do is put the node of the var name through `analyze-usages2` and that's probably it.

**Comment by ericdallo** [comment]
Thanks, I'll give it a try

**Comment by ericdallo** [comment]
Done on https://github.com/clj-kondo/clj-kondo/pull/1499
