### ISSUE TITLE
Obstrusive printlning, especially for JVM users

### ISSUE THREAD

**Issue by vemv** [clj-kondo/clj-kondo#1514]
**version**

`[clj-kondo "2021.12.19"]`

**platform**

JVM

**problem**

I see `[clj-kondo] Already seen the file ...` when I'm linting via a `clojure` invocation (which is the pattern I use in CI, or locally in certain projects) **or** (independently) when I spin up a repl (which is the pattern I use for personal productivity, via [formatting-stack](https://github.com/nedap/formatting-stack)).

For the CLI case it represents an abundance of info which wasn't present before. As someone who routinely uses this `clojure ...` pattern, I expect the info to be "to the point", since I will actively use it.

For the REPL case it's even more bothering, since one will be greeted with a wall of `println`s every time one starts a repl.

Thanks - V

**Comment by vemv** [comment]
(If it helps at all, I would be OK with having to set a piece of config or System property to opt out)

**Comment by borkdude** [comment]
I agree. We can make a `--debug` flag (and `:debug true` in the JVM API) that will show these warnings and turn them off otherwise. There are a couple more of these.

**Comment by borkdude** [comment]
@vemv You can try `clj-kondo/clj-kondo` version `2021.12.20-20220103.220032-8`. Please let me know if this works for you.

**Comment by vemv** [comment]
It sure does! Thank you.
