### ISSUE TITLE
Relax reduce-without-init for functions known to be safe

### ISSUE THREAD

**Issue by borkdude** [clj-kondo/clj-kondo#1519]
See discussion [here](https://github.com/clj-kondo/clj-kondo/discussions/1517).

See current [docs](https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#reduce-without-initial-value)

Known to be safe functions: `clojure.core/+`, `core/*`, ...

We should also support an `:exclude` config.

/cc @vemv

**Comment by borkdude** [comment]
I added the above. If you know more core functions known to be safe with `reduce` let me know.

**Comment by vemv** [comment]
Cheers! Thanks for the continued work 🍻
