### ISSUE TITLE
Detect mistyped metadata on def and defn

### ISSUE THREAD

**Issue by danielcompton** [clj-kondo/clj-kondo#1529]
To upvote this issue, give it a thumbs up. See [this list](https://github.com/clj-kondo/clj-kondo/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) for the most upvoted issues.

**Is your feature request related to a problem? Please describe.**

I noticed that in Reagent, metadata was meant to be created, but the `^` was missed so it was just a plain map. I fixed this case in https://github.com/reagent-project/reagent/pull/561.

**Describe the solution you'd like**

In `defn`, `def` (and maybe others?), if someone places a map or a keyword in the metadata position without adding `^`, warn about it.

Now that I'm looking at it, I'm not exactly sure what the correct way is to associate metadata maps, there seems to be a few options and maybe even differences between CLJ and CLJS?

**Describe alternatives you've considered**

This is pretty difficult to grep for because you're just searching for a map.

**Additional context**

**Comment by Deraen** [comment]
`defn` takes optional metadata map as the "third" parameter (after name and optional docstring): https://clojuredocs.org/clojure.core/defn

`^` is separate thing, and can be used to add metadata to symbols/vars, then it needs to be before the name, e.g. `(defn ^{:foo true} render ...)`.

**Comment by borkdude** [comment]
The`defn` macro takes a metamap like this, without the caret:

```
user=> (defn foo {:bar true} [])
#'user/foo
user=> (meta #'foo)
{:arglists ([]), :bar true, :line 1, :column 1, :file "NO_SOURCE_PATH", :name foo, :ns #object[clojure.lang.Namespace 0x3cbcd8f3 "user"]}
```

So I think this isn't an issue that clj-kondo should detect?

**Comment by danielcompton** [comment]
Yeah, I think this might actually be a CLJS/Closure issue? Sorry for the noise.
