### ISSUE TITLE
clj-kondo hangs on large codebase with 2022.01.13

### ISSUE THREAD

**Issue by logseq-cldwalker** [clj-kondo/clj-kondo#1536]
Hi @borkdude. I'm introducing clj-kondo at work on a fairly large cljs codebase - https://github.com/logseq/logseq. Noticing some unusual behavior and appreciate any insight you can give into the issue I'm seeing.

More details below:

---
**version**

2022.01.13 but also seen on 2021.12.19

**macro usage**

n/a

**platform**

jvm

**editor**

n/a

**problem**

When I [upgrade clj-kondo from 2021.10.19 to 2022.01.13](https://github.com/logseq/logseq/pull/3896/commits/b451578997eabaeffc2ee9f951b10a25183b06a3), suddenly the linting process is unable to complete and just hangs. I experienced this locally on osx and on CI e.g. https://github.com/logseq/logseq/runs/4809856616?check_suite_focus=true

**repro**

* Clone and checkout this https://github.com/logseq/logseq/tree/test/add-clj-kondo-part-trois-hang
* Run ` clojure -M:clj-kondo --lint src`

Example output seen:

```sh
$ clojure -M:clj-kondo --lint src
DEPRECATED: Libs must be qualified, change quoin => quoin/quoin (/Users/me/.gitlibs/libs/hickory/hickory/9c2c2f1fc2c45efaad906e0faabc3201278deeaa/deps.edn)
DEPRECATED: Libs must be qualified, change quoin => quoin/quoin (/Users/me/.gitlibs/libs/hickory/hickory/9c2c2f1fc2c45efaad906e0faabc3201278deeaa/deps.edn)
..............................
```

Normally the output spans two lines and exits 0. To see a working example, switch to https://github.com/logseq/logseq/tree/test/add-clj-kondo-part-trois to run a passing lint

**config**

https://github.com/logseq/logseq/blob/fe1cd2d90b1fddeacc270f34227ab7d4f82abb00/.clj-kondo/config.edn

**expected behavior**

I expect clj-kondo to lint and not hang as seen on a previous version

**Comment by borkdude** [comment]
Can you see any CPU activity? What is the memory consumption of the process on on your machine? I'll take a look tomorrow.

**Comment by logseq-cldwalker** [comment]
CPU is at 100%. Memory is steady at 680MB. Thanks

**Comment by borkdude** [comment]
Could be some sort of infinite loop. Could you disable the hooks and see if that helps?

**Comment by logseq-cldwalker** [comment]
Good call. Rum hooks were causing the hang. But now I have `linting took
3357ms, errors: 757, warnings: 137` hehe

**Comment by borkdude** [comment]
OK, add some printing to your hooks, to see which expressions and files cause the loop,

**Comment by logseq-cldwalker** [comment]
I don't see any prn statements when I place them in the body of the hooks
e.g.
https://github.com/logseq/logseq/blob/7c8e8e06c68545203f637e83d9ab7482b5f4e2ab/.clj-kondo/hooks/rum.clj#L62-L68
. I don't see anything with :output unconfigured or with it set to
:progress. Is there a specific :output configuration I need?

**Comment by borkdude** [comment]
No, you should see the printed output when the hook is executed.

**Comment by borkdude** [comment]
After adding some logging in clj-kondo, it seems to be stuck here:

```
src/workspaces/workspaces/cards.cljs
```

Digging further.

**Comment by borkdude** [comment]
This file seems to lint fine with the binary clj-kondo, but in the JVM it seems to get stuck in a loop. Digging further.

**Comment by borkdude** [comment]
@logseq-cldwalker Found the issue. When running a tool, you're adviced to use `:deps` (or `:replace-deps` in older versions of the CLI). What happened is that clj-kondo was running with an older version of SCI, since you used `:extra-deps`. Changing it to:

```
           :clj-kondo {:deps {clj-kondo/clj-kondo {:mvn/version "2022.01.13"}}
                       :main-opts  ["-m" "clj-kondo.main"]}
```

makes the linting work.

Also, please upgrade SCI anyway!

**Comment by logseq-cldwalker** [comment]
Thanks for tracking this down ❤️ . I think you meant [:deps is deprecated](https://clojure.org/releases/tools#v1.10.1.697). The [jvm doc](https://github.com/clj-kondo/clj-kondo/blob/master/doc/jvm.md) mentions :extra-deps. I can fix that if it's helpful

**Comment by borkdude** [comment]
I guess so. https://clojure.org/reference/deps_and_cli Yes, PR more than welcome!
