### ISSUE TITLE
Add lint for {:keys [a :as m]}

### ISSUE THREAD

**Issue by john-shaffer** [clj-kondo/clj-kondo#1543]
```clojure
;; What the lint would warn on:
;; Accidentally binding 'as to nil and 'm to nil (in most cases)
;; If the map contains :as or :m keys, the those syms will be bound to those values
(defn oops [{:keys [a :as m]}]
  (prn a as m))

;; The intended behavior: 'm is bound to the fn argument, 'as is not bound at all
(defn fine [{:keys [a] :as m}]
  (prn a m))
```

This is not hard to type accidentally given how often :as is used, and the misplaced  ] can be very hard to see.

I think the lint could look for :as anywhere within a :keys/:strs/:syms destructuring vector, since there is no reason to use `{:keys [:as]}` intentionally (you would use `{:keys [as]}`.

**Comment by borkdude** [comment]
Opt-in linter welcome. Some people use `{:keys [:foo :bar]}` - I've done this myself for a long time as it was the style of one of my former colleagues and I wanted to align with the style of the codebase.
