### ISSUE TITLE
Provide custom hooks with the ability to expand namespace aliases on symbols

### ISSUE THREAD

**Issue by dannyfreeman** [clj-kondo/clj-kondo#1546]
**Is your feature request related to a problem? Please describe.**
While writing a custom clj-kondo hook, I would like to resolve the namespace aliases in symbol tokens that represent vars.
For example, if I encounter one of the tokens `re-frame/subscribe`, `rf/subscribe`, or `subscribe` in a namespace with a require statement like `[re-frame.core :as rf]`, `[re-frame.core :as re-frame]`, or `[re-frame.core :refer [subscribe]]` I'd like to be able to expand those symbols to `re-frame.core/subscribe`. If I can do this I'd be confident that the symbol I've encountered that belongs to the namespace I expect, and is not something like `[not.re-frame :as rf]`.

**Describe the solution you'd like**
I'd like to be able to call something like `(clj-kondo.hooks-api/expand-ns 'rf/subscribe)` in a namespace with a require statement `[re-frame.core :as rf]` and have `'re-frame.core/subscribe` returned based on aliases in the namespace under analysis.

Another solution that would be fine is access to the current aliases in the namespace being analyzed. 

**Describe alternatives you've considered**
I have an acceptable workaround right now. I have a list of symbols that `re-frame.core/subscribe` is commonly referred to as, and I can check all of those instead of checking only the fully expanded symbol. Using this combined with the [`:consistent-alias`](https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#consistent-alias) linter I can be pretty confident what symbol I'm working with in my custom hook.

**Additional context**
I'd be happy to help create a PR. I've never worked on this codebase or with sci, but if I could be pointed in the right direction I'd be happy to take a swing at it.

**Comment by borkdude** [comment]
Note that `foo/bar` can also be a static access to a class. So I think we need the equivalent of `resolve` but the result should be telling us that its a var or a class, so the return value will likely be a map. 

Passing the map of aliases -> namespaces is something we could easily do.

**Comment by camsaul** [comment]
Big +1 on this. Access to the map of aliases->namespaces would be great.

My use case is I want to disallow `with-redefs` inside of a parallel test (using a custom test runner).

```clj
(deftest ^:parallel my-parallel-test
  ;; this should error
  (with-redefs [...]
     ...))
```

I have that linter working so long as the symbol is `with-redefs` or `clojure.core/with-redefs`... if you try to do something sneaky and alias `clojure.core` as something else you can get around it.

**Comment by camsaul** [comment]
I think this is basically the same thing I was asking for in #1996, and it was added in https://github.com/clj-kondo/clj-kondo/commit/e92982f2adc6f753c74c9fcc74acb0f62227651f earlier this year

**Comment by borkdude** [comment]
Thanks @camsaul, you're right, I'll close this one.
