### ISSUE TITLE
Detect and warn on cyclic task dependencies in bb.edn

### ISSUE THREAD

**Issue by mknoszlig** [clj-kondo/clj-kondo#1549]
babashka has cycle detection for tasks:

`bb.edn`:
```clojure
{:tasks {a {:depends [c]
            :task (println "a")}
         b {:depends [a]
            :task (println "b")}
         c {:depends [b]
            :task (println "c")}}}
```

```shell
> bb run a
Cyclic task: a
```

It would be nice to have this detection available in clj-kondo and possibly even some more info on the nature of cycle.
In the above example, the message could be something like `cyclic task dependency: a -> c -> b -> a`.

**Comment by borkdude** [comment]
Agreed
