### ISSUE TITLE
Support `clojure.test.check.properties/for-all`

### ISSUE THREAD

**Issue by ericdallo** [clj-kondo/clj-kondo#1594]
To upvote this issue, give it a thumbs up. See [this list](https://github.com/clj-kondo/clj-kondo/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) for the most upvoted issues.

**Is your feature request related to a problem? Please describe.**
As mentioned [here](https://clojurians.slack.com/archives/CHY97NXE2/p1620406367426000), I think we could support by default linting `clojure.test.check.properties/prop` as `clojure.core/let`?

**Comment by borkdude** [comment]
PR welcome
