### ISSUE TITLE
[analysis] Consider making is easier to distinguish protocols defs from protocol methods

### ISSUE THREAD

**Issue by lread** [clj-kondo/clj-kondo#1602]
To upvote this issue, give it a thumbs up. See [this list](https://github.com/clj-kondo/clj-kondo/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) for the most upvoted issues.

## Problem
I am currently [exploring adding clj-kondo as an alternate cljdoc API analyzer](https://github.com/cljdoc/cljdoc/issues/543).

### cljdoc analyzer behavior
The [cljdoc API analyzer](https://github.com/cljdoc/cljdoc-analyzer), which is based on [codox](https://github.com/weavejester/codox), parses [this](https://github.com/clj-commons/rewrite-clj/blob/558a964c28bc78542ac68da5da1d957398e1d4bf/src/rewrite_clj/node/protocols.cljc#L77-L86) 

```Clojure
(defprotocol InnerNode
  "Protocol for non-leaf EDN/Clojure/ClojureScript nodes."
  (inner? [node]
    "Returns true if `node` can have children.")
  (children [node]
    "Returns child nodes for `node`.")
  (replace-children [node children]
    "Returns `node` replacing current children with `children`.")
  (leader-length [node]
    "Returns number of characters before children for `node`."))
```

to:

```Clojure
{:name InnerNode,
 :file "rewrite_clj/node/protocols.cljc",
 :type :protocol,
 :line 77,
 :members
 ({:name children,
   :type :var,
   :arglists ([node]),
   :doc "Returns child nodes for `node`.\n"}
  {:name inner?,
   :type :var,
   :arglists ([node]),
   :doc "Returns true if `node` can have children.\n"}
  {:name leader-length,
   :type :var,
   :arglists ([node]),
   :doc "Returns number of characters before children for `node`.\n"}
  {:name replace-children,
   :type :var,
   :arglists ([node children]),
   :doc
   "Returns `node` replacing current children with `children`.\n"}),
 :doc "Protocol for non-leaf EDN/Clojure/ClojureScript nodes.\n"}
```

### current clj-kondo behavior
If I look at the `:var-definitions` for the above in clj-kondo, I see the protocol itself:

```Clojure
{:end-row 86,
 :meta nil,
 :name-end-col 23,
 :name-end-row 77,
 :name-row 77,
 :ns rewrite-clj.node.protocols,
 :name InnerNode,
 :defined-by clojure.core/defprotocol,
 :lang :clj,
 :filename "rewrite_clj/node/protocols.cljc",
 :col 1,
 :name-col 14,
 :end-col 65,
 :doc "Protocol for non-leaf EDN/Clojure/ClojureScript nodes.", 
 :row 77}
```

But don't see a strong distinction/link-back for its members, for example, here's `children`
```Clojure
{:fixed-arities #{1},
 :end-row 86,
 :meta nil,
 :name-end-col 12,
 :name-end-row 81,
 :name-row 81,
 :ns rewrite-clj.node.protocols,
 :name children,
 :defined-by clojure.core/defprotocol,
 :lang :clj,
 :filename "rewrite_clj/node/protocols.cljc",
 :col 1,
 :name-col 4,
 :end-col 65,
 :arglist-strs ["[node]"],
 :doc "Returns child nodes for `node`.", 
 :row 77}
```

## Proposals
There are many ways to solve this.
In the spirit of getting the idea ball rolling, here's what I've come up with so far.
I don't think option 1 is horrible but would personally prefer something along the lines of option 2 or 4.

### Option 1 - do nothing - user can probably infer
I think maybe I could infer that `InnerNode` is the protocol by seeing it has no arglists.
And then I could infer that `children` is part of `InnerNode` checking `:row` for overlap.

Pros:
- no changes to clj-kondo

Cons:
- user has to infer

### Option 2 - take inspiration from `:protocol-impl`
I do see the new `:protocol-impls` work, and that looks cool, but I don't think it helps with protocol definitions. For handy reference here's an example `:protocol-impl` entry:

```Clojure
{:impl-ns rewrite-clj.node.keyword,
 :end-row 43,
 :name-end-col 10,
 :protocol-ns rewrite-clj.node.protocols,
 :name-end-row 41,
 :method-name string,
 :name-row 41,
 :defined-by cljs.core/defrecord,
 :protocol-name Node,
 :filename "rewrite_clj/node/keyword.cljc",
 :col 3, 
 :name-col 4, 
 :end-col 22, 
 :row 41}
```

One idea would be to add the `:protocol-name` to the `:var-definitions` protocol members.

Pros:
- seems like a small simple change, at least data-wise

Cons:
- Is this still on the vague side? Could we be more explicit?

### Option 3 - Mimic codox `:members` structure
See example under problem section.

Cons:
- potentially breaking change?
- I typically find nested data is harder to generically work with than flat structures

### Option 4 - Describe under `:protocol-impls` or a new `:protocol-defs`
Pros:
- groups protocol info together
- extra analysis is only invoked when requested

## Context
This issue was extracted from bloated #405.

Clj-kondo analysis for above examples generated via:
```Shell
clj-kondo --config '{:config-paths ^:replace [] :output {:format :edn :analysis {:arglists true :namespace-definitions {:meta true} :var-definitions {:meta true} :protocol-impls true}}}' --lint  ~/.m2/repository/rewrite-clj/rewrite-clj/1.0.699-alpha/rewrite-clj-1.0.699-alpha.jar | jet --pretty > dump.edn
```

## Next Steps
Happy to help in any way that's useful including a PR.

**Comment by borkdude** [comment]
I think 2 would be a small change and makes sense to me. Adding `:protocol-ns` + `:protocol-name` in a PR would be ok with me.
