### ISSUE TITLE
VSCODE + clj-kondo extension + Windows 10 Pro fails to parse file

### ISSUE THREAD

**Issue by fdabrao** [clj-kondo/clj-kondo#1605]
**version**

`v2022.03.04`

**platform**

`VSCODE` + `clj-kondo` extension + Windows 10 Pro

**editor**

`VSCODE`

**problem**

When I use `clj-kondo` extension in Windows 10 Pro, something strange happen, it won't parse the file correctly

**repro**

In only simple `clj.core` happen this
```Can't parse /c:/Trabalho/Pessoal/Fernando/home-project-1/src/core.clj, Illegal char <:> at index 2: .c:.Trabalho.Pessoal.Fernando.home-project-1.src.core.cljclj-kondo```

**Comment by borkdude** [comment]
Can repro locally on Windows + VSCode:

<img width="1063" alt="Screen Shot 2022-03-07 at 21 49 13" src="https://user-images.githubusercontent.com/284934/157115641-37a1f9af-e12d-4b46-ad64-86ed899b625a.png">
