### ISSUE TITLE
Latest update breaks namespace > filename check

### ISSUE THREAD

**Issue by LouDnl** [clj-kondo/clj-kondo#1607]
[ To keep development of this project going, consider sponsoring. If you are
already a sponsor, thank you! ]

**version**

v2022.3.8

**platform**

Windows 10 `Microsoft Windows [Version 10.0.19043.1526]`

**editor**

VSCode:
![image](https://user-images.githubusercontent.com/8543038/157227024-a58155f9-899c-41c5-b445-1a73ff5172f1.png)

**problem**

Latest update that fixes the namespace bug introduces new namespace bug:
![image](https://user-images.githubusercontent.com/8543038/157227226-375c7462-f6cb-4c6a-8983-cea6da2892a0.png)
![image](https://user-images.githubusercontent.com/8543038/157227249-bfd24eed-d412-4234-b1b6-1f4f20791e49.png)

**repro**

Create project, create clojure file with namespace. Error occurs immediatly.

**config**

```clojure
{:hooks   {:analyze-call {taoensso.timbre/refer-timbre hooks.taoensso.timbre/refer-timbre
                          sibiro.params/defnp hooks.sibiro.params/defnp
                          sibiro.params/defnp- hooks.sibiro.params/defnp
                          slingshot.slingshot/try+ hooks.slingshot.try-plus/try+}}
 :lint-as {mount.lite/defstate clojure.core/def
           taoensso.encore/defonce clojure.core/def}
 :linters {:unused-referred-var {:exclude {mount.lite [defstate]}}
           :unused-namespace    {:exclude ["^aorta.*"]}
           :clojure-lsp/unused-public-var {:level :off}}
 :skip-comments true}
```

**expected behavior**

Do not give namespace / filename error

**Comment by borkdude** [comment]
Worth mentioning that with a single segment namespace it did work correctly.

**Comment by borkdude** [comment]
@svdo If you want to look into it, the error happens when calling clj-kondo via this LSP server:

https://github.com/clj-kondo/clj-kondo.lsp/blob/c7f741917ed2d40274ae8696ce5efce23df4a3d4/server/src/clj_kondo/lsp_server/impl/server.clj#L125-L143

**Comment by borkdude** [comment]
@svdo @LouDnl I have a vsix for debugging here:

[extension.zip](https://github.com/clj-kondo/clj-kondo/files/8224637/extension.zip)

I added `(spit (io/file "clj-kondo.log") [filename filename* ns-name munged-ns] :append true)` to the code in case of a name mismatch, so we can see what clj-kondo encountered. Please post the contents of this file so we can debug further. You still have to enable the linter.

**Comment by borkdude** [comment]
Using that extension, I was able to reproduce it again on Windows and got the following `clj-kondo.log`:

```
type .\clj-kondo.log
["/c:/Users/borkdude/dev/clj-kondo.lsp/server/src/clj_kondo/lsp_server/impl/server.clj" "c:\\Users\\borkdude\\dev\\clj-kondo.lsp\\server\\src\\clj_kondo\\lsp_server\\impl\\server" clj-kondo.lsp-server.impl.server "clj_kondo.lsp_server.impl.server"]["/c:/Users/borkdude/dev/clj-kondo.lsp/server/src/clj_kondo/lsp_server/impl/server.clj" "c:\\Users\\borkdude\\dev\\clj-kondo.lsp\\server\\src\\clj_kondo\\lsp_server\\impl\\server" clj-kondo.lsp-server.impl.server "clj_kondo.lsp_server.impl.server"]["/c:/Users/borkdude/dev/clj-kondo.lsp/server/src/clj_kondo/lsp_server/impl/server.clj" "c:\\Users\\borkdude\\dev\\clj-kondo.lsp\\server\\src\\clj_kondo\\lsp_server\\impl\\server" clj-kondo.lsp-server.impl.server "clj_kondo.lsp_server.impl.server"]
```

**Comment by borkdude** [comment]
It looks correct in the REPL:

```
user=> (def filename "/c:/Users/borkdude/dev/clj-kondo.lsp/server/src/clj_kondo/lsp_server/impl/server.clj")
#'user/filename
user=> (some-> filename
                                    ^String (fs/strip-ext)
                                    ^String (.replace "/" ".")
                                    (cond-> (not= fs/file-separator "/")
                                      (.replace ^CharSequence fs/file-separator ".")))
"c:.Users.borkdude.dev.clj-kondo.lsp.server.src.clj_kondo.lsp_server.impl.server"
```

**Comment by svdo** [comment]
@borkdude Is the problem maybe that the return value of `babashka.fs/strip-ext` appears to be a `java.nio.File.Path` instance, but in the code that I added there is a `^String` type hint; maybe that gives problems with GraalVM (and not in the REPL)?

**Comment by borkdude** [comment]
```
user=> (require '[babashka.fs :as fs])
nil
user=> (fs/strip-ext "foo.bar")
"foo"
```

**Comment by borkdude** [comment]
The code isn't running in GraalVM in this extension, but in a normal JVM

**Comment by borkdude** [comment]
I'll add some more logging tomorrow and then I'll publish a new plugin here

**Comment by borkdude** [comment]
Added more logging:

[extension2.zip](https://github.com/clj-kondo/clj-kondo/files/8232063/extension2.zip)

**Comment by borkdude** [comment]
Logs:
```
c:\Users\borkdude\dev\clj-kondo\src\clj_kondo\core :<-:stripped
c:\Users\borkdude\dev\clj-kondo\src\clj_kondo\core :<-replaced
[:filename "/c:/Users/borkdude/dev/clj-kondo/src/clj_kondo/core.clj" "c:\\Users\\borkdude\\dev\\clj-kondo\\src\\clj_kondo\\core" "c:\\Users\\borkdude\\dev\\clj-kondo\\src\\clj_kondo\\core" :ns-name clj-kondo.core :munged-ns "clj_kondo.core"] :append true
```
It seems the `(not= fs/file-separator "/")` condition isn't hit in the extension... since I would have also expected `:replace2` to be logged:

``` clojure
            (let [log (fn [& strs]
                        (spit (io/file "clj-kondo.log") (str (str/join " " strs) "\n") :append true))
                  filename* (some-> filename
                                    ^String (fs/strip-ext)
                                    (doto (log :<-:stripped))
                                    ^String (.replace "/" ".")
                                    (doto (log :<-replaced))
                                    (cond-> (not= fs/file-separator "/")
                                      (-> (doto (.replace ^CharSequence fs/file-separator ".")
                                            (log :<-replace2)))))
                  munged-ns (str (munge ns-name))]
              (when (and filename*
                         (not (str/ends-with? filename* munged-ns)))
                (log [:filename filename filename* filename* :ns-name ns-name :munged-ns munged-ns] :append true)
```

**Comment by borkdude** [comment]
Could it be that an extension is running inside linux in Visual Studio Code on Windows...?

**Comment by borkdude** [comment]
Removed conditional, always replace backslashes:

[extension3.zip](https://github.com/clj-kondo/clj-kondo/files/8232164/extension3.zip)

**Comment by borkdude** [comment]
That seems to work. Well, let's just always replace backslashes, no matter the OS, it seems a sane thing to do.

**Comment by borkdude** [comment]
One last time, I'm logging the file separator and OS name at startup within the extension:

[extension4.zip](https://github.com/clj-kondo/clj-kondo/files/8232334/extension4.zip)


``` clojure
     (info "Clj-kondo language server loaded. Please report any issues to https://github.com/borkdude/clj-kondo.")
     (info "OS" (System/getProperty "os.name"))
     (info "FS separator" java.io.File/separator)
```

**Comment by borkdude** [comment]
It beats me...

```
[Info  - 2:46:39 PM] Clj-kondo language server loaded. Please report any issues to https://github.com/borkdude/clj-kondo.
[Info  - 2:46:39 PM] OS Windows 10
[Info  - 2:46:39 PM] FS separator \
```

**Comment by svdo** [comment]
Yeah I guess that's the best you can do, good enough for me to be sure. Thanks for all the effort you have put into this thing that seemed so simple!!
