### ISSUE TITLE
Provide keyword analysis for keywords in the `ns` form

### ISSUE THREAD

**Issue by PEZ** [clj-kondo/clj-kondo#1609]
To upvote this issue, give it a thumbs up. See [this list](https://github.com/clj-kondo/clj-kondo/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) for the most upvoted issues.

**Is your feature request related to a problem? Please describe.**

Keywords in the `ns` form doesn't get the same treatment as other keywords from the analysis. This results in clojure-lsp being unable to apply things like semantic tokens to these, making them render differently in clients that have semantic tokens enabled.

Here are two screenshots from Calva, showing the difference:

![image (1)](https://user-images.githubusercontent.com/30010/157445871-5c9fa01b-e59f-4aa4-9a32-362df4b7c96e.png)

![image (2)](https://user-images.githubusercontent.com/30010/157445856-b5994752-c40b-47d6-b19a-37f04ec1a8b7.png)

**Describe the solution you'd like**

If clj-kondo provides the keyword analysis for the `ns` form, that's be great!

**Describe alternatives you've considered** / **Additional context**

Semantic tokens for keywords help the users since more themes will highlight them in a special way. Previously Calva solved this by giving them a non-standard TextMate grammar scope, but that causes other problems, so we have changed to use proper TM grammar scopes for keywords.

**Comment by borkdude** [comment]
We didn't analyze those keywords since keyword analysis initially was more about being able to consistently rename (user-defined) keywords. Renaming `:require` in an ns form almost never makes sense. But I'm open to do that.

**Comment by borkdude** [comment]
>  I didn't even know you could do this.

Yes, this is supported by Clojure, although maybe not idiomatic, lots of people use it.

**Comment by ericdallo** [comment]
@PEZ fixed on clj-kondo and clojure-lsp!

**Comment by PEZ** [comment]
Thanks!
