### ISSUE TITLE
[analysis] Information about reify methods

### ISSUE THREAD

**Issue by dbunin** [clj-kondo/clj-kondo#1613]
Is your feature request related to a problem? Please describe.
Consider the code:

```clojure
(defprotocol MyFoo
  (something [this]))

(defn make-foo []
  (reify MyFoo
    (something [_]
      123)))
```

You are able to go to implementation using clojure-lsp with the `defrecords`, but you aren't when the protocol is reified with `reify`.

Describe the solution you'd like
Add `reify` to protocol implementations

**Comment by borkdude** [comment]
Thanks. Related to https://github.com/clj-kondo/clj-kondo/issues/1544. Will look at this, this week hopefully.

**Comment by dbunin** [comment]
Yes, indeed!

**Comment by borkdude** [comment]
Done on master. @ericdallo Plz test :)

**Comment by ericdallo** [comment]
@borkdude I confirmed this issue was fixed ❤️ !
I just noticed references + lens doesn't consider reify, but this is another issue I'll dig further :)

![image](https://user-images.githubusercontent.com/7820865/158675602-bb51b8e9-b318-44ff-84da-3d2e983d206c.png)

**Comment by borkdude** [comment]
Do you mean, the clj-kondo analysis looks good and lsp might need fixing? Or is there something else that needs to be fixed in clj-kondo?

**Comment by ericdallo** [comment]
that's what I'll checking right now 😅 I let you know as soon as I find the issue

**Comment by ericdallo** [comment]
@borkdude AFAICS, it's everything working as expected.
it's expected in that code to `something` be considered as unused/0 references because a reference means a usage of that var-definition, not a implementation (which can be accessible by find-implementations though), this follows the same which other LSPs do like java, dart, ts, so it looks good to me

**Comment by borkdude** [comment]
Cool!

**Comment by iarenaza** [comment]
@borkdude I was working on extending protocol analysis support to other use cases. I already had a working patch (with unit test, etc), but you beat me to it :smile: 

I see that you actually extended protocol implementation analysis not just to `reify`, but to `specify!`, `extend-type` and `extend-record` too (I guess that was a side effect of supporting `extend-type`). But unfortunately your changes don't work for `extend-record`, as the "placement" of the "types" and "protocols" in those functions are "reversed". E.g.,

```
(defprotocol AProtocol
  (a-method [x y z]))

(defrecord ARecord [x])

(extend-protocol AProtocol
  ARecord
  (a-method
    [_x _y _z]
    nil))

(extend-type ARecord
  AProtocol
  (a-method
    [_x _y _z]
    nil))
```
Notice that the positions of `ARecord` and `AProtocol` are "swapped" in `extend-protocol` and `extend-type`.

`extend-protocol` is also a bit special in that the protocol name appears just once, but it can be extended to several records/types in a single form: 

```clj
(defprotocol AProtocol
  (a-method [x y z]))

(defrecord ARecord [x])
(defrecord BRecord [x])

(extend-protocol AProtocol
  ARecord
  (a-method
    [_x _y _z]
    nil)
  BRecord
  (a-method
    [_x _y _z]
    nil))
```

which makes the protocol name handling in the `loop ... recur` body a bit different than the other uses cases.

**Comment by borkdude** [comment]
@iarenaza Thanks! Feel free to open a new issue and optionally a PR if you're interested in working on that.
