### ISSUE TITLE
clj-kondo does not consider arglists metadata as usage of imports

### ISSUE THREAD

**Issue by dpsutton** [clj-kondo/clj-kondo#1617]
**version**

clj-kondo v2022.02.09

**platform**

osx

**editor**

emacs

**problem**

clj-kondo does not consider imports used in argslist metadata

**repro**

```clojure
(ns bug
  (:import java.util.Collection))

(defmulti foo {:arglists '([^Collection coll])} first)
```

Interestingly, it considers j.u.Collection unused in the following form as well:
```clojure
(defmulti foo {:arglists (list [^Collection 'coll])} first)
```

**expected behavior**

the j.u.Collection import should be considered used.

**Comment by borkdude** [comment]
@dpsutton I took a look and I've come to believe this is not a bug. Check this:

```
user=> (defmulti foo {:arglists '([^Collection coll])} first)
nil
user=> (-> (:arglists (meta #'foo)) first first meta)
{:tag Collection}
```

There was no need to import `Collection` here.
But if we do:

```
user=> (ns bug
  (:import java.util.Collection))
nil
bug=> (defmulti foo {:arglists '([^Collection coll])} first)
#'bug/foo
bug=> (-> (:arglists (meta #'foo)) first first meta)
{:tag Collection}
```

the metadata is unaffected by it, i.e the import was really unused.
