### ISSUE TITLE
Lint for clojure.string/split

### ISSUE THREAD

**Issue by nivekuil** [clj-kondo/clj-kondo#1621]
**Is your feature request related to a problem? Please describe.**
Was bit by this: `(clojure.string/split x " ")` works on CLJS, but throws an exception on CLJ.

**Describe the solution you'd like**
I think clj-kondo can catch that the 2nd arg needs to be a `^Pattern`, as in `#" "`. Not sure if kondo can generically generate linters from type hints?

**Comment by borkdude** [comment]
We can add the type here:

https://github.com/clj-kondo/clj-kondo/blob/master/src/clj_kondo/impl/types/clojure/string.clj

although currently clj-kondo doesn't distinguish between types on clj vs cljs... so I guess adding a union of string and regexp doesn't help us here yet.
