### ISSUE TITLE
Rosetta instructions no longer needed, I think?

### ISSUE THREAD

**Issue by eggsyntax** [clj-kondo/clj-kondo#1622]
Just a doc FYI, re: the homebrew instructions in [install.md](https://github.com/clj-kondo/clj-kondo/blob/master/doc/install.md#brew-macos-and-linux):
> Apple's new M1 Silicon computers use the ARM architecture, instead of Intel. To use clj-kondo, you'll need to install Rosetta2 and then run homebrew via that:

On a new M1 Macbook Pro, with Rosetta already activated, `brew install clj-kondo` was fine for me & I can use clj-kondo to lint a project without error, whereas the recommended `arch -x86_64 brew install borkdude/brew/clj-kondo` failed with an error:

<img width="576" alt="image" src="https://user-images.githubusercontent.com/1233514/159132101-d5e610e4-3eaf-459e-96ed-836e513fb4b4.png">

I don't know much about Rosetta2 yet, but my guess is that Homebrew now handles that automatically? @robert-stuttaford I see you added those instructions a few months ago -- any thoughts? I don't see mention of a relevant change in the release notes for the [only Homebrew release](https://brew.sh/2022/02/28/homebrew-3.4.0/) since those instructions were added.

**Comment by eggsyntax** [comment]
Minor update: created a clj repo & clj-kondo linted it fine; updated ticket description accordingly.

**Comment by borkdude** [comment]
PR welcome to remove those instructions.

**Comment by eggsyntax** [comment]
More than happy to make a PR for it; as someone on my first day of using Apple Silicon I just don't have much confidence that other folks won't need the instructions. Hopefully Robert will chime in; otherwise you might want to wait until/unless you hear the same from someone else.

**Comment by robert-stuttaford** [comment]
I simply provided what worked for me back then. If it doesn't work any longer, yank em!

**Comment by eggsyntax** [comment]
Hedged my bets and mentioned both possibilities in the PR 😆

**Comment by borkdude** [comment]
@eggsyntax Are you still going to submit that commit as a PR?

**Comment by eggsyntax** [comment]
Nah, I figured better to maintain a separate fork with improved instructions 😊 

My bad, submitting now!
