### ISSUE TITLE
hook-generated (def ...) form doesn't seem recognized by project requiring sicmutils

### ISSUE THREAD

**Issue by sritchie** [clj-kondo/clj-kondo#1626]
[ To keep development of this project going, consider sponsoring. If you are
already a sponsor, thank you! ]

**version**

[ Please specify which version of clj-kondo you're using. You can find this with `clj-kondo --version`.]

**macro usage**

yes!
**platform**

JVM, also native.

**editor**

emacs via cider.

**problem**

 I’m hitting a problem where in a project that takes sicmutils as a dependency, any namespace that tries to use a form like `new-sym` defined in `sicmutils.env` with `(import-def original-value new-sym)` fails to recognize `sicmutils.env/new-sym`, EVEN THOUGH namespaces inside the project work fine.

@borkdude also noted that the principal-value var doesn't appear here:

```
cat .clj-kondo/.cache/v1/cljc/sicmutils.env.transit.json | jet --from transit --query ':clj keys' --pretty
```

**repro**

https://github.com/sritchie/kondo-repro

**config**

```
{:config-paths ["babashka/sci"
                "sicmutils/sicmutils"]}
```

**expected behavior**

I'd expect that var to resolve correctly, since its hook emits a proper `def` form, and this works inside the `sicmutils` project.

**Comment by borkdude** [comment]
@sritchie Sorry I dropped the ball on this. Is this still a problem?
