### ISSUE TITLE
Introduce re-frame testing code in corpus to prevent future breakage 

### ISSUE THREAD

**Issue by borkdude** [clj-kondo/clj-kondo#1638]
_Originally posted by @borkdude in https://github.com/clj-kondo/clj-kondo/issues/1637#issuecomment-1082735498_

@benedekfazekas I "fixed" this by reverting the analysis commit. Before introducing more analysis changes around re-frame we should first have some more re-frame testing in place that will prevent future breakage (this is the second time we experienced this).
I asked around on Twitter if there are open source projects using re-frame that we could use:

https://twitter.com/borkdude/status/1508933061534228483

Athens Research is one of them. I suggest we take their re-frame code and put it in corpus and lint for 0 warnings/errors. I'll make an issue of this.

**Comment by benedekfazekas** [comment]
looking into this. athens (their `src/cljs` dir) does pass linting with the re-frame commit reverted and does report errors and warnings when linted with the re-frame commit

**Comment by borkdude** [comment]
@benedekfazekas OK, let's add that to `corpus`, e.g. `corpus/re-frame/athens/src/cljs`

**Comment by borkdude** [comment]
And then also add a test for it, I would say separately from the analysis tests: `test/clj_kondo/re_frame_test.clj` and then a test which should result in 0 warnings/errors linting that dir.

**Comment by benedekfazekas** [comment]
PRed

**Comment by benedekfazekas** [comment]
should be closed?
