### ISSUE TITLE
Support callback function for each file analyzed

### ISSUE THREAD

**Issue by ericdallo** [clj-kondo/clj-kondo#1675]
To upvote this issue, give it a thumbs up. See [this list](https://github.com/clj-kondo/clj-kondo/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) for the most upvoted issues.

**Is your feature request related to a problem? Please describe.**
As mentioned [here](https://clojurians.slack.com/archives/CHY97NXE2/p1651283825804139), it'd be super helpful if kondo could provide a callback function that would be called for each analyzed filename, so clojure-lsp could update progress bar smarter and precisely.

**Describe the solution you'd like**
A custom callback function on clj-kondo JVM which would be called N times being N the number of filenames analyzed.
Note: if passing `src`, it'd be even better if kondo could call the callback for each file not only one time.

**Describe alternatives you've considered**

**Additional context**

I can open a PR, any suggestion on where to add that? maybe near existing custom-lint-fn, not sure all files are already available there to loop

**Comment by borkdude** [comment]
@ericdallo PR welcome, this should be near analyze-input. I suggest that we pass a map to the function for extensibility.

**Comment by ericdallo** [comment]
Sure, maybe something like that `(fn [{:keys [filename]}])`

**Comment by borkdude** [comment]
Yes, and/or uri?

**Comment by ericdallo** [comment]
I think we can use URI, I'd love to see kondo in the future using URI for everything, so maybe start with new features is a start?

**Comment by borkdude** [comment]
Yes. It's also already available in the Java analysis. Should be in the context object.
