### ISSUE TITLE
Redefined defmethods

### ISSUE THREAD

**Issue by olivergeorge** [clj-kondo/clj-kondo#1682]
To upvote this issue, give it a thumbs up. See [this list](https://github.com/clj-kondo/clj-kondo/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) for the most upvoted issues.

**Is your feature request related to a problem? Please describe.**
I've just found a bunch of duplicate defmethods in my code.  That is, defmethods which have the same dispatch value.

To fix, I need to work out which is the last to be registered.  That's fiddly and there's a risk of regression if I remove the wrong one.

**Describe the solution you'd like**
It would be nice to pick this up and report like a "Warning: redefined var".

**Describe alternatives you've considered**
Wrapping defmethod and detecting at runtime.

**Comment by borkdude** [comment]
@olivergeorge Do the defmethods live in the same or separate namespaces?

**Comment by olivergeorge** [comment]
Many namespaces. It’s quite a big code base.
