### ISSUE TITLE
Hook code collides with some tools

### ISSUE THREAD

**Issue by imrekoszo** [clj-kondo/clj-kondo#1685]
**version**

v2022.04.25

**platform**

native

**editor**

Cursive, tools.build, tools.namespace

**problem**

As hooks distributed with libs are defined in `.clj` files, which must be on the classpath for clj-kondo to be able to access them, in some cases it causes tools to mistake them for namespaces to be loaded into one's project.

Examples:

- https://github.com/Engelberg/better-cond/blob/master/resources/clj-kondo.exports/better-cond/better-cond/better_cond/core.clj makes Cursive IDE confuse it with the actual implementation of that namespace.
- https://ask.clojure.org/index.php/11434/could-namespace-refresh-sophisticated-directory-filtering describes a problem related to using `tools.namespace/refresh-all`
- https://clojurians.slack.com/archives/C02B5GHQWP4/p1651685386479149 describes a problem with `tools.build/compile-clj`

Workarounds for the latter two have been added to the docs in https://github.com/clj-kondo/clj-kondo/pull/1684/files

**repro**

See docs added in https://github.com/clj-kondo/clj-kondo/pull/1684/files

**expected behavior**

According to [this comment](https://ask.clojure.org/index.php/11434/could-namespace-refresh-sophisticated-directory-filtering?show=11882#c11882) (and preceding ones) by @puredanger, it should not be a surprise to developers that any file with a clojure source file extension and on the classpath might be attempted to be loaded by tools by default, and that some of these tools don't have a convenient way to apply filtering before loading is attempted.

Perhaps it would be less prone to these types of problems to allow for hooks to be defined in files with a clj-kondo-specific extension (and encourage the use of that, while still supporting the current one for backwards-compatibility). One idea could be to adopt the `.clj-kondo` extension, but I'd leave this decision to the maintainers.

For more background on this issue, see https://clojurians.slack.com/archives/CHY97NXE2/p1641398954304500

**Comment by borkdude** [comment]
I think all things considered supporting a `.kondo` extension could be a good solution.

**Comment by borkdude** [comment]
From the next release on, clj-kondo supports the `.clj_kondo` extension
