### ISSUE TITLE
Imported Configs are now Automatically Activated

### ISSUE THREAD

**Issue by lread** [clj-kondo/clj-kondo#1697]
## Version
`v2022.04.25`

## Platform
All

## Problem
Docs and messaging around imported configs are a bit stale.
It is no longer necessary to specify imported configs in `:config-paths` if the import config conforms the suggested structure.

## Repro
In a new empty dir, given the following `deps.edn`
```Clojure
{:deps {clj-kondo/config {:git/url "https://github.com/clj-kondo/config"
                          :sha "c37c13ea09b6aaf23db3a7a9a0574f422bb0b4c2"}}}
```
Run:
```
$ mkdir .clj-kondo
$ clj-kondo --copy-configs --dependencies --lint "$(clojure -Spath)"
Imported config to .clj-kondo/clj-kondo/better-cond. To activate, add "clj-kondo/better-cond" to :config-paths in .clj-kondo/config.edn.
Imported config to .clj-kondo/clj-kondo/claypoole. To activate, add "clj-kondo/claypoole" to :config-paths in .clj-kondo/config.edn.
Imported config to .clj-kondo/clj-kondo/mockery. To activate, add "clj-kondo/mockery" to :config-paths in .clj-kondo/config.edn.
Imported config to .clj-kondo/clj-kondo/rum. To activate, add "clj-kondo/rum" to :config-paths in .clj-kondo/config.edn.
Imported config to .clj-kondo/clj-kondo/slingshot. To activate, add "clj-kondo/slingshot" to :config-paths in .clj-kondo/config.edn.
```

## Proposals
Happy to discuss, just initial ideas:

### Messaging
Proposal for new messaging:

```
Active imported configs:
- .clj-kondo/clj-kondo/better-cond. 
- .clj-kondo/clj-kondo/claypoole. 
- .clj-kondo/clj-kondo/mockery. 
- .clj-kondo/clj-kondo/rum. 
- .clj-kondo/clj-kondo/slingshot.
```

When none found, no message is displayed.

### Handling of existing/new/modified
We are currently only showing new configs where a new config is one that is not already specified in `:config-paths`.  

Option 1: show all active import configs (current proposal)
Option 2: show all active import configs but mark new/changed ones
Option 3: show only new/changed import configs
Option 4: ?

### Handling of configured :config-paths
Since we are focused on imported configs, I propose that we report on what is found in the file system and not look at anything that might happen to be in `config.edn` `:config-paths`.

### Docs
Config docs should be updated to match new messaging and behavior.

## Next Steps
After we agree on an approach, I am happy to follow up with a PR.

**Comment by borkdude** [comment]
My preference would be to only report what `--copy-configs` _copied_ (so only new + changed), if and only if `--copy-configs` was used. In other cases, clj-kondo should not generate any noise.

**Comment by lread** [comment]
Yeah, good, makes sense!

How about using the same language as the `--copy-configs` option?:

```
Configs copied:
- .clj-kondo/clj-kondo/better-cond
- .clj-kondo/clj-kondo/claypoole
- .clj-kondo/clj-kondo/mockery
- .clj-kondo/clj-kondo/rum
- .clj-kondo/clj-kondo/slingshot
```

And maybe, since the user has asked for configs to be copied, a message, when there are none copied, would be helpful?:

```
No configs copied.
```

Also looks like `--dependencies` is no longer required for the copy to occur. 
I'll update docs there too  (but examples will still include it).

**Comment by borkdude** [comment]
Sounds good! `--dependencies` is only to suppress lint warnings
