### ISSUE TITLE
Pre-commit support

### ISSUE THREAD

**Issue by joelhess** [clj-kondo/clj-kondo#1705]
[ Leave this text in if you want to promote it. ]

To upvote this issue, give it a thumbs up. See [this list](https://github.com/clj-kondo/clj-kondo/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) for the most upvoted issues.

[ To keep development of this project going, consider sponsoring. If you are
already a sponsor, thank you! You can remove this message. ]

**Is your feature request related to a problem? Please describe.**
pre-commit is a tool to help manage/configure git hooks. It helps set up the hook configuration based on some simple yaml config. It'd be great if clj-kondo could integrate with it to help with running the linter as a git pre-commit hook.

**Describe the solution you'd like**
Add a .pre-commit-hooks.yaml to the repo that can be used to integrate with the tool 

**Describe alternatives you've considered**
you could just set up the hook yourself, but I've found this tooling to be really helpful for my team and me.

**Additional context**
Check out pre-commit.com for addtional details

I have fork for this that I'll be PR-ing.

**Comment by borkdude** [comment]
@joelhess I'm sure pre-commit is a useful tool but doesn't that config has to live in a project where users would use the precommit too? Checking it into clj-kondo itself will only make it useful for clj-kondo developers?

**Comment by borkdude** [comment]
I see, so the PR contains some hook declaration and a user should make a `.pre-commit-config.yaml` that references this PR's config from this repo? And in addition to `clj-kondo --lint` they should provide their own arguments like `src:test`? 
What does the other keys:

``` clojure
 language: system
 types: [clojure]
 require_serial: true
``` 

mean? 

Does it have any value to have such a basic config in clj-kondo's repository? I can imagine that it would be simple enough just write `clj-kondo --lint src:test` in a `.pre-commit-config.yaml` yourself without referencing this repo?

**Comment by joelhess** [comment]
```
 language: system // clj-kondo runs as a executable (as opposed to under a python or node runtime or something)
 types: [clojure] // Runs against Clojure File Types that are staged for commit 
 require_serial: true // Requires that the hook runs serially (I think I can take this off)...
```
Since this is a git hook, it only executes against the list of files that have staged changes. Additional arguments can be passed in via the local repo's config file if desired. 

Is it simple enough to do yourself? It's as simple as managing git hooks for multiple languages can be? Pre-commit has turned into a fairly popular tool though (8.2K stars), and this would help particularly with projects that are managing multiple hooks for multiple languages. If you're already using pre-commit, all it takes would be to add a block to your config like this:
```  
- repo: https://github.com/clj-kondo/clj-kondo
    rev: v2022.04.25
    hooks:
      - id: clj-kondo
 ```
You also get some added visibility to clj-kondo when it's included in the listings for available tools on the pre-commit site.

**Comment by borkdude** [comment]
Sounds good. Just one side-note: It's often not sufficient to lint only the changed files, as a change in one file impacts other files. E.g. if you change an arity in function `foo/f` and that one is used in namespace `bar`, you also have to lint `bar`. Although we also do that here:

https://github.com/clj-kondo/clj-kondo/blob/master/doc/ci-integration.md#pre-commit-hook

I think we should then update the docs there as well?

**Comment by joelhess** [comment]
Sure. Do you think that should be part of my PR, Or a separate update?

**Comment by borkdude** [comment]
I think it would make sense for this PR

**Comment by joelhess** [comment]
I think I misinterpreted... You just want some info about the pre-commit tooling added to the docs?

**Comment by borkdude** [comment]
Yeah, in this section:

https://github.com/clj-kondo/clj-kondo/blob/master/doc/ci-integration.md#pre-commit-hook

**Comment by borkdude** [comment]
What I meant was that you would add this snippet:

.pre-commit-config.yaml:
```
- repo: https://github.com/clj-kondo/clj-kondo
    rev: v2022.04.25
    hooks:
      - id: clj-kondo
```

to the ci-integration.md file (in addition to the link you just added), so it's immediately obvious how to configure it.
