### ISSUE TITLE
comment blocks could be ignored for some warnings (or don't lint across comment blocks)

### ISSUE THREAD

**Issue by benjamin-asdf** [clj-kondo/clj-kondo#1719]
```clojure
(comment
  (require '[babashka.curl :as curl])
  ;; rich comment 1

  )

(comment
  ;; duplicate require of babashka.curl
  (require '[babashka.curl :as curl])
  ;; rich comment 2

  )
```

maybe  I am the only one running  into this... ? 
I make  multiple rich comments in a file because they have a different theme - usually because I come back to a file and want to check something new. 

This is 1 example of where the linter could ignore other comment blocks, basically lint on the global scope and in the comment scope but not across comments.

If you decide this sounds usefull, I can check if I can make a pr.

**Comment by borkdude** [comment]
@benjamin-asdf You can configure your linters in comment forms using `:config-in-comment {:linters {....}}`. I think that sufficiently covers this.

**Comment by benjamin-asdf** [comment]
ah sweet. I will do that can close I guess.
