### ISSUE TITLE
Extra linter: discouraged-ns

### ISSUE THREAD

**Issue by DeLaGuardo** [clj-kondo/clj-kondo#1721]
To upvote this issue, give it a thumbs up. See [this list](https://github.com/clj-kondo/clj-kondo/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) for the most upvoted issues.

**Is your feature request related to a problem? Please describe.**
Some projects might discourage requiring some namespaces by a convention or because of other reasons like the potential consequences of loading namespace (requiring is mutable operation).

**Describe the solution you'd like**
Add one more linter similar to discourage-var, except it will check namespace declaration for the occurrence of a specific namespace symbol and emit a warning pointing to its location.

**Describe alternatives you've considered**
Extend discourage-var linter with the ability to place namespace instead of fully qualified var name and make it check namespace declaration and other forms.

**Comment by borkdude** [comment]
In addition, it might also be desired to express that you cannot use namespace X from namespace Y.
