### ISSUE TITLE
FR: Allow namespace groups to be used for `:type-mismatch` linter

### ISSUE THREAD

**Issue by riotrah** [clj-kondo/clj-kondo#1723]
[ Leave this text in if you want to promote it. ]

To upvote this issue, give it a thumbs up. See [this list](https://github.com/clj-kondo/clj-kondo/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) for the most upvoted issues.

[ To keep development of this project going, consider sponsoring. If you are
already a sponsor, thank you! You can remove this message. ]

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I cannot make use of namespace groups for `:type-mismatch` linter.

There's a namespace in our codebase where most public symbols are the results of a `defn`-like macro, which are always fns with a predictable arg type. Tried to look into adding a linter rule for this namespace, however the symbols of course vary, and there's tons of them (more info later). I cannot register this linter's rules for the macro that all of those symbols are essentially created by either, of course, as that would not actually lint _their_ calls.

---

**Background / Alternative attempted**

The real reason I came across this is when adding a hook for [`clj-commons.secretary.core/defroute`](https://github.com/clj-commons/secretary).

(I can make a PR to that repo at some point and point this PR to that if desired, though idk how active that project is)

I wanted to add a `(token-node "^Map")` inside a rewritten arg vector, to ensure that only a (single) map arg could be passed to any named routes created via `defroute`. If you're not familiar, `defroute` sorta acts as a `defn`, in that its result is a callable fn, that always takes a single map arg.

I realized I could not use that `token-node` technique, as kondo reports `error: unsupported binding form "^Map"`. Perhaps it's an incorrect usage.

**Describe the solution you'd like**
Allow regex-y definitions for the symbols in a particular namespace to apply the `:type-mismatch` rule to (eg namespace groups)

[ Optional: if you are interested in doing a PR yourself, please leave a note. ]
Am open to doing myself <3

**Comment by borkdude** [comment]
I have trouble understanding your use case. Could you please give some examples?

**Comment by riotrah** [comment]
**The primary request is simply to extend the use of namespace groups to be used with the `type-mismatch` linter**,[ as suggested by the final line of the relevant section in `config.md`](https://github.com/clj-kondo/clj-kondo/blob/master/doc/config.md#namespace-groups).

**Comment by borkdude** [comment]
And what would be an example that would benefit from this? This wasn't clear to me from your description. I can imagine that it would be useful, but I want to make a more educated guess than simply imagining.

**Comment by riotrah** [comment]
My apologies, the description is super duper confusing on second read. I'll update it rn; thanks for following up in any case

**Comment by riotrah** [comment]
Upon second thought, as I was rewriting the description, I realized that namespace groups would not suffice for my use-case.

I'm going to take this down shortly unless there's a reason not to.
