### ISSUE TITLE
Warn on single-arity calls to distinct?, min, max

### ISSUE THREAD

**Issue by enaeher** [clj-kondo/clj-kondo#1738]
**Is your feature request related to a problem? Please describe.**
It's a common mistake to pass a collection to `distinct?`, `min`, and `max`. A single-arg invocation of any of these functions is very likely to be an instance of this mistake.

**Describe the solution you'd like**
Kondo should warn something like "Only one arg passed to distinct?"

**Additional context**
It might also be worth warning on two-arg calls to `min-key` and `max-key`.

I intend to implement this myself. Would such a linter be accepted?

**Comment by borkdude** [comment]
We already have a linter called `:redundant-call {:level :warning}` to which we can add these. PR welcome.
