### ISSUE TITLE
Expose imported-ns on vars defined by potemkin/import-vars

### ISSUE THREAD

**Issue by mainej** [clj-kondo/clj-kondo#1744]
**Is your feature request related to a problem? Please describe.**
When a var is defined by potemkin, clojure-lsp needs to know which namespace that var was imported from to fix https://github.com/clojure-lsp/clojure-lsp/issues/1020.

**Describe the solution you'd like**
The analysis of var definitions that are defined by `potemkin/import-vars` should include the `:imported-ns`, the namespace that originally defined the var.

**Describe alternatives you've considered**
When clojure-lsp is trying to show the definition of one of these vars, currently it looks at all other var definitions that have the same name, and assumes that one of them is right. This works as long as there's only one namespace that defines a var with that particular name, but can lead to the wrong var otherwise.

I'll submit a PR to expose `:imported-ns`.

**Comment by borkdude** [comment]
Sure!
