### ISSUE TITLE
allow `clojure.pprint` in hooks

### ISSUE THREAD

**Issue by valyagolev** [clj-kondo/clj-kondo#1749]
[ Leave this text in if you want to promote it. ]

To upvote this issue, give it a thumbs up. See [this list](https://github.com/clj-kondo/clj-kondo/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) for the most upvoted issues.

**Is your feature request related to a problem? Please describe.**

I want to use pretty-printing in the macro hook to enrich the docs I see on hover. For some reason I can't load the library: `Could not find namespace: clojure.pprint.` (`cljs.pprint` is also no luck)

**Describe the solution you'd like**
I'm not very familiar with the kind of Clojure clj-kondo is running in, but hopefully the runtime would include `pprint`. Babashka has it, apparently.

**Describe alternatives you've considered**
My own pprint? Sounds complicated. 

**Additional context**

[ Optional: if you are interested in doing a PR yourself, please leave a note. ]

I would do a Pull Request, but I'm absolutely lost here because I have no idea how clj-kondo works and why it doesn't have pprint while having other clojure libraries...

**Comment by borkdude** [comment]
Hooks run in an interpreter (same as babashka) with restricted access. Adding pprint seems reasonable.
