### ISSUE TITLE
Linter: Warn when a namespace use `_` instead of `-` on its name.

### ISSUE THREAD

**Issue by ericdallo** [clj-kondo/clj-kondo#1753]
To upvote this issue, give it a thumbs up. See [this list](https://github.com/clj-kondo/clj-kondo/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) for the most upvoted issues.

**Is your feature request related to a problem? Please describe.**
Today I saw someone facing a error which clj-kondo could probably help, warn when the ns is using `_` instead of `-` like `(ns foo_bar)` instead of `(ns foo-bar)`

**Describe the solution you'd like**
A new linter complaining about that

**Describe alternatives you've considered**
Do nothing

**Additional context**

**Comment by dharrigan** [comment]
Hi,

I was toying with the idea of doing this one. I put together a simple repo here `https://github.com/dharrigan/issue-1753` to see what would happen before doing anything on clj-kondo.

Looks like `foo_bar` is still valid, i.e., in `bar` I can bring in the `foo_bar` namespace and eval (at line 5) to get 3.

Would a warn that `_` in a namespace isn't best practice still be okay?

**Comment by ericdallo** [comment]
I like it

**Comment by borkdude** [comment]
Yeah

**Comment by borkdude** [comment]
I think we should add a rationale to #2209 in the docs: why is it a good idea to avoid `_` in namespace names?
