### ISSUE TITLE
Warn about using side-effecting functions with lazy sequence operations

### ISSUE THREAD

**Issue by sheluchin** [clj-kondo/clj-kondo#1757]
To upvote this issue, give it a thumbs up. See [this list](https://github.com/clj-kondo/clj-kondo/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) for the most upvoted issues.

**Is your feature request related to a problem? Please describe.**
https://stuartsierra.com/2015/08/25/clojure-donts-lazy-effects suggests a guideline:

> Only use pure functions with the lazy sequence operations like map, filter, take-while, etc. When you need side effects, use one of these alternatives:

This seems like good advice that helps avoid creating bugs related to unexpected laziness.

**Describe the solution you'd like**
Warn about code that uses lazy sequence operations with side-effecting functions. @borkdude [mentions](https://clojurians.slack.com/archives/CHY97NXE2/p1658402205264309?thread_ts=1658402048.673549&cid=CHY97NXE2) this would require adding some side-effect tracking functionality to clj-kondo.

**Describe alternatives you've considered**
I'm not aware of any alternatives besides using the `!` suffix convention to denote side-effecting functions and then being careful about not using them with lazy sequence operations.

**Comment by sheluchin** [comment]
This could be implemented using the var-info list from [Eastwood](https://github.com/jonase/eastwood/blob/master/src/eastwood/util.clj#L1083) added in [#1816.](https://github.com/clj-kondo/clj-kondo/pull/1816/files#diff-d8d8772c091e44dd4ea175b65d977ecee7706a175dfe69ea0b3c110224f5a069)

**Comment by borkdude** [comment]
Right, we could just warn if we know that a function is side effecting based on the list in eastwood

**Comment by sheluchin** [comment]
I personally still think this would be an important thing to have and would not like to see this issue closed, but I also don't have time to work on it myself for the foreseeable future.
