### ISSUE TITLE
:config-paths not parsing `/`

### ISSUE THREAD

**Issue by vemv** [clj-kondo/clj-kondo#1766]
**version**

2022.06.22

**platform**

lein-clj-kondo 0.2.1

**problem**

I'm finding that `:config-paths ["foo/bar"]` doesn't work for a `foo/bar/config.edn` located in the project root, while `:config-paths ["bar"]` does work for a `bar/config.edn` located in the project root.

It's as if sub-directories relative to the project root weren't recognised as such.

WDYT?

Thanks - V

**Comment by borkdude** [comment]
Hmm, this should work (normally). We need a repro github repo. Can you also specify the OS you're using?

**Comment by borkdude** [comment]
Note that config-paths are always relative to the `config.edn` in which you specify them: not relative to the current working directory.

So if you're in `$project/.clj-kondo/config.edn` and you want to add `$project/foo/bar` to the config path, you need to specify: `["../foo/bar"]`.

**Comment by vemv** [comment]
Might have to do with lein-clj-kondo. I'm using https://github.com/clj-kondo/lein-clj-kondo/tree/5099ba40299fdebc53d9096fe5f948ca276f516b#config which doesn't have a location per se, which would break the `Note that config-paths are always relative to the config.edn in which you specify them` assumption

Will verify and/or create a repro

**Comment by vemv** [comment]
While I keep having an issue, I'm not exactly sure of its nature, will debug it directly and then report or PR
