### ISSUE TITLE
(:tag Node) returns nil on TokenNodes

### ISSUE THREAD

**Issue by Liverm0r** [clj-kondo/clj-kondo#1768]
**version**

`clj-kondo v2022.06.22`

**platform**

running from command line, osx m1 monterei 12.5 aarch64-darwin.

**problem**

hook like this:
```clojure
(defn defstackfn [{:keys [node]}]
  (println :tags (->> (:children node) 
                      (map :tag)
                      doall)))
```
prints `(nil nil :vector nil :list)`

**repro**

Repository to reproduce https://github.com/Liverm0r/clj-kondo-tag-nil

**expected behavior**

I would expect `(:tag node)` to return :symbol or :token, for example, and not nil.

**Comment by Liverm0r** [comment]
It seems like [TokenNode](https://github.com/clj-kondo/clj-kondo/blob/master/parser/clj_kondo/impl/rewrite_clj/node/token.clj) record doesn't contain a tag key. 

I don't know why it wasn't added, but seems to be an easy fix.

```clojure
(defrecord TokenNode [`tag`  ;; add this !
                       value string-value]...

(defn token-node
  "Create node for an unspecified EDN token."
  [value & [string-value]]
  (->TokenNode
   :token ;; add this !
    value
    (or string-value (pr-str value))))
```
    
If it's good, I could make a pr tomorrow

**Comment by borkdude** [comment]
@Liverm0r Instead, I think we should expose the `tag` function to the clj-kondo hooks API [here](https://github.com/clj-kondo/clj-kondo/blob/a550a8279e1bf2134921d5a31b98aa68c60f5a00/src/clj_kondo/impl/hooks.clj#L35)

**Comment by borkdude** [comment]
You links do not work, but I think the idea is that `tag` is the public API function and the keyword is kind of an implementation detail. So as long as you through the `tag` function, you will always get back a tag.

**Comment by Liverm0r** [comment]
I could make a pr if you want

**Comment by borkdude** [comment]
Sure!
