### ISSUE TITLE
`Expected: associative collection or nil, received: string` error in custom hooks returning a map node

### ISSUE THREAD

**Issue by camsaul** [clj-kondo/clj-kondo#1773]
**version**

```
clj-kondo v2022.08.03
```

**platform**

Native version on Windows/WSL 2. Installed via Homebrew

**problem**

This is a minimum reproduction of the problem I'm actually running in to. I have a namespace like this:

```clj
(ns my-ns)

(defmacro special-map [_map-type m]
  m)

(defn x []
  (let [num-cans 2]
    (assoc (special-map :world-map {:description (format "%d cans" num-cans)}) :wow :ok)))
```

This is set up to use a custom hook defined like this:

```clj
(ns hooks.my-ns
  (:require [clj-kondo.hooks-api :as hooks]))

(defn special-map
  [{{[_ & args] :children} :node}]
  (let [[_map-type m] (if (= (count args) 1)
                       [(first args) (hooks/map-node [])]
                       args)]
    {:node m}))
```

So basically all it's doing is returning the map that gets wrapped by `special-map`. Am I doing something really stupid? I would expect it to work, but I keep getting errors like 

```
my_ns.clj:8:50: error: Expected: associative collection or nil, received: string.
```

The problem goes away if I replace the call to `format` with a plain string, **or** if I remove the `assoc` form that wraps the call to `special-map`, **or** if I tweak the hook to wrap the whole thing in a `do` like

```clj
(hooks/list-node
 (list
  (hooks/token-node 'do)
  ...))
```

**repro**

I created a GitHub repro to reproduce this locally 

https://github.com/camsaul/clj-kondo-hook-map-bug-repro

**config**

```clj
{:hooks {:analyze-call {my-ns/special-map hooks.my-ns/special-map}}}
```

**Comment by borkdude** [comment]
I'll try now.
