### ISSUE TITLE
Macroexpand hook with # functions reader macro

### ISSUE THREAD

**Issue by markgdawson** [clj-kondo/clj-kondo#1779]
**version**

I'm running `clj-kondo` 2022.08.03 on the JVM in Linux.

**problem**

I'm used the `macroexpand` hook to expand the [try-let macro](https://github.com/rufoa/try-let). My macro implementation is mostly good enough and is working for me in most cases. But clj-kondo produces errors when there is a function defined by `#(...)` in the expansion of the macro. It seems to me that clj-kondo is failing to recognise reader macro functions when using the macroexpand hook.

**repro**

EDIT: here is a minimal project which this repro in runnable form: https://github.com/markgdawson/clj-kondo-reader-macro-repro.
Run with `clj -M:clj-kondo`.

```clojure
(ns core
  (:require [try-let :refer [try-let]]))

(try-let [a 10]
         #(+ a 2)
         (catch Throwable e e))
```

In this case I get clj-kondo error on this macro saying `unused-binding a`.

For completeness, I use `try-let` in deps.edn as: `try-let/try-let {:mvn/version "1.3.1"}`.

The warning goes away with:
```clojure
(try-let [a 10]
         a
         #(+ a 2)
         (catch Throwable e e))
```
and with
```clojure
(try-let [a 10]
         (fn [] (+ a 2))
         (catch Throwable e e))
```

**config**
./.clj-kondo/configs/try-let/config.edn
```clojure
{:hooks
 {:macroexpand {try-let/try-let clj-kondo.try-let.try-let/try-let}}}
```

./.clj-kondo/configs/try-let/clj_kondo/try_let/try_let.clj
```clojure
(ns clj-kondo.try-let.try-let)

(defn expression-type [body]
  (if (and (seq? body)
           (#{'catch 'finally} (first body)))
    :catches
    :body))

(defmacro try-let
  [bindings & body]
  (let [{:keys [body catches]} (group-by expression-type body)]
    `(try (let [~@bindings] ~@body)
          ~@catches)))
```

**expected behavior**

I expected clj-kondo not to throw errors for valid/correct code expansions which use the `#` function reader macro.

**Comment by borkdude** [comment]
I can see the error here locally too, thanks for making such a good repro.
