### ISSUE TITLE
namespace-name-mismatch on namespaces with '+'

### ISSUE THREAD

**Issue by gianfun** [clj-kondo/clj-kondo#1791]
[ To keep development of this project going, consider sponsoring. If you are
already a sponsor, thank you! ]

**version**

2022.08.03

**macro usage**

[ Is your bug related to macro usage? Consider using a configuration. If not, ignore this section. ]

See [config.md](https://github.com/clj-kondo/clj-kondo/blob/master/doc/config.md#unrecognized-macros) for related configuration options.

**platform**

Running clj-kondo it on the JVM. Directly adding it to `:dependencies` and having an alias for it:
```
"clj-kondo" ["run" "-m" "clj-kondo.main"]
```

**editor**

IntelliJ 2022.1.1 (Community Edition)

**problem**

Namespaces with a plus in them fail the namespace-name-mismatch check

**repro**

1. Create a new project with `lein new app clj-kondo-test`
2. Create a new file `hamburguer+cheese.clj`
3. Run `lein clj-kondo --lint src/clj_kondo_test/hamburguer+cheese.clj`

Output: 
```
src/clj_kondo_test/hamburguer+cheese.clj:1:5: error: Namespace name does not match file name: clj-kondo-test.hamburguer+cheese
linting took 129ms, errors: 1, warnings: 0
```

Expected:
```
linting took 112ms, errors: 0, warnings: 0
```

**config**

[ Is your bug related to `.clj-kondo/config.edn`? Paste your entire
configuration here. Also check if the bug still occurs without using a
configuration, as the bug may be a result of malformed configuration. ]

**expected behavior**

Expected the check to not fail

--------

Taking a look at the code, I realized we use `munge` on the namespace. I also realized that clojure.core has `namespace-munge`, and that replacing the call to `munge` with `namespace-munge` yields the correct behavior.
However, I do not have enough clojure or clj-kondo knowledge to know if this makes sense. `munge` replaces more things than `namespace-munge`, so I am not sure if more things are dependent on this

**Comment by borkdude** [comment]
@gianfun I think you made the right diagnosis, munge should be replaced with namespace-munge. PR welcome, but also fine to leave this for me to fix.
