### ISSUE TITLE
Lint: warn when using fully-qualified keyword or symbol when there is an alias defined for the same namespace

### ISSUE THREAD

**Issue by sheluchin** [clj-kondo/clj-kondo#1800]
To upvote this issue, give it a thumbs up. See [this list](https://github.com/clj-kondo/clj-kondo/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) for the most upvoted issues.

**Describe the solution you'd like**
```clojure
(ns foo
  (:require
    [clojure.string :as str]
    [bar :as-alias b]))

;; show  `alias available` warning for both
(clojure.string/blank? "")
(identity :bar/baz)
```

If there is already an alias defined for a namespace, show a linter warning when using fully qualified keywords/symbols of that same namespace. 

The rationale is that such warnings will help keep code more consistent, easier to grep and refactor, etc.

**Comment by NoahTheDuke** [comment]
The linked PR #1809 has only tackled linting symbols. I will handle linting keywords in a later PR.
