### ISSUE TITLE
Support ignoring unresolved symbols inside of unresolved symbols

### ISSUE THREAD

**Issue by camsaul** [clj-kondo/clj-kondo#1803]
To upvote this issue, give it a thumbs up. See [this list](https://github.com/clj-kondo/clj-kondo/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) for the most upvoted issues.

**Is your feature request related to a problem? Please describe.**

I wanted to write a test expression form like this

```clj
(defn- re-quote [^String s]
  (re-pattern (java.util.regex.Pattern/quote s)))

(defmethod t/assert-expr 'macroexpansion-spec-error? [message [_ error form]]
  (t/assert-expr
   message
   `(~'thrown-with-msg?
     Exception
     ~(re-quote error)
     (try
       (macroexpand (quote ~form))
       (catch clojure.lang.Compiler$CompilerException e#
         (throw (or (ex-cause e#) e#)))))))
```

that I would use to test macroexpansion `fdef` spec validation like this:

```clj
(t/testing "Throw error on invalid args (#36)"
  (t/is (macroexpansion-spec-error?
         "Call to methodical.macros/defmulti did not conform to spec."
         (macros/defmulti multifn :default
           [x y z]
           :ok))))
```

However I could not find a way to please Kondo so I eventually gave up and removed this entirely and wrote everything the hard way.

My main problem is that I'm getting unresolved symbol errors inside `macroexpansion-spec-error?`. I cannot tell Kondo to ignore unresolved symbols inside of it because of #1662.

I've tried everything, but it seems like trying to write a `:lint-as` rule or `:macroexpand` hook doesn't work here since this is an unqualified symbol.

At any rate I would actually like to ignore unresolved symbol errors for `macroexpansion-spec-error?` itself only when it's inside of `clojure.test/is` forms, and then ignore also ignore any unresolved symbols inside of it. Would it be possible to support nesting unresolved symbol ignores, maybe like this:

```clj
{:linters
 {:unresolved-symbol
  {:exclude
   [(clojure.test/is [(macroexpansion-spec-error?)])]}}}
```

**Describe the solution you'd like**

I'd be happy if there was **any** way to make my test expression work without disabling the unresolved symbol linter entirely. 

**Describe alternatives you've considered**

I've tried a `:lint-as` rule, a `:macroexpand` hook, etc. Nothing works since this is an unqualified symbol.

**Comment by borkdude** [comment]
@camsaul This could be a workaround:

```
$ clj
Clojure 1.11.0
user=> (require '[clojure.test :as t])
nil
user=> (defmethod t/assert-expr 'foo/bar [message [_ error form]] (t/assert-expr message `(+ 1 2 3)))
#object[clojure.lang.MultiFn 0x1ded7b14 "clojure.lang.MultiFn@1ded7b14"]
user=> (t/is (foo/bar 1))
6
user=> (require '[my-test-hook :as-alias foo])
nil
user=> (t/is (foo/bar 1)) ;; clj-kondo thinks foo/bar is my-test-hook/bar
6
```

**Comment by borkdude** [comment]
This configuration does work:

```
{:linters
 {:unresolved-symbol
  {:exclude
   [(clojure.test/is [macroexpansion-spec-error?])]}}}
```

This should at least not flag the symbol `macroexpansion-spec-error?`.
