### ISSUE TITLE
Add a linter to warn when a namespace requires itself

### ISSUE THREAD

**Issue by camsaul** [clj-kondo/clj-kondo#1804]
To upvote this issue, give it a thumbs up. See [this list](https://github.com/clj-kondo/clj-kondo/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) for the most upvoted issues.

**Is your feature request related to a problem? Please describe.**

It can cause problems when a namespace references itself, at least in Clojure (`.clj`) files:

```clj
(ns my-namespace.x
  (:require [my-namespace.x :as x]))
```

this can break things that try to build dependency graphs between namespaces and cause compilation issues.

It would be nice to have a linter that could detect and warn about this situation.

**Describe the solution you'd like**

Warning/error when I accidentally do something dumb

**Describe alternatives you've considered**

I have the unused namespaces linter enabled and I don't get a warning if I don't use the alias for the current namespace e.g. `x/` anywhere -- this seems like it might be a bug?

**Comment by borkdude** [comment]
Yes, I think this is a good one.
