### ISSUE TITLE
Add exclude to :used-underscored-binding

### ISSUE THREAD

**Issue by staifa** [clj-kondo/clj-kondo#1842]
[ Leave this text in if you want to promote it. ]

To upvote this issue, give it a thumbs up. See [this list](https://github.com/clj-kondo/clj-kondo/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) for the most upvoted issues.

[ To keep development of this project going, consider sponsoring. If you are
already a sponsor, thank you! You can remove this message. ]

**Is your feature request related to a problem? Please describe.**
We have a naming convention that uses specific prefix starting with `_` in our codebase. It's deeply rooted legacy that would be too painful to get rid of. We'd like to use `:used-underscored-binding` linter though.

**Describe the solution you'd like**
Adding a possibility to exclude both symbols and regexes from `:used-underscored-binding`.

PR coming after opening the issue. I finished coding before I noticed the issue-first policy, sorry!

**Comment by borkdude** [comment]
I'll take a look at the PR soon-ish, thanks
