### ISSUE TITLE
Add linter to check for earmuffs on ^:dynamic vars

### ISSUE THREAD

**Issue by NoahTheDuke** [clj-kondo/clj-kondo#1846]
To upvote this issue, give it a thumbs up. See [this list](https://github.com/clj-kondo/clj-kondo/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) for the most upvoted issues.

**Is your feature request related to a problem? Please describe.**
To borrow the description from [eastwood](https://github.com/jonase/eastwood#non-dynamic-earmuffs):

Vars marked `^:dynamic` should follow the "earmuff" naming convention, and vice versa:
* `(def foo 42)` (OK: non-dynamic, non-earmuffed)
* `(def ^:dynamic foo 42)` (Not OK: dynamic, non-earmuffed)
* `(def *foo* 42)` (Not OK: earmuffed, non-dynamic)
* `(def ^:dynamic *foo* 42)` (OK: dynamic, earmuffed)

**Describe the solution you'd like**
A linter that performs such a check.

**Describe alternatives you've considered**
Doing nothing is always possible. :)

**Additional context**
N/A

I would be willing to write this one.

**Comment by borkdude** [comment]
Yes please!
