### ISSUE TITLE
New opt-in linter for 0 or 1 newlines at the end of all files

### ISSUE THREAD

**Issue by dchelimsky** [clj-kondo/clj-kondo#1852]
To upvote this issue, give it a thumbs up. See [this list](https://github.com/clj-kondo/clj-kondo/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) for the most upvoted issues.

**Is your feature request related to a problem? Please describe.**

Different developers seem to have different habits re: newlines at the end of files, leading to inconsistency.

**Describe the solution you'd like**

A opt-in linter, including an automated fix, with options :off (default - does nothing), 0, or 1

**Describe alternatives you've considered**

* make it opt-out - that would cause a lot of noise, but maybe that's OK? I don't have a strong feeling about this. Others may or may not agree.
* standardize on IDE settings within our organization. Meh.

**Additional context**

**Comment by borkdude** [comment]
Will implement it next release

**Comment by borkdude** [comment]
Can you give some really specific examples of what clj-kondo should lint, given some string documents?

`"foo\n"` - this is pretty normal right?

**Comment by ericdallo** [comment]
I think @dchelimsky meant cases like files that don't have EOL (End of line) at all, github even shows that on PRs, this is the most common discussion between developers AFAICS.

![image](https://github.com/clj-kondo/clj-kondo/assets/7820865/4acaf7d0-36a0-43cb-9b36-2daeb4505aec)

**Comment by borkdude** [comment]
Then why do we need the setting for 1 newline at the end of the file, this is what is recommended commonly?

**Comment by ericdallo** [comment]
I think David thought that some users may preser 0 and others 1 so a option for that, but to me, we could go with a linter for warn the missing EOL only

**Comment by TimoKramer** [comment]
Hi, just chiming in since this might be related. Apart from a linting of a last line in a file one could find it helpful to show blanks and whitespaces that are unnecessary. Two things come to mind: 1. a line with spaces only 2. a line with trailing whitespace. My setup has lua-language-server installed and in my lua file it shows like this:

![image](https://github.com/clj-kondo/clj-kondo/assets/4785848/097cccd9-9e78-49a5-a9bb-a7a226c86990)

I think this is a nice message and would help me keep my files clean.

**Comment by borkdude** [comment]
Since I'm not getting a response from the original poster, I'm bumping this back to medium priority

**Comment by dchelimsky** [comment]
Original poster here! I retired in July and have been focusing on things unrelated to software. Please don't let my absence hang this up for all the up-voters who like the idea!

**Comment by esuomi** [comment]
There's a curious detail to this, I believe enabling this should also respect the possibly present [EditorConfig](https://editorconfig.org/) configuration file as well to avoid pingpong between tools and editors.

**Comment by borkdude** [comment]
Closing this for now. Feel free to open a new issue with a new feature request if something like this is still desired.
