### ISSUE TITLE
discouraged-var doesn't respect `:level :off` when provided from a merged config

### ISSUE THREAD

**Issue by rschmukler** [clj-kondo/clj-kondo#1853]
**version**

```
clj-kondo v2022.10.14
```

**macro usage**

N/A

**platform**

Native (but also applies to JVM)

**editor**

Emacs / CLI

**problem**

The `discouraged-var-usage` linter will not respect the `:level :off` config when it is provided via a merged config (ns-meta, ns group config, or config-in-comment)

**repro**

```clj
(ns repro 
  {:clj-kondo/config {:linters {:discouraged-var {:level :off}}}})
(satisfies? Datafy 5)
```

**config**

```clj
{:linters  {:discouraged-var {clojure.core/satisfies? {:message "Too slow"}}}}
```

**expected behavior**

CLJ kondo should respect the `:level :off` config being merged in.

PR incoming

**Comment by borkdude** [comment]
Thanks for the fix.
