### ISSUE TITLE
definterface methods are not analyzed as var-definitions

### ISSUE THREAD

**Issue by mainej** [clj-kondo/clj-kondo#1879]
**version**

clj-kondo v2022.11.02

**platform**

MacOS 
Graal

**editor**

n/a

**problem**

Methods defined by `definterface` do not have any analysis associated with them. Because of this, clojure-lsp can't navigate from the definition to the implementation (e.g., in a defrecord) with "goto implementations". (Note that even after this is fixed in clj-kondo, clojure-lsp will still need to be updated to support "goto implementations" from definterface methods.)

**repro**

```clojure
(definterface I
  (imethod [x] "An interface method"))

(defrecord R []
  I
  (imethod [_this x] x))

(.imethod (R.) 2)
```

Using the Graal version of the CLI: `clj-kondo v2022.11.02`

```
❯ clj-kondo --config '{:output {:format :edn}, :analysis {:protocol-impls true}}' --lint repro.clj 2>/dev/null | jet --query ':analysis :var-definitions' --colors false
[{:end-row 2,
  :name-end-col 16,
  :name-end-row 1,
  :name-row 1,
  :ns user,
  :name I,
  :defined-by clojure.core/definterface,
  :filename "repro.clj",
  :col 1,
  :name-col 15,
  :end-col 40,
  :row 1}
 {:end-row 6,
  :name-end-col 13,
  :name-end-row 4,
  :name-row 4,
  :ns user,
  :name R,
  :defined-by clojure.core/defrecord,
  :filename "repro.clj",
  :col 1,
  :name-col 12,
  :end-col 26,
  :row 4}
 {:fixed-arities #{0},
  :end-row 6,
  :name-end-col 13,
  :name-end-row 4,
  :name-row 4,
  :ns user,
  :name ->R,
  :defined-by clojure.core/defrecord,
  :filename "repro.clj",
  :col 1,
  :name-col 12,
  :end-col 26,
  :row 4}
 {:fixed-arities #{1},
  :end-row 6,
  :name-end-col 13,
  :name-end-row 4,
  :name-row 4,
  :ns user,
  :name map->R,
  :defined-by clojure.core/defrecord,
  :filename "repro.clj",
  :col 1,
  :name-col 12,
  :end-col 26,
  :row 4}]
```

**expected behavior**

I would expect the above to include a var definition for `imethod`, similar to a method defined by `defprotocol`. It would probably look like this:

```clojure
'{:fixed-arities #{1},
  :end-row 2,
  :name-end-col 12,
  :protocol-ns user,
  :name-end-row 2,
  :name-row 2,
  :ns user,
  :name imethod,
  :defined-by clojure.core/definterface,
  :protocol-name I,
  :filename "repro.clj",
  :col 3,
  :name-col 4,
  :end-col 37,
  :doc "An interface method",
  :row 2}
```

**additional context**

I'm not sure I'll have time to look at this, so anyone else is free to pick it up. I did do a tiny bit of research and noticed that `definterface` is [analyzed as if](https://github.com/clj-kondo/clj-kondo/blob/4bd9cca90b235e9e4553d980644cc41d1614a2e3/src/clj_kondo/impl/analyzer.clj#L2092-L2093) it were a `defrecord` or `deftype`. This surprised me because I think of `definterface` more like `defprotocol`—something that _defines_ methods—than like `defrecord` or `deftype`, something that _implements_ them. I'm not sure that `analyze-defprotocol` could be reused (among other possible differences, the first argument to `defprotocol` methods is always `this`, whereas that's implicit on `defrecord` methods) but perhaps there's overlap.

**Comment by borkdude** [comment]
Related to https://github.com/clj-kondo/clj-kondo/issues/1871

**Comment by borkdude** [comment]
It's a bit of a shortcut, but I'll just treat `definterface` as `defprotocol` for now and will suppress the redefined var warning and then the navigation works.

![definterface-nav](https://user-images.githubusercontent.com/284934/206303343-d8798fa5-4787-4830-801a-3663340acf81.gif)

**Comment by mainej** [comment]
I forgot about this, but now I see it's fixed in clj-kondo and implemented in clojure-lsp—you two are on top of it! Thanks :pray:
