### ISSUE TITLE
Report redundant-do in more locations

### ISSUE THREAD

**Issue by mainej** [clj-kondo/clj-kondo#1880]
**Is your feature request related to a problem? Please describe.**
The `:redundant-do` lint is great. I'd like it to appear in more scenarios.

**Describe the solution you'd like**
I believe that `:redundant-do` could be applied when any of the following is at the top of the callstack, because each establishes an implicit `do`.

* [comment](https://github.com/clojure/clojure/blob/5ffe3833508495ca7c635d47ad7a1c8b820eab76/src/clj/clojure/core.clj#L4741)
* [delay](https://github.com/clojure/clojure/blob/5ffe3833508495ca7c635d47ad7a1c8b820eab76/src/clj/clojure/core.clj#L755) via fn*
* [dosync](https://github.com/clojure/clojure/blob/5ffe3833508495ca7c635d47ad7a1c8b820eab76/src/clj/clojure/core.clj#L5115) via sync
* [dotimes](https://github.com/clojure/clojure/blob/5ffe3833508495ca7c635d47ad7a1c8b820eab76/src/clj/clojure/core.clj#L2741) via when
* [io!](https://github.com/clojure/clojure/blob/5ffe3833508495ca7c635d47ad7a1c8b820eab76/src/clj/clojure/core.clj#L2540) via do
* [letfn](https://github.com/clojure/clojure/blob/5ffe3833508495ca7c635d47ad7a1c8b820eab76/src/clj/clojure/core.clj#L6601) via letfn*
* [locking](https://github.com/clojure/clojure/blob/5ffe3833508495ca7c635d47ad7a1c8b820eab76/src/clj/clojure/core.clj#L1672) via try
* [sync](https://github.com/clojure/clojure/blob/5ffe3833508495ca7c635d47ad7a1c8b820eab76/src/clj/clojure/core.clj#L2526) via fn
* [while](https://github.com/clojure/clojure/blob/5ffe3833508495ca7c635d47ad7a1c8b820eab76/src/clj/clojure/core.clj#L6384) via when
* [with-bindings](https://github.com/clojure/clojure/blob/5ffe3833508495ca7c635d47ad7a1c8b820eab76/src/clj/clojure/core.clj#L2009) via fn
* [with-in-str](https://github.com/clojure/clojure/blob/5ffe3833508495ca7c635d47ad7a1c8b820eab76/src/clj/clojure/core.clj#L4764) via binding
* [with-local-vars](https://github.com/clojure/clojure/blob/5ffe3833508495ca7c635d47ad7a1c8b820eab76/src/clj/clojure/core.clj#L4363) via try
* [with-out-str](https://github.com/clojure/clojure/blob/5ffe3833508495ca7c635d47ad7a1c8b820eab76/src/clj/clojure/core.clj#L4754) via binding

**Describe alternatives you've considered**
No alternatives necessary, just a nice-to-have.

**Additional context**
I've been compiling a similar list of symbols that establish an implicit `do` as research for https://github.com/clojure-lsp/clojure-lsp/issues/210. While doing that I noticed clj-kondo doesn't lint these locations, so I thought I'd report here.

**Comment by sumbach** [comment]
See also:

* #1784 `catch`
* #1785 `finally`
