### ISSUE TITLE
Add possibility to override project config

### ISSUE THREAD

**Issue by staifa** [clj-kondo/clj-kondo#1891]
**Is your feature request related to a problem? Please describe.**
Currently I have no means to override clj-kondo project config (or I wasn't able to find out how). There is a `:config-paths` setting that lets us alter project config, buth the project config takes always precedence when merging. This bugs me for following reasons:

- I'd like to have an editor specific config - for example disabling conjure's log buffer linting is easy, robust and elegant with `:output {:exclude-files ["conjure-log*"]}`
- Our project config is quite benevolent. It's ok to not force certain coding habits/philosophies on others, but I'd like to use as many linters as possible. Brainfarts happen.

**Describe the solution you'd like**
Add possibility to override project config. We would add an `:extra-config-paths` setting to `config.edn`. It would be merged after project config, effectively overrriding it. It would be used the same way as `:config-paths`.

Example:
`{:extra-config-paths ["$XDG_CONFIG_HOME/clj-kondo"]}`

**Describe alternatives you've considered**
Since I'm using `clj-kondo` via `clojure-lsp`, there probably isn't any viable alternative apart from setting the config from `clojure-lsp` itslef.

**Additional context**
I actually created a PR for this on `clojure-lsp` side
https://github.com/clojure-lsp/clojure-lsp/pull/1394
and discussion over the related issue
https://github.com/clojure-lsp/clojure-lsp/issues/1393

I will create a PR if that's ok @borkdude

**Comment by borkdude** [comment]
Sounds good

**Comment by borkdude** [comment]
I've merged support to for the `CLJ_KONDO_EXTRA_CONFIG_DIR` to master. Can you test it there?

**Comment by staifa** [comment]
Sure thing. I'll test it later today.
