### ISSUE TITLE
Linter hook for `defproject`

### ISSUE THREAD

**Issue by sumbach** [clj-kondo/clj-kondo#1892]
I am working on an `:analyze-call` hook to do custom linting of the `(defproject ,,,)` form in my `project.clj` files. I have had some success with the hook itself, but I'm struggling to find a good way to signal clj-kondo to execute the hook when it encounters an unqualified `defproject` symbol.

## Setup

```
;; .clj-kondo/config.edn
{:linters {:leiningen/defproject {:level :error}}}
```

```
;; .clj-kondo/lint_defproject/leiningen/defproject.clj
;; NOTE: This is a silly hook implementation; I'm planning to do more than this, but wanted a simple example just for demonstration purposes
(ns lint-defproject.leiningen.defproject
  (:require [clj-kondo.hooks-api :as api]))

(defn hook [{:keys [node]}]
  (let [[_ _nm version & _kvs] (:children node)]
    (when-not (and (api/string-node? version)
                   (re-matches #"[1-9][0-9]*\..*" (api/sexpr version)))
      (api/reg-finding!
       (assoc (meta version)
              :message "project version must be greater than 1.0.0"
              :type :leiningen/defproject))))
  {:node (api/token-node nil)})
```

```
;; project.clj
(defproject lint-defproject "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.8.0"]])
```

## Workarounds

I have found two ways to "trick" clj-kondo into running this hook for the bare `defproject` symbol:

```
rm -rf .clj-kondo/.cache
clj-kondo --lint "$(lein classpath)" --dependencies --parallel --copy-configs

# refer leiningen.core.project/defproject into user ns
echo "(ns user (:require [leiningen.core.project :refer [defproject]]))" | \
  clj-kondo --config '{:hooks {:analyze-call {leiningen.core.project/defproject lint-defproject.leiningen.defproject/hook}}}' --filename user.clj --lint - --lint project.clj

project.clj:1:29: error: project version must be greater than 1.0.0
linting took 51ms, errors: 1, warnings: 0
```

```
rm -rf .clj-kondo/.cache
clj-kondo --lint "$(lein classpath)" --dependencies --parallel --copy-configs

# declare user/defproject
echo "(ns user)(declare defproject)" | \
  clj-kondo --config '{:hooks {:analyze-call {user/defproject lint-defproject.leiningen.defproject/hook}}}' --filename user.clj --lint - --lint project.clj

project.clj:1:29: error: project version must be greater than 1.0.0
linting took 46ms, errors: 1, warnings: 0
```

While these work from the command line, I'd ideally like to see linter feedback in my editor as well. To make this work, I suspect I would need to get `clj-kondo --lint project.clj` to see `defproject` and run the `user/defproject` or `leiningen.core.project/defproject` hook (without need of the extra `--filename user.clj --lint -` bits).

I am willing to spoil my clj-kondo cache with a `user/defproject` declaration, but it looks like `clj-kondo --lint project.clj` does not make use of the existing cache file for the user namespace (more on this below).

## Alternatives

I have considered editing `project.clj` to use fully-qualified `(leiningen.core.project/defproject ,,,)`, but that doesn't feel like a good trade-off to me.

## Related Issues/PRs

* https://github.com/clj-kondo/clj-kondo/issues/339
* https://github.com/clj-kondo/clj-kondo/issues/515
* https://github.com/clj-kondo/clj-kondo/issues/1167#issuecomment-777386535 (maybe?)
* https://github.com/clj-kondo/clj-kondo/issues/1054#issuecomment-719789463 (maybe?)
* https://github.com/clj-kondo/clj-kondo/issues/1010#issuecomment-699674750 (maybe?)
* https://github.com/clj-kondo/clj-kondo/issues/381
* https://github.com/clj-kondo/clj-kondo/pull/551/files

## Additional Context

I did some more experiments to try to better understand clj-kondo behavior. Here's what I learned:

```
# declare clojure.core/defproject
# does NOT run the hook

rm -rf .clj-kondo/.cache
clj-kondo --lint "$(lein classpath)" --dependencies --parallel --copy-configs

echo "(ns clojure.core)(declare defproject)" | \
clj-kondo --config '{:hooks {:analyze-call {clojure.core/defproject lint-defproject.leiningen.defproject/hook}}}' --filename clojure/core.clj --lint - --lint project.clj

linting took 13ms, errors: 0, warnings: 0
```

```
# switch to mydefproject to avoid default exclusion of unresolved-symbol within user/defproject
cat project.clj | perl -p -e 's/\(defproject /(mydefproject /;' > myproject.clj

rm -rf .clj-kondo/.cache
clj-kondo --lint "$(lein classpath)" --dependencies --parallel --copy-configs

# before
clj-kondo --lint myproject.clj

myproject.clj:1:2: error: Unresolved symbol: mydefproject
myproject.clj:1:15: error: Unresolved symbol: lint-defproject
myproject.clj:6:19: warning: Unresolved namespace org.clojure. Are you missing a require?
linting took 24ms, errors: 2, warnings: 1

# declare user/mydefproject
echo "(ns user)(declare mydefproject)" | clj-kondo --filename user.clj --lint -

linting took 22ms, errors: 0, warnings: 0

# after
# does NOT run the hook
# but DOES appear to resolve defproject as user/mydefproject
clj-kondo --lint myproject.clj

myproject.clj:1:15: error: Unresolved symbol: lint-defproject
myproject.clj:6:19: warning: Unresolved namespace org.clojure. Are you missing a require?
linting took 18ms, errors: 1, warnings: 1

clj-kondo --config '{:hooks {:analyze-call {user/mydefproject lint-defproject.leiningen.defproject/hook}}}' --lint myproject.clj

myproject.clj:1:15: error: Unresolved symbol: lint-defproject
myproject.clj:6:19: warning: Unresolved namespace org.clojure. Are you missing a require?
linting took 16ms, errors: 1, warnings: 1
```

```
# switch to mydefproject to avoid default exclusion of unresolved-symbol within user/defproject
cat project.clj | perl -p -e 's/\(defproject /(mydefproject /;' > myproject.clj

rm -rf .clj-kondo/.cache
clj-kondo --lint "$(lein classpath)" --dependencies --parallel --copy-configs

# before
clj-kondo --lint myproject.clj

myproject.clj:1:2: error: Unresolved symbol: mydefproject
myproject.clj:1:15: error: Unresolved symbol: lint-defproject
myproject.clj:6:19: warning: Unresolved namespace org.clojure. Are you missing a require?
linting took 15ms, errors: 2, warnings: 1

# declare clojure.core/mydefproject
echo "(ns clojure.core)(declare mydefproject)" | clj-kondo --filename clojure/core.clj --lint -

linting took 18ms, errors: 0, warnings: 0

# after
# does NOT run the hook
# but DOES appear to resolve defproject as clojure.core/mydefproject
clj-kondo --lint myproject.clj

myproject.clj:1:15: error: Unresolved symbol: lint-defproject
myproject.clj:6:19: warning: Unresolved namespace org.clojure. Are you missing a require?
linting took 11ms, errors: 1, warnings: 1

clj-kondo --config '{:hooks {:analyze-call {clojure.core/mydefproject lint-defproject.leiningen.defproject/hook}}}' --lint myproject.clj

myproject.clj:1:15: error: Unresolved symbol: lint-defproject
myproject.clj:6:19: warning: Unresolved namespace org.clojure. Are you missing a require?
linting took 11ms, errors: 1, warnings: 1
```

`Unresolved symbol: mydefproject` can be avoided/resolved by installing a `user/mydefproject` or `clojure.core/mydefproject` declaration in the cache. Even after the symbol is resolved, the analyze-call hook for this symbol is not called.

## Conclusions

I can see at least three options, though I'm not sure if any of them are acceptable in clj-kondo (not sure of the complexity of the change or if these could break existing behavior):

- execute hooks for unqualified, but resolved, symbols
    - using the same logic as the unresolved symbol linter, where it looks for the symbol in the current namespace and clojure.core
    - this requires populating a `user/defproject` or `clojure.core/defproject` declaration in my cache, which isn't ideal but seems like a reasonable trade-off
- execute hooks for unqualified symbols, even if unresolved
    - by assuming the symbol refers to a var in the current namespace
    - this seems slightly better since we don't need to populate a fake declaration in the cache
    - but could be confusing if an unqualified symbol legitimately refers to var in clojure.core, for example
- provide some mechanism to configure a symbol to resolve a particular way, or for an unqualified symbol to invoke a particular hook
    - ideally this configuration would live outside the `project.clj` file so it could be put in a shared config.edn file somewhere
    - but a `#_{:clj-kondo/config ,,,}` map within `project.clj` could work as well
    - I don't have a concrete proposal for what either of these could look like; I can work on a proposal, but wanted to discuss the general idea here first.

**Comment by sumbach** [comment]
... or you can tell me to take a hike, @borkdude 😉 It's reasonable to question if this is even in scope for clj-kondo.

I have considered writing a completely separate tool/script to handle `project.clj` linting. The benefits of doing this within clj-kondo are:

- editor integration
- leveraging the existing rewrite-clj parsing handled by clj-kondo
- leveraging the existing error reporting handled by clj-kondo
- ability to lint extra stuff in `project.clj` outside of the `(defproject ,,,)` form

**Comment by borkdude** [comment]
> but I'm struggling to find a good way to signal clj-kondo to execute the hook when it encounters an unqualified defproject symbol

Can you try `user/defproject`?

**Comment by borkdude** [comment]
I think this issue is also related: https://github.com/clj-kondo/clj-kondo/issues/1690

**Comment by sumbach** [comment]
> Can you try `user/defproject`?

I tried, but I've observed that the `user/defproject` hook is executed only if I explicitly `(declare defproject)` as below:

```
echo "(ns user)(declare defproject)" | \
  clj-kondo --config '{:hooks {:analyze-call {user/defproject lint-defproject.leiningen.defproject/hook}}}' --filename user.clj --lint - --lint project.clj
```

I tried splitting this into two commands, first adding `user/defproject` to the cache, then linting `project.clj`, but I observed that this did not run the `user/defproject` hook:

```
# add `user/defproject` to cache
echo "(ns user)(declare defproject)" | clj-kondo --filename user.clj --lint -

# lint `project.clj` (at the command line or via editor integration)
clj-kondo --config '{:hooks {:analyze-call {user/defproject lint-defproject.leiningen.defproject/hook}}}' --lint project.clj
```

This made me curious about both 1) when the cache is used and 2) in what cases a hook is executed for an unqualified symbol.

Regarding point 1, I found that I could use the cache to get unqualified `(mydefproject ,,,)` to resolve as either `user/mydefproject` or `clojure.core/mydefproject` (as evidenced by the lack of an `Unresolved symbol: mydefproject` error).

On point 2, from what I can tell, the corresponding hook is not called.

If I'm understanding the clj-kondo source correctly, it looks like the analysis phase needs to decide which, if any, hook to call for a given symbol (qualified or not) and this doesn't (probably for good reason) look in the cache for what vars might be declared in the current namespace.

The only other idea I could come up with was trying to get `core-sym?` to report true for `defproject` (so it would resolve to and call the hook for `clojure.core/defproject`). It doesn't look like the behavior of this function can be affected by clj-kondo config or cache (and it would be pretty gross to lie to my whole codebase about `clojure.core/defproject` anyways).
