### ISSUE TITLE
The rules need better reference

### ISSUE THREAD

**Issue by kasajian** [clj-kondo/clj-kondo#1895]
**Is your feature request related to a problem? Please describe.**
A better way to reference issues and an explanation.

**Describe the solution you'd like**
When I get a warning on code like this:

    (use 'clojure.java.io)

I get error message:

    use require with alias or :refer

First when the error shows up in VS-Code, there's no reference on where to go to look up why this is a warning.  The warning message doesn't explain why this is a warning.   At a minimum, a link should be included to where the warnings can be looked up.   Preferably, each warning as a unique ID that can be searched.   Even better, a link to a page that contains the warning.

Second thing is, when I look up the warning.   The warning description on the web site shows:

    This linter is closely tied to [Refer All](https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#refer-all). Namespaces configured to suppress the :refer-all warning will also suppress the :use warning.

It refers to "Refer All" but that doesn't explain anything.

So the bottom line is, it's assumed that the person getting the warning fully understands why the recommendation is being made.

I think to make this tool more mature we should adopt conventions used by other static-code analysis rules.   For instance, the C++ Core Guidelines, or C# Roslyn code analyzers.  They have description for each rule:  A reason, an example; how to fix.  typical reasons to disable / exceptions.   The creator of C+, bjarne stroustrup , for instance said that it's not necessary to memorize all the rules - as long as a developer is given enough information as to why the rule exists, what's the best practice, and how to fix it.  

It's basically a way to get new developers to learn the language.    It's about adoption.   This type of an improvement can do wonders for the adoption of Clojure.   In my personal experience, there were features of C# I never used until my IDE started giving me hints on who I can improve my code, and how I can improve it -- with specific instructions, and even code-fixes to do the change for me, inline.   vs-code now has this type of interface, but it's hardly ever used.   

**Describe alternatives you've considered**
Alternative is to Google around - search StackOverflow.   Beg experts on Reddit to explain things.   

**Additional context**
none

[ Optional: if you are interested in doing a PR yourself, please leave a note. ]

**Comment by borkdude** [comment]
@kasajian The way this is solved in clj-kondo is by enabling this:

https://github.com/clj-kondo/clj-kondo/blob/master/doc/config.md#show-linter-name-in-message

This gives you the linter name in the message.

Then you can look up the relevant linter here:

https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md

Which brings you here:

https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#refer-all

I agree that there should be documentation for the _why_ of the linter.

You can find some of that here: https://github.com/bbatsov/clojure-style-guide. The style guide suggests using an alias or an explicit refer over a "wildcard" refer.

Warning about `:refer :all` in clj-kondo is both a style thing but also a reliability thing. I'll give you the reasons here and maybe we can include that in the docs somewhere.

1. Using `:refer :all` makes names in your code ambiguous: for the linter isn't not always clear where things are coming from which can lead to false positives.
2. It can be confusing to see vars that are not explicitly referred, even in documentation. (I certainly have this experience)
3. CLJS doesn't support this feature, so if you want to write standard Clojure that works in more places than the JVM, it's better to avoid it.
4. It can cause bugs. See [this tweet for example](https://twitter.com/borkdude/status/1589951843991683073).

**Comment by kasajian** [comment]
Those reasons sound solid.  The less ambiguity the better.

Thanks for the other suggestions.   The thing that I have to figure out now how kondo is even on my system.  I am simply using Calva in vscode, so it must have gotten pulled in through that.   I don't see any clj-kondo specific configuration files in my project though.   Anyway, it should be easy for me to figure out where to put `'{:output {:linter-name true}}`

Thanks again for the quick response.

**Comment by borkdude** [comment]
That goes into your `$project/.clj-kondo/config.edn` where `$project` is the root of your project, or you can put it in your home directory config: `$HOME/.config/clj-kondo/config.edn`.
