### ISSUE TITLE
Add `:analysis :all` option

### ISSUE THREAD

**Issue by sheluchin** [clj-kondo/clj-kondo#1897]
To upvote this issue, give it a thumbs up. See [this list](https://github.com/clj-kondo/clj-kondo/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) for the most upvoted issues.

**Is your feature request related to a problem? Please describe.**
Some tools which depend on clj-kondo analysis data aim to get as much analysis information as possible, but understanding which [Extra analysis](https://github.com/clj-kondo/clj-kondo/tree/master/analysis#extra-analysis) options are available requires some effort and if the options list grows, the downstream tools need to be updated to use the new options. 

Examples of tools that could benefit from an `:analysis :all` option:
- https://github.com/phronmophobic/dewey/issues/4
- clojure-lsp's `dump` command with [analysis overrides](https://github.com/clojure-lsp/clojure-lsp/issues/1384)

**Describe the solution you'd like**
It would be helpful to have an analysis config option like `:analysis :all` to return all possible analysis data. The list of available data can grow and consumers of the data could receive the expanded map without needing to update any code on their end.

**Describe alternatives you've considered**
The alternative is to read through the docs and construct the comprehensive analysis config yourself, and then watch for newly added options and incorporate them as they come.

I can submit a PR for this feature, but I can't promise exactly when I'll get around to it.

**Comment by borkdude** [comment]
PR welcome

**Comment by phronmophobic** [comment]
I just commented on the mentioned issue in dewey, but the tldr is that I'm less interested in having an `:analysis :all` option, but would be happy to have some way to programmatically inspect what kinds of analysis are available. That would allow me to check if new analyses are available and independently decide when/if to pull them in.

**Comment by sheluchin** [comment]
It's a valid point about reproducibility.

What about having something that can return the available analysis options as an EQL query or something like that?

**Comment by borkdude** [comment]
If I retrieve analysis I'm usually doing this with a specific case in mind. But when just exploring the data when experimenting `:all` may be convenient. You can programmatically then discover the available data by analyzing a sample maybe, although this wouldn't tell you about all available keys if nothing in the analysis hits a relevant piece of code.

**Comment by sheluchin** [comment]
How about putting the config map that `:all` corresponds to in a map that can be inspected to get its explicit meaning? It could fulfill the desire for a convenient `:all` option, would allow for inspection, and would serve as a bit of documentation. Maybe Dewey could publish the complete analysis config along with the dump artifacts to support reproducibility?

**Comment by borkdude** [comment]
@sheluchin That's an interesting idea. We could just expose a var that is the config to get all the analysis, so you can also inspect that map in the REPL locally.

**Comment by phronmophobic** [comment]
```
Maybe Dewey could publish the complete analysis config along with the dump artifacts to support reproducibility?
```

I like that idea!
