### ISSUE TITLE
Treat quoted forms as code for analysis, without emitting lint warnings

### ISSUE THREAD

**Issue by borkdude** [clj-kondo/clj-kondo#1902]
When quoting a form like `'(fn [x] (inc x))` one would like to navigate to the clojure.core/inc var and from the local usage `x` to the local definition of `x`. So far clj-kondo has treated quoted forms as just a random blob of data. To enable navigation, renaming etc. for clojure-lsp, clj-kondo has to perform code analysis on the quoted form instead.

- Only do this when analysis is true: it has no benefit for linting purposes?
- Add extra `:quote true` in analysis? We could do without and see if this has adverse affects on clojure-lsp and add it if necessary

Having code analysis happen in edn would also make lsp work better for babashka tasks (still no linting there but something)
And deps.edn: `exec-fn` 

There are also cases like `(requiring-resolve 'clojure.set/union)` that won't be helped by this. When treating `clojure.set/union` as a normal piece of code, clj-kondo normally emits an `Unresolved namespace: clojure.set` warning. But because warnings are suppressed in quoted forms, you would see nothing, neither in the analysis output. This is something to address as well.

**Comment by ericdallo** [comment]
probably adding `:quote true` would be a good idea, as not sure we want to show references and things like that for quoted code, maybe we only want to add find definition support on lsp

**Comment by borkdude** [comment]
@ericdallo I'm working on getting quoted symbols (like the first argument in `(requiring-resolve 'clojure.set/union)`) and symbols in edn into the analysis.

A demo here: https://twitter.com/borkdude/status/1612773780589355008

It works now because I emit `:var-usages` for those symbols, but ... this isn't always accurate. E.g. `org.clojure/clojure` isn't a var reference, but a dependency... so I'm leaning towards a separate `:symbols` bucket again, which will contain similar entries as `:var-usages` but as an opt-in bucket and one should treat this as "may be a reference or not, do whatever you need with it". Initially I'll also only add namespaced symbols to this.

**Comment by ericdallo** [comment]
It will need a extra work on LSP side to support that but I understand the point of having var-usages that are not really var usages, so I think it's ok

**Comment by borkdude** [comment]
@ericdallo See `:symbols` docs here: https://github.com/clj-kondo/clj-kondo/blob/master/analysis/README.md

Let me know if you need any help with integrating in clojure-lsp.

**Comment by borkdude** [comment]
I'm working on a PR for clojure-lsp

**Comment by borkdude** [comment]
PR is up
