### ISSUE TITLE
Can't run latest clj-kondo version in GH actions - GLIBC_2.32 not found

### ISSUE THREAD

**Issue by khmelevskii** [clj-kondo/clj-kondo#1909]
I can see the following problem
```
clj-kondo: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32\' not found (required by clj-kondo)\nclj-kondo: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34\' not found (required by clj-kondo)\n
```
Run on `ubuntu-22.04`

**Comment by borkdude** [comment]
@khmelevskii I'm aware of this problem but I need more details. How are you installing clj-kondo? If you've done this via the installer script, it should work now. If you've done this manually, please use the linux static binary.

**Comment by borkdude** [comment]
We can probably fix this by using `cimg/clojure@sha256:8298383d7753a2305663403871c31f238c3c5f0200e13f2394e32d4598a9fdf2` in the builds instead of a tagged image without a SHA. This was the image used in the previous release when this still worked.

/cc @lispyclouds

**Comment by borkdude** [comment]
Will do another release. Hang on.

**Comment by borkdude** [comment]
Can you try again?

**Comment by khmelevskii** [comment]
Thank you @borkdude. Now it works perfectly!

**Comment by khmelevskii** [comment]
I've just tried to build such container
```
FROM cljkondo/clj-kondo:latest AS binary

FROM node:10-slim

COPY lib /action/lib
COPY --from=binary /usr/local/bin/clj-kondo /usr/local/bin/clj-kondo
ENTRYPOINT ["/action/lib/entrypoint.sh"]
```
Now it work
