### ISSUE TITLE
Encourage idiomatic closure definition

### ISSUE THREAD

**Issue by andreyorst** [clj-kondo/clj-kondo#1920]
I've seen some examples of misuse of `def` + `let` + `fn` combinations like this one:

```clojure
(def add-three
  "Function that adds three to the given number"
  (let [x 3]
    (fn [y] (+ x y))))
```

Which can be written in a more idiomatic way:

```clojure
(let [x 3]
  (defn add-three 
    "Function that adds three to the given number"
    [y]
    (+ x y)))
```

This has the additional benefit of providing useful metadata with the function name, such as function arglist.

## Solution 1

I've made a hook, that I've included in my local config, and I've thought that this can be one of the default linting rules for clj-kondo, as the code is more concise with `let` + `defn`:

```clojure
(ns hooks.def-let-fn
  (:require [clj-kondo.hooks-api :as api]))

(defn def-let-fn [{:keys [node]}]
  (let [body (rest (:children node))]
    (when-let [[name docstring body]
               (cond (= 3 (count body)) body
                     (= 2 (count body)) [(first body) nil (last body)]
                     :else nil)]
      (when (and (api/list-node? body)
                 (= 'let (first (api/sexpr body))))
        (let [[bindings body] (rest (:children body))]
          (when (and (api/list-node? body)
                     (= 'fn (first (api/sexpr body))))
            (api/reg-finding!
             (assoc (meta (first (:children body)))
                    :message
                    (format "consider using 'defn' inside 'let' instead of 'fn' inside 'let' inside 'def': (let %s %s)"
                            (api/sexpr bindings)
                            (list* 'defn
                                   (api/sexpr name)
                                   (if docstring
                                     (list* (api/sexpr docstring) (rest (api/sexpr body)))
                                     (rest (api/sexpr body)))))
                    :type :hook))))))))
```

It works, and even suggests the corrected variant, that you can copy from the message, only requiring you to reformat the code afterward.

## Solution 2

I can, of course, keep it as a local hook, or propose its inclusion into the [configs](https://github.com/clj-kondo/configs) project, but I think it would be better as a default rule.

I'm not sure how built-in checks are implemented, but I'm willing to try adding this myself if it is in the scope of the project.

Thanks!

**Comment by borkdude** [comment]
It would be interesting to collect some data on how often this occurs in code bases.
I think https://github.com/borkdude/grasp could be used to detect some libraries that are doing the first pattern, where the second pattern should be preferred.

**Comment by borkdude** [comment]
Also "misuse" and "more idiomatic": I think these are strong words that need some justification on why that is the case (not for me, but just for anyone that you want to convince to use the second style).

**Comment by andreyorst** [comment]
> Also "misuse" and "more idiomatic": I think these are strong words that need some justification on why that is the case (not for me, but just for anyone that you want to convince to use the second style).

I agree on the strong words. English is not my first language, so perhaps this may have sounded harsher than I really meant.

Though, I think the benefit of the arglist metadata is already a pretty good point.

Another one is that the name is not mangled in stack traces if the exception occurs in it or other functions called from such a function.

**Comment by borkdude** [comment]
Good points

**Comment by borkdude** [comment]
I have the feeling that this pattern should also cover `(def x (fn [] ..)` right? `:top-level-fn` as the name or so? (maybe a less confusing name?)

**Comment by andreyorst** [comment]
Updated the hook to support `(def x (fn [] ..))`:

```clojure
(ns hooks.def-let-fn
  (:require
   [clj-kondo.hooks-api
    :refer [list-node? sexpr reg-finding!]]))

(defn def-let-fn [{:keys [node]}]
  (let [body (rest (:children node))]
    (when-let [[name docstring body]
               (cond (= 3 (count body)) body
                     (= 2 (count body)) [(first body) nil (last body)]
                     :else nil)]
      (condp = (and (list-node? body)
                    (first (sexpr body)))
        'let
        (do (println :vaiv)
            (let [[_ bindings body] (:children body)]
              (when (and (list-node? body)
                         (= 'fn (first (sexpr body))))
                (reg-finding!
                 (assoc (-> body :children first meta)
                        :message
                        (format "consider using 'defn' inside 'let' instead of 'fn' inside 'let' inside 'def': (let %s %s)"
                                (sexpr bindings)
                                (list* 'defn
                                       (sexpr name)
                                       (if docstring
                                         (list* (sexpr docstring) (rest (sexpr body)))
                                         (rest (sexpr body)))))
                        :type ::def-closure)))))
        'fn
        (reg-finding!
         (assoc (-> body :children first meta)
                :message
                (format "consider using 'defn' instead of 'fn' inside 'def': %s"
                        (list* 'defn
                               (sexpr name)
                               (if docstring
                                 (list* (sexpr docstring) (rest (sexpr body)))
                                 (rest (sexpr body)))))
                :type ::def-fn))
        nil))))
```

**Comment by borkdude** [comment]
@andreyorst I'm open to a pull request to have this in clj-kondo. Suggested linter name, still thinking about this but let's go for `:def-fn` as the temporary name.

It's quite easy and cheap to implement using the `:callstack` in the `ctx`. Just look upwards for calls to `clojure.core/def` or `cljs.core/def` in `analyze-fn`. There is also `top-level?` key in there, that might be useful.
If we see that def has been called, and there is no `defn` in between, we know that we have `(def x (fn []))` type thing. Of course there is a let allowed in between as well.

To understand better what I mean, just print `(-> ctx :callstack)` inside `analyze-fn`.

We need tests to test that `(def x [(fn [])])` etc. do not trigger this behavior.

**Comment by sumbach** [comment]
I haven't looked deeply enough yet to offer an explanation, but I'm seeing `:def-fn` reporting on `reify` within `def`:

```
$ clj-kondo --version
clj-kondo v2023.02.17

$ clj-kondo --config '{:linters {:def-fn {:level :warning}}}' --lint - <<< '(def thing (reify Object (toString [_] "thing")))'
<stdin>:1:26: warning: Use defn instead of def + fn
linting took 69ms, errors: 0, warnings: 1
```

I have a legitimate instance like this in my codebase `(def xpath-function-resolver (reify javax.xml.xpath.XPathFunctionResolver ,,,))`. I know I can `:clj-kondo/ignore` this var, but this might be a legitimate `:def-fn` false positive.

Is there a better/more idiomatic way to write def + reify? Would you like me to open a separate GitHub issue to track this?

**Comment by sumbach** [comment]
Potential culprit here: https://github.com/clj-kondo/clj-kondo/blob/f1b13914ee192953f1ef/src/clj_kondo/impl/analyzer.clj#L1442-L1444

```
;; ... (foo [x y z]) is linted as (fn [x y z])
```

**Comment by borkdude** [comment]
@sumbach Isssue (+ optionally fix, happy to guide you) welcome.
