### ISSUE TITLE
Add check in deps.edn: exclusions should be vector (or list) of symbols

### ISSUE THREAD

**Issue by ont-app** [clj-kondo/clj-kondo#1928]
To upvote this issue, give it a thumbs up. See [this list](https://github.com/clj-kondo/clj-kondo/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) for the most upvoted issues.

**Is your feature request related to a problem? Please describe.**
I made a silly mistake in formatting my deps.edn file and got a cryptic stack trace that took a while to track down.

**Describe the solution you'd like**

Calling kondo with `--lint deps.edn` would match the contents of the file against [the spec](https://github.com/clojure/tools.deps/blob/master/src/main/clojure/clojure/tools/deps/specs.clj).

**Comment by borkdude** [comment]
- If there is a spec, how come you didn't discover it via clojure.spec?
- Can you give the concrete example that took a while to track down, to give that more priority?

**Comment by ont-app** [comment]
Good point!

This was easy enough to add to my build.clj:

```
(defn validate-deps
  "Throws an `ex-info` of type `::invalid-deps`, or returns `opts` unchanged"
  [opts]
  (println "Validating deps.edn...")
  (let [deps (-> "deps.edn" (slurp) (read-string))
        ]
    (when (not (spec/valid? ::deps-specs/deps-map deps))
      (throw (ex-info "Invalid deps.edn"
                        {:type ::invalid-deps.edn
                         :problem (-> (spec/explain-data ::deps-specs/deps-map deps)
                                      ::spec/problems
                                      )
                         })))
    (println "deps.edn conforms to clojure.tools.deps.specs")
    opts))
```
That's probably a better approach. I guess I withdraw the suggestion.

To answer your question, this silly mistake:

```
{:deps {<library> {:mvn/version ... :exclusions [[nested-too-deep]]}, ...}...}
```
Resulted in a stack trace associated with this error message when I tried to build the uberjar in my build.clj, adapted from Sean's script:

```
"Execution error (ClassCastException) at clojure.tools.build.tasks.write-pom/to-dep$fn (write_pom.clj:44).\nclass clojure.lang.PersistentVector cannot be cast to class clojure.lang.Named (clojure.lang.PersistentVector and clojure.lang.Named are in unnamed module of loader 'app')\n"
```

**Comment by borkdude** [comment]
It's still useful to have additional checks in clj-kondo. It already checks a few things in deps.edn, so I'll interpret this request to check if exclusions is a vector of symbols.
