### ISSUE TITLE
Incorrect work with function argument constraints

### ISSUE THREAD

**Issue by makarichevss** [clj-kondo/clj-kondo#1929]
**version**

v2022.12.10

**macro usage**

no macros

**platform**

I use clj-kondo installed in Cursive, 1.12.6-2022.3.
But in the native version (in VS Code, v2022.12.10) the error is the same.

**problem**

Hi!
Looks like some styles of function argument constrains are not processed by clj-kondo properly.
This style is valid and recognized correctly:
```
(defn constrained–fn [f x]
  {:pre  [(pos? x)]
   :post [(= % (* 2 x))]}
  (f x))
```

This one is valid too, but kondo can't fully recognize it:
```
(defn name3 ^{:pre  [(pos? z)]
              :post [(> % 10) (< % 20)]}
  [z]
  z)
```

![2022-12-24_152902](https://user-images.githubusercontent.com/62963044/209436636-348485c5-b340-4020-a886-17398cde87d6.jpg)

![2022-12-24_153943](https://user-images.githubusercontent.com/62963044/209436673-c46f4464-a361-4367-b227-fb41735deea8.jpg)

Please teach kondo that the last code is valid too.

**Comment by borkdude** [comment]
I wasn't aware of the metadata notation. Thanks. Why not use the other notation though?

**Comment by makarichevss** [comment]
I think metadata is a bit faster recognizable for me (for now).
Saw that notation in one 8-years old Clojure course and was surprised that kondo is still unaware of it.

**Comment by borkdude** [comment]
I think kondo is unaware because most people don't use it like this :)

**Comment by borkdude** [comment]
Some evidence for this:

A lot of hits (1600) on grep.app for `{:pre `, but just one for `^{:pre `:

https://grep.app/search?q=%7B%3Apre%20&filter[lang][0]=Clojure

**Comment by makarichevss** [comment]
tonsky was the second one))

![2022-12-24_171022](https://user-images.githubusercontent.com/62963044/209439461-308ff6ad-3834-48d1-8eb0-7640df3c7f0e.jpg)
