### ISSUE TITLE
Differing behavior when hooking on clojure.core/new depending on whether callsite uses (new Foo) or (Foo.) syntax

### ISSUE THREAD

**Issue by nathanmarz** [clj-kondo/clj-kondo#1944]
Version v2021.07.28 running on JVM via `lein clj-kondo`

Hooks on `clojure.core/new` receive different input whether a callsite uses `(new Foo)` or `(Foo.)` syntax. The former receives metadata on the node that contains line numbers, while the latter has no metadata. I believe the lack of metadata also causes `:clj-kondo/ignore` to not work since we're unable to provide line numbers when calling `reg-finding!`.

**Comment by borkdude** [comment]
So the expectation is that they work the same and both have metadata - right?

**Comment by nathanmarz** [comment]
Yes

**Comment by borkdude** [comment]
I found an (unrelated) regression in which every time a hook was used the SCI namespace was reloaded. I'm releasing a new version now: 2023.01.16

**Comment by borkdude** [comment]
Done releasing
