### ISSUE TITLE
analyzer ignores code inside syntax-quote

### ISSUE THREAD

**Issue by sritchie** [clj-kondo/clj-kondo#1971]
This form triggers “redundant-fn-wrapper” on clj-kondo v2022.12.08:

```clj
(let [nsm {}]
     (fn [sym]
       `(.println
         (RT/errPrintWriter)
         ~(nsm sym))))
```

From @borkdude in [Clojurians Slack](https://clojurians.slack.com/archives/CHY97NXE2/p1674332705266199?thread_ts=1674326706.620039&cid=CHY97NXE2):

> "I think the issue may be that only the code in the unquote is analyzed and the redundant-fn-wrapper isn't aware of the syntax-quote in between."

**Comment by borkdude** [comment]
cc @NoahTheDuke
