### ISSUE TITLE
Add support for `:arglists` when analyzing signature, and special case `defn-` to use `defn`'s arglist.

### ISSUE THREAD

**Issue by didibus** [clj-kondo/clj-kondo#1977]
To upvote this issue, give it a thumbs up. See [this list](https://github.com/clj-kondo/clj-kondo/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) for the most upvoted issues.

**Is your feature request related to a problem? Please describe.**

There are many core functions/macros that are defined using `def`, and they have an explicit `:arglists` meta attached to list their arguments, such as `defn` and `conj`:

```
(def
 ^{:arglists '([] [coll] [coll x] [coll x & xs])
   :doc "conj[oin]. Returns a new collection with the xs
    'added'. (conj nil item) returns (item).
    (conj coll) returns coll. (conj) returns [].
    The 'addition' may happen at different 'places' depending
    on the concrete type."
   :added "1.0"
   :static true}
 conj (fn ...))
```

For these methods, the signature reported by clj-kondo is empty, so in clojure-lsp for example, we don't see any list of arguments for these core functions.

Also, the signature for `defn-` is: `([name & decls])`, which is the correct signature as per the source of `defn-`, but it's also not an ideal signature, and it would be better if it was more detailed, such as the `:arglists` specified by `defn`: `([name doc-string? attr-map? [params*] prepost-map? body])`

**Describe the solution you'd like**

It would be nice for clj-kondo to take into account `:arglists` meta, or be able to capture the arg lists from the `fn` inside a `def` or both, so that methods defined as: `(def name (fn ...)` would also show proper argument lists.

It would also be nice for `defn-` to not show the argument list it has, which is not very detailed, but display the arg lists as define by `defn`, which is much more useful.

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by ericdallo** [comment]
Yes, I think it's enough for clojure-lsp, we should open a issue on clojure-lsp to check arglists meta indeed, feel free to open @didibus

**Comment by ericdallo** [comment]
https://github.com/clojure-lsp/clojure-lsp/issues/1504
