### ISSUE TITLE
Specify minimum clj-kondo version in config.edn

### ISSUE THREAD

**Issue by ingesolvoll** [clj-kondo/clj-kondo#1990]
To upvote this issue, give it a thumbs up. See [this list](https://github.com/clj-kondo/clj-kondo/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) for the most upvoted issues.

Many of our devs rarely update their clj-kondo client. When our config starts employing more recent features, the older clients start to emit warnings that do not make sense to those devs. This has led to some fatigue for clj-kondo, where linter warnings are not taken seriously.

If possible, specifying a `min-version` in the config edn would be nice. Getting a warning about your outdated client will make it clear enough that you need to act on it.

**Comment by borkdude** [comment]
In the style of `:min-lein-version` and `:min-bb-version` I think `:min-clj-kondo-version` would be good.

**Comment by snasphysicist** [comment]
Hi @borkdude , I would like to make a PR to implement this feature. I think I've worked out most of what I need to achieve it, including tests.

However, I am not sure whether the minimum version warning should be returned in the output from `core/run!` and then printed by `core/print!`, or whether the warning can simply be printed to `*err*`. In the former case I guess some a new key should be added to the map which `run!` returns - perhaps `:warnings` or  `:messages`?

Also, do you think it's necessary to account for `alpha`/`SNAPSHOT` versions, or is it okay to assume the release version will always have format `yyyy.MM.dd`?

Thanks!

**Comment by borkdude** [comment]
@snasphysicist I think it would be quite natural to emit this warning as part of `:findings` and enable this linter by default
