### ISSUE TITLE
def-catch-all doesn't emit locations

### ISSUE THREAD

**Issue by borkdude** [clj-kondo/clj-kondo#1995]
See https://github.com/clj-kondo/clj-kondo/discussions/1994

**Comment by netdrilling** [comment]
Well, given how quickly and confidently you responded I can only assume the problem persisting is on me not knowing how to install kondo from source. It's been a journey through the recesses of my tooling. 

I cloned master and built using script/compile, then moved the binary into /usr/local/bin, 
```
clj-kondo --version
clj-kondo v2023.01.21-SNAPSHOT
which clj-kondo
/usr/local/bin/clj-kondo
```

I deleted my .clj-kondo/lsp/cpcache directories and opened up a project after adding the def-catch-all lint back to the config.edn, I got no change in behavior.

I made an attempt to try to force clojure-lsp to use the jar file that was created from the most recent commit on master by including this in my use-package declaration for lsp-mode
:custom
`  ((lsp-clojure-server-command '("java" "-jar" "/home/pat/bin/clj-kondo/target/clj-kondo-2023.01.21-SNAPSHOT.jar")))`
That made lsp-mode have a conniption.

I also attempted to include the most recent commit in my project by adding kondo as a dev dependency, though I couldn't figure out how to make emacs pick it up. Or do I even need t?
io.github.clj-kondo/clj-kondo {:git/sha  "d7464b7b9d57186e779318f2c523d8dacdc2f38b"} 

At this point I imagine I've missed the boat somewhere. I appreciate you getting on this so quick, and wanted to tell you thanks I'm autocompleting and refactoring like a pro, but I can't. I'm lacking some sort of knowledge that isn't available or I missed in the docs.

**Comment by borkdude** [comment]
@netdrilling I use this script to start a development version of clojure-lsp:

```
#!/usr/bin/env bash

clj -Sdeps '{:deps {clj-kondo/clj-kondo {:local/root "/Users/borkdude/dev/clj-kondo"}
                    clojure-lsp/clojure-lsp {:local/root "/Users/borkdude/dev/clojure-lsp/cli"}
                    cider/cider-nrepl {:mvn/version "0.28.6"}}}' -M -m clojure-lsp.main
```

The `:local/root` dependencies are local checkouts of clojure-lsp and clj-kondo but you can refer to them as git dependencies with `:git/url ...` and `:git/sha`.

Don't use `io.github.clj-kondo/clj-kondo` as the library name since you will have two different versions of clj-kondo on the classpath and you won't know which one will win. Always use `clj-kondo/clj-kondo` and then `:mvn/version` or `:git/url` + `:git/sha`.

**Comment by netdrilling** [comment]
Much appreciated. I've got the custom server running proper from local checkouts I've put the libs in my bin just like you. They're all on the most recent commits. I'm fairly confident that I've got this setup right, because your instructions were easy to follow. I'm still getting the exact same behavior. Linting good, completion/references missing. I tried referencing the local checkout of Kondo from within bin/clojure-lsp/lib/deps.edn but that didn't help. The only thing I can think of is maybe one of my deps needs an exclusion??? I'm at a loss. At this point I hope I'm not exhausting either of our patience. Here is what should be on my classpath.

clj -Sdeps '{:deps {clj-kondo/clj-kondo {:local/root "/home/pat/bin/clj-kondo"}
                    clojure-lsp/clojure-lsp {:local/root "/home/pat/bin/clojure-lsp/cli"}
                    cider/cider-nrepl {:mvn/version "0.30.0"}}}' -M -m clojure-lsp.main


`:aliases {:dev {:extra-paths ["src/clojure/dev"]
                 :extra-deps {nrepl/nrepl {:mvn/version "1.1.0-alpha1"}
                              cider/cider-nrepl {:mvn/version "0.30.0"}
                              clj-kondo/clj-kondo {:local/root "/home/pat/bin/clj-kondo"}
                              refactor-nrepl/refactor-nrepl {:mvn/version "3.6.0"}
                              mx.cider/tools.deps.enrich-classpath {:mvn/version "1.9.0"}}
                 :main-opts  ["-m" "nrepl.cmdline" "--middleware"
                              "[refactor-nrepl.middleware/wrap-refactor,cider.nrepl/cider-middleware]"]}
           :test {:extra-paths ["test/clojure/main"]
                  :main-opts ["-m" "kaocha.runner"]
                  :extra-deps {lambdaisland/kaocha {:mvn/version "1.77.1236"}}}}}
`

Here I am. I don't want completion as much as I don't want to fail in this seemingly simple task. Especially since you took your time out to help me along. Thoughts?

**Comment by borkdude** [comment]
I'll make a new release today and then @ericdallo could maybe bump it so you can download the nightly release.

**Comment by borkdude** [comment]
I'm not sure what the `:aliases` snippet is here?

**Comment by netdrilling** [comment]
The aliases are in the deps.edn map that are at the project level I currently use to connect to for editing. Years past things went bonkers when you started a repl outside of cider and connected to it with cider having mis-matched versions of things. It's a stretch, but I thought it might be the source of my misfortune. Cheers.

**Comment by borkdude** [comment]
The script I listed above should go in some kind of directory that is unrelated to your project, e.g. ~/bin. Then you set emacs to pick up on that script as the clojure-lsp command. The `:aliases` in your project are unrelated, but it might good to try _using_ lsp in an empty project and just do what I did above.

**Comment by netdrilling** [comment]
Yes, that is as figured. I even tried doing a cider jack-in on the troubleshooting repro repo you verified working yesterday. No dice. I don't know why I added the extra info... Desperation I suppose.

**Comment by borkdude** [comment]
cider-jack-in should not be relevant at all here since clj-kondo/lsp are only doing static analysis
