### ISSUE TITLE
Linting with latest release throws error: "Unresolved symbol: Exception" when file uses .cljc extension

### ISSUE THREAD

**Issue by edporras** [clj-kondo/clj-kondo#2000]
**version**

v2023.02.17

**platform**

clojure deps.edn

**problem**

Linting fails with an "Unresolved symbol: Exception" error when using exceptions in a file with the .cljc extension with the latest release

**repro**

Given the file `src/kondo_bug/core.clj` with the following content:

```clojure
; cat src/kondo_bug/core.cljc
(ns kondo-bug.core)

(defn i-throw []
  (throw (Exception. "I'm throwing")))
```

and deps.edn configured to use the "`LATEST`" version of clj-kondo:

```clojure
; cat deps.edn
{:paths ["src"]
 :deps {org.clojure/clojure                 {:mvn/version "1.11.1"}}

 :aliases
 {:clj-kondo/lint
  {:replace-deps {clj-kondo/clj-kondo {:mvn/version "LATEST"}}
   :main-opts ["-m" "clj-kondo.main" "--lint" "src"]}}}
```

linting errors out, breaking CI/CD integration in our gitlab repo. To be sure it's not a cache issue, I'll clear it at every step:

```sh
; rm -rf .cpcache .clj-kondo/.cache
; clojure -M:clj-kondo/lint
src/kondo_bug/core.cljc:4:11: error: Unresolved symbol: Exception
linting took 50ms, errors: 1, warnings: 0
```

If we rename the file to use a .clj extension, it succeeds:

```sh
; mv src/kondo_bug/core.cljc src/kondo_bug/core.clj
; rm -rf .cpcache .clj-kondo/.cache
; clojure -M:clj-kondo/lint
linting took 51ms, errors: 0, warnings: 0
```

If we revert it back, it shows the error:

```sh
; mv src/kondo_bug/core.clj src/kondo_bug/core.cljc
; rm -rf .cpcache .clj-kondo/.cache
; clojure -M:clj-kondo/lint
src/kondo_bug/core.cljc:4:11: error: Unresolved symbol: Exception
linting took 61ms, errors: 1, warnings: 0
```

BUT, if we update deps.edn to force clj-kondo's version to the previous release (`"2023.01.20"`), the error does not happen:

```sh
; cat deps.edn | grep replace-deps
  {:replace-deps {clj-kondo/clj-kondo {:mvn/version "2023.01.20"}}
; rm -rf .cpcache .clj-kondo/.cache
; clojure -M:clj-kondo/lint
linting took 56ms, errors: 0, warnings: 0
```

Attached is a gzipped tar with the project used to show the example above.

**config**

Config file is empty (`{}`)

**expected behavior**

It should behave like the previous version and not report an unresolved symbol.

[kondo-issue-w-cljc-exceptions.tar.gz](https://github.com/clj-kondo/clj-kondo/files/10804304/kondo-issue-w-cljc-exceptions.tar.gz)

**Comment by borkdude** [comment]
`Exception` isn't a valid thing in CLJS, this is why it complains in a `.cljc` file. This was always the case.

**Comment by edporras** [comment]
ack, I'm sorry, I've been working on the package but I only use it on the backend and it didn't even occur to me as it never complained until the new release. Sorry for wasting your time. I'll close the issue.
