### ISSUE TITLE
Linter for vars that differ only in case

### ISSUE THREAD

**Issue by emlyn** [clj-kondo/clj-kondo#2006]
If you (or one of your dependencies) have two vars that differ only in case (e.g. an example I ran into recently: [clojure2d.color/to-lch](https://github.com/Clojure2D/clojure2d/blob/c34b435ef86941c8121dc4802e0ccbc0a6ce949f/src/clojure2d/color.clj#L903) and [clojure2d.color/to-LCH](https://github.com/Clojure2D/clojure2d/blob/c34b435ef86941c8121dc4802e0ccbc0a6ce949f/src/clojure2d/color.clj#L1761)), building an uberjar will fail on case insensitive filesystems, because one class file will overwrite the other.

It would be good to have a linter that detected this.

I'd be happy to write a PR for this, but might need a couple of pointers to get started.

**Comment by borkdude** [comment]
@emlyn Thank you for the issue. This can indeed be a problem and not only in Clojure, but even in Java. A linter for this would be good.

I think the place to look at would be the `reg-var!` function in `clj-kondo.impl.namespace`
There we have the information about which vars were defined before so we can check it immediately.

PR welcome.
