### ISSUE TITLE
Using reader tag in :macroexpansion hook results in unresolved read-string symbol in CLJS

### ISSUE THREAD

**Issue by borkdude** [clj-kondo/clj-kondo#2007]
Repro:

Make a `:macroexpand` hook then use `#foo [1 2 3]` in the body of a call.

This expands into something like `(read-string #foo [1 2 3])` in the expansion due to how rewrite-clj s-expresses reader-tag nodes.
But `read-string` (unresolved even) does not exist in CLJS. Is this something that should be changed in rewrite-clj?

A workaround is to add `(declare ~'read-string)` in the macro, for example:

``` clojure
(ns dispacio.alpha.core)

(defmacro defp [sym pred arg-vec & body]
  `(do (declare ~sym)
       (declare ~'read-string)
       (defmethod ~sym ~pred ~arg-vec ~@body)))
```

Probably an even better workaround:

``` clojure
{:hooks {:macroexpand {dispacio.alpha.core/defp dispacio.alpha.core/defp}}
 :config-in-call {dispacio.alpha.core/defp {:linters {:unresolved-symbol {:exclude [read-string]}}}}}
```

cc @lread

**Comment by lread** [comment]
Yes, interesting.

I did take [some notes on this](https://github.com/clj-commons/rewrite-clj/blob/main/doc/01-user-guide.adoc#reader-macro-chars) a long while back:

> I think it was a design decision of rewrite-clj v0 to return `(read-string ...)` for reader macros it did not want to deal with (or deal with yet). Rewrite-clj v1 will carry on.
> - It seems the idea might have been that the caller could eval the sexpr result if they wanted to?
> - Note for ClojureScript users, `read-string` is not available under `cljs.core`, but a version is available under `cljs.tools.reader`.

Also applies to, according to my notes, `#inst` `#uuid` `#?` `#@?` `#foo/bar`

**Comment by borkdude** [comment]
I think when emitting such things, one should always (or almost always) use a fully qualified symbol

**Comment by borkdude** [comment]
@lread It would maybe be better if rewrite-clj supported the round-trip better:

``` clojure
user=> (require '[rewrite-clj.parser :as p] '[rewrite-clj.node :as n])
nil
user=> (p/parse-string "#foo [1 2 3]")
<reader-macro: #foo [1 2 3]>
user=> (n/sexpr (p/parse-string "#foo [1 2 3]"))
(read-string "#foo [1 2 3]")
user=> (n/coerce (n/sexpr (p/parse-string "#foo [1 2 3]")))
<list: (read-string "#foo [1 2 3]")>
```

At least, this is something I'd need in clj-kondo.

**Comment by lread** [comment]
Yeah, I had these questions when I was working on v1.
But had no answers/ideas at the time.

To start with, is returning `read-string` forms the right thing to do for these for your use case? Are there any alternatives we would want to consider?

**Comment by borkdude** [comment]
I can understand the reasoning why rewrite-clj did this as it's not possible to represent a reader tag as an s-expression. So it chose to represent it as an evaluation of a string that contains a reader tag. Maybe expanding it to a configurable thing could be nice. E.g. if you know that `#foo` refers to `my-ns/foo` in data_readers.cljc, expanding to `(my-ns/foo (quote [1 2 3]))` may be more reasonable and then the round-trip problem would also be solved.

**Comment by lread** [comment]
Yes, maybe like something we invented (well mostly you came up with the idea) to [support namespaced maps](https://github.com/clj-commons/rewrite-clj/blob/main/doc/01-user-guide.adoc#custom-auto-resolve).
