### ISSUE TITLE
Support for type-checking homogenous maps

### ISSUE THREAD

**Issue by ikitommi** [clj-kondo/clj-kondo#2019]
**Is your feature request related to a problem? Please describe.**

[Malli](https://github.com/metosin/malli) (like spec and schema) supports homogenous maps via `:map-of`. Malli uses clj-kondo for type-checking functions inputs and outputs. Would be great if clj-kondo could be used to check both of the following:

1. homogenous maps
   - *map with :string keys and :boolean values*
   - e.g. `{"kikka" true, "kukka" false, "kakka" 123}` ;; <- last value fails
3. homo- & hetegenous maps
   - *map with :x :int, :y :int and rest with :string keys and :boolean values*
   - `{:x 1, :y 2, "kikka" true, "kukka" false, "kakka" 123}` ;; <- last value fails

The previous with malli:

```clojure
(-> [:map-of :string :boolean]
    (m/explain {"kikka" true, "kukka" false, "kakka" 123})
    :errors)
; => [{:path [1], :in ["kakka"], :schema :boolean, :value 123}]

(-> [:map
     [:x :int]
     [:y :int]
     [::m/default [:map-of :string :boolean]]]
    (m/explain {:x 1, :y 2, "kikka" true, "kukka" false, "kakka" 123})
    :errors)
; => [{:path [:malli.core/default 1], :in ["kakka"], :schema :boolean, :value 123}]
```

**Describe the solution you'd like**

A way to describe and enforce the above with clj-kondo.

**Comment by borkdude** [comment]
The question is how often you can statically verify this in real code. Could you give me some examples from real code?

**Comment by ikitommi** [comment]
I don't think it's common in the wild, but would be good for being more complete. There is a convention in many libraries (malli, reitit, I recall yada too) that configuration data is defined as map with *known un-qualified keys*  and *open/unknown qualified keys*  (e.g. user extensions).

example of runtime route data validation with reitit (currently using spec). https://github.com/metosin/reitit/blob/master/doc/basics/route_data_validation.md#closed-specs

in case of malli + reitit, the actual schema/spec for the endpoint/schema is accumulated from multiple sources. e.g. in reitit there is:

1. a global base-spec (that can be overridden)
2. each middleware/interceptor can contribute to the endpoint schema

... so the static analyser should be able to accumulate those know the schema to be useful.

Will try to find useful examples.
