### ISSUE TITLE
Support namespace groups in unresolved-namespace linter

### ISSUE THREAD

**Issue by Juholei** [clj-kondo/clj-kondo#2025]
**Is your feature request related to a problem? Please describe.**
We use an sql library that generates query namespaces in a macro so when running clj-kondo it gives us a lot of unresolved namespace warnings. It would be nice to be able exclude these without listing every single one of the generated namespaces.

**Describe the solution you'd like**
https://github.com/clj-kondo/clj-kondo/blob/master/doc/config.md#namespace-groups says to create an issue if you want support for namespace groups for other linters. For our problem it would be a solution to define a namespace group with pattern ".*-db$" if unresolved-namespace linter also supported namespace groups.

**Describe alternatives you've considered**
I haven't come up with any other solution apart from listing all the namespaces manually to be excluded.

**Comment by borkdude** [comment]
> So the functions and namespaces are generated during runtime

That doesn't mean you can't write a `(:require [your-generated-namespace])` though

**Comment by borkdude** [comment]
I mean, you just have to ensure that the creation of those namespaces is done before you require those namespaces.

**Comment by borkdude** [comment]
But happy to support both options.

**Comment by borkdude** [comment]
`:ns-groups` + `:unresolved-namespace` combo is now supported on master
