### ISSUE TITLE
aset is called with 4 args but expects 3

### ISSUE THREAD

**Issue by archaic** [clj-kondo/clj-kondo#2035]
**version**
clj-kondo v2023.01.20

**platform**
NixOS / Native

**editor**
From shell

**problem**
The call (aset dataset i j -byte) is returning a lint error
error: clojure.core/aset is called with 4 args but expects 3

**repro**
(defn foo
  [array i j -byte]
  (aset array
        i
        j
        -byte))

**expected behavior**
No lint error, aset can take multiple indexes

**Comment by borkdude** [comment]
This has already been fixed in the newest release.

**Comment by archaic** [comment]
Thanks

**Comment by archaic** [comment]
Hi, just following up, using 
:extra-deps {clj-kondo/clj-kondo {:git/url "https://github.com/clj-kondo/clj-kondo"
                                                            :git/sha "0bb8610678e26492e6c05effe650e6b7393a2b1d"}}

clojure -M:dev:clj-kondo --version
clj-kondo v2023.03.18-SNAPSHOT

clojure -M:dev:clj-kondo --lint src
is still returning
clojure.core/aset is called with 4 args but expects 3

**Comment by borkdude** [comment]
@archaic You might be having a caching issue. Please delete `.clj-kondo/.cache` and try again
