### ISSUE TITLE
Reader literals in ns :require are ignored

### ISSUE THREAD

**Issue by colliderwriter** [clj-kondo/clj-kondo#2040]
**version**
clj-kondo v2023.03.17

**macro usage**
N/A

**platform**
Linux 6.1.7-200.fc37.x86_64

**editor**
GNU Emacs 28.2

**problem**

[ Please provide a short and to the point description of the problem ]

**repro**
In a .cljc file, attempting to set up tests for both clj and cljs using a reader literal in the namespace :require as in

```
(ns xxxx.common-test
  (:require [models.common :as sut]
            #?(:clj [clojure.test :as t]
               :cljs [cljs.test :as t :include-macros true])))
```

causes clj-kondo to return an "unparseable libspec".

I get the same result for

```
(ns xxxx.common-test
  (:require [models.common :as sut]
            #?(:clj [clojure.test :as t])
            #?(:cljs [cljs.test :as t :include-macros true])))
```             
which lints from the command line as
```
$  clj-kondo --lint test/xxxx/common_test.clj 
test/xxxx/common_test.clj:3:15: error: Unparsable libspec: (:clj [clojure.test :as t])
test/xxxx/common_test.clj:4:15: error: Unparsable libspec: (:cljs [cljs.test :as t :include-macros true])
test/xxxx/common_test.clj:7:2: error: Unresolved symbol: deftest
test/xxxx/common_test.clj:7:10: error: Unresolved symbol: test-url?
test/xxxx/common_test.clj:8:4: error: Unresolved symbol: testing
test/xxxx/common_test.clj:9:6: error: Unresolved symbol: is
linting took 25ms, errors: 6, warnings: 0
```

**config**
{;;:skip-comments true
 :lint-as {potemkin/def-derived-map clojure.core/defrecord}
 :linters {:missing-else-branch {:level :off}
           :unused-binding {:level :off}
           :unused-referred-var {:exclude {clojure.test [deftest testing is are]
                                           cljs.test [deftest testing is are]}}}}

**expected behavior**
No lint errors at all

**Comment by borkdude** [comment]
If you're in a `.clj` file, reader conditionals don't apply. The file should end with `.cljc`. Is that the case in your situation? 

``` clojure
clj-kondo --lint test/xxxx/common_test.clj 
```

seems to suggest you're using a `.clj` file?

**Comment by colliderwriter** [comment]
You are correct. 

After hours coding error.


Closing and donating for wasting your valuable time.

**Comment by borkdude** [comment]
Thank you!
