### ISSUE TITLE
Feature: Ability to treat a namespace as already required

### ISSUE THREAD

**Issue by rschmukler** [clj-kondo/clj-kondo#2051]
To upvote this issue, give it a thumbs up. See [this list](https://github.com/clj-kondo/clj-kondo/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) for the most upvoted issues.

**Is your feature request related to a problem? Please describe.**

Writing hooks for custom macros can benefit from deeper analysis that clj-kondo can perform. An example is the binding analysis performed for calls to `clojure.core.match/match`. Consider the following macro:

```clojure
(ns my-ns.macros
  (:require [clojure.core.match :refer [match]]))
  
(defmacro when-match
  "Similar to `when-let` but uses match patterns for binding."
  [bindings & body]
  (let [[pattern expr] bindings]
    `(match ~expr
       ~pattern (do ~@body)
       _# nil)))
```

It would be nice to have linting apply to the resulting expression (eg. unused variables) using the sophistication of the existing analyzer. Unfortunately, if the consuming namespace does not require `clojure.core.match` explicitly an `:unresolved-namespace` linting error is thrown. While the error can be ignored (via metadata on the macro or `:config-in-call`) the deeper analysis of `clojure.core.match/match` is not performed.  If the consuming namespace requires `clojure.core.match` the analysis does get performed correctly.

**Describe the solution you'd like**
It would be nice if `:config-in-call` (or macro metadata) could be used to hint to `clj-kondo` that a require has already happened. Eg:

```clojure
 :config-in-call
 {my-ns.macros/when-match
  {:implied-requires [clojure.core.match]}}}
```

**Describe alternatives you've considered**
Initially attempted using `:config-in-call` to ignore the linting error, but that short-circuits the analysis. For now I am requiring the namespace in the consuming namespace but it's odd to have an unused require for the sake of clj-kondo linting.

**Comment by borkdude** [comment]
@rschmukler Here is a PR to fix it as follows: the entries in `:excluded` are considered as already required namespaces.

https://github.com/clj-kondo/clj-kondo/pull/2052

``` clojure
(deftest excluded-implies-already-required
  (assert-submaps2
   [{:row 1,
     :col 1,
     :level :warning,
     :message "Do not use join"}]
   (lint! "(clojure.string/join \",\" [1 2 3])"
          '{:linters
            {:discouraged-var {clojure.string/join {:message "Do not use join"}}
             :unresolved-namespace {:exclude [clojure.string]}}})))
```

**Comment by borkdude** [comment]
Thanks for sponsoring! :)
