### ISSUE TITLE
Add support to lint clara-rules defrule and defquery macros

### ISSUE THREAD

**Issue by k13gomez** [clj-kondo/clj-kondo#2059]
clj-kondo currently supports a handful of libraries, and I would like to add support for the [clara](https://github.com/cerner/clara-rules) rules engine. Primarily there are two macros for which support is needed:
- `clara.rules/defrule`
- `clara.rules/defquery`

These macros are responsible for defining bindings for queries and rules written using clara dsl, and for defining each rule's LHS constraints and RHS body.

I attempted to write support for this library using hooks but it seems simpler to just add built-in support using a custom analyzer which understand the clara-rules definitions and can parse and analyze them with the proper contextual semantics for bindings.

**Comment by borkdude** [comment]
Ever since clj-kondo supports hooks, I'm not adding bespoke support for libraries if I can prevent it, so let's investigate the hook option first.

**Comment by k13gomez** [comment]
You can review the proposed implementation I've got working in #2060, the main barrier I encountered when attempting to add support for this using hooks is that I did not have access to the following namespace functions inside the hook.

```clojure
[clj-kondo.impl.analyzer.common :refer [extract-bindings ctx-with-bindings analyze-children]]
```

**Comment by borkdude** [comment]
@k13gomez Cool, I'll take a look at this later this week hopefully!

**Comment by k13gomez** [comment]
@borkdude I think I have figured out how to accomplish the same thing using an analyze-call hook, I'm closing this issue but for anyone else curious here's the hook I wrote: https://github.com/k13gomez/clj-kondo-config/blob/main/hooks/clara_rules.clj

**Comment by borkdude** [comment]
@k13gomez I'm glad you figured it out! 

Now it would be convenient for others if you could PR this config to clara_rules itself, so when you use this dependency, you can import the configuration.

To export a configuration in a dependency:

https://github.com/clj-kondo/clj-kondo/blob/master/doc/config.md#exporting

To import from a dependency:

https://github.com/clj-kondo/clj-kondo/blob/master/doc/config.md#importing

If you want or need any help with this, please let me know!
