### ISSUE TITLE
(= true x) => (true? x)

### ISSUE THREAD

**Issue by borkdude** [clj-kondo/clj-kondo#2065]
Idea taken from splint / kibit.

About (= true x) => (true? x), I'm a bit on the fence of the importance of these things and "is it always what you want?"

E.g.:

user=> (time (dotimes [i 100000000] (= true 1)))
"Elapsed time: 54.981042 msecs"
nil
user=> (time (dotimes [i 100000000] (true? 1)))
"Elapsed time: 104.490417 msecs"
nil
user=> (time (dotimes [i 100000000] (identical? true 1)))
"Elapsed time: 13.819041 msecs"

true? is 2x as slow as (= true x) and (identical? true x) is ~10x as fast as (true? x) ?

So it depends from which angle you're coming. Is it shorter? yes? Is it faster? no. Does it matter? Don't know.

The above turned out to be a JIT / profiling issue.

```
(quick-bench (true? 1))
; Execution time mean : 2.923421 ns

(quick-bench (= true 1))
; Execution time mean : 33.659225 ns

(quick-bench (identical? true 1))
; Execution time mean : 2.722816 ns
```

The difference in CLJS is quite dramatic:

```
cljs.user=> (time (dotimes [i 100000000] (= true 1)))
"Elapsed time: 2095.988709 msecs"
nil
cljs.user=> (time (dotimes [i 100000000] (true? 1)))
"Elapsed time: 38.172708 msecs"
```

**Comment by svdo** [comment]
Would it make sense to also add the equivalent `:equals-false` linter?

**Comment by borkdude** [comment]
sure

**Comment by svdo** [comment]
See PR: https://github.com/clj-kondo/clj-kondo/pull/2202
