### ISSUE TITLE
Add type-linting of function arguments and return values within function body 

### ISSUE THREAD

**Issue by ikitommi** [clj-kondo/clj-kondo#2070]
Type-linting is awesome feature. And it could be even more awesome!

# Problem

Currently, clj-kondo handles type-mismatch errors for function inputs and return values when function is called, but not within the function body.

## Example from malli

Generated clj-kondo config:
```clojure
{:linters {:type-mismatch {:namespaces {demo {my-fn {:arities {1 {:args [:string], :ret :string}}}}}}}}
```

Code:
```clojure
(ns demo
  (:require [malli.experimental :as mx]))

(mx/defn my-fn :- :string [x :- :string]
  ;; function arguments or return values are
  ;; not type-checked within function body :(
  (inc x))

(comment
 ;; function arguments are checked
 (my-fn :10) ;; => clj-kondo: Expected: string, received: keyword.

 ;; function retun values are checked
 (inc (my-fn "10"))) ;; => clj-kondo: Expected: number, received: string.

(comment
 ((requiring-resolve 'malli.dev/start!)))
```

# Suggestion

I would like clj-kondo also to type-check the arguments and return value within the function body, giving greatly improved type-checking experience.

# Another example

Example from frontend development:

```clojure
(def Props
  [:map
   [:name :string]
   [:address [:map
              [:super-street :string]
              [:super-number :int]]]])

(mx/defn reagent-render-fn [props :- Props]
  [:h1 (-> props :address :super-street inc)])
```

Full generated clj-kondo config:

```clojure
{:linters {:type-mismatch {:namespaces {demo {my-fn {:arities {1 {:args [:string], :ret :string}}},
                                              reagent-render-fn {:arities {1 {:args [{:op :keys,
                                                                                      :req {:name :string,
                                                                                            :address {:op :keys,
                                                                                                      :req {:super-street :string,
                                                                                                            :super-number :int}}}}],
                                                                              :ret :any}}}}}}}}
```

Seen from Cursive:

<img width="475" alt="Screenshot 2023-05-05 at 22 02 34" src="https://user-images.githubusercontent.com/567532/236547128-d450fb92-5329-44c7-a650-81975aa3a5a3.png">

**Comment by ikitommi** [comment]
bit similar issue here: #1973

**Comment by ericdallo** [comment]
This is pretty similar to https://github.com/clj-kondo/clj-kondo/issues/1268, which is a similar support for schema.core, we should probably think on something that works for both

**Comment by ikitommi** [comment]
Malli already creates valid clj-kondo config and this works from outside of the function: we get type errors on function arguments and on return values. This does not work within function definition:

<img src="https://user-images.githubusercontent.com/567532/236547128-d450fb92-5329-44c7-a650-81975aa3a5a3.png">
