### ISSUE TITLE
ClojureCLR support

### ISSUE THREAD

**Issue by elenapoot** [clj-kondo/clj-kondo#2072]
To upvote this issue, give it a thumbs up. See [this list](https://github.com/clj-kondo/clj-kondo/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) for the most upvoted issues.

(I don't really know where clojure-lsp ends and clj-kondo begins, so I'm copying this to both. I am a newbie VSC/Calva user doing extensive work in ClojureCLR.)

Please add ClojureCLR support, specifically:

Support for *.cljr files 
Support for :cljr reader conditional

By support, I mean handling much as cljs is handled, so that cljr namespaces are considered distinct from clj and cljs namespaces and conditional code is assigned to the appropriate ones of those. 

Java-based tools can't verify anything in imports or required namespaces not in the current body of code (there is no classpath and if there was you wouldn't be able to read the .dll files it would lead to). If you simply assume references to unknown namespaces and imported classes are correct and don't flag them as problems or unresolvable, that would be wonderful. 

In addition, there are some new syntactic forms that look much like functions, but are more special forms. As a first cut, just accepting them without trying to resolve them would be great. I may miss some, but these would include:

   by-ref, sys-func, sys-action, enum-val, enum-or, enum-and, assembly-load, assembly-load-from, assembly-load-file and 
   assembly-load-with-partial-name. 

There are also new type hints uint, ulong, uints and ulongs for unsigned types. 

More info on the syntactic additions is at https://github.com/clojure/clojure-clr/wiki/ but even minimal support would be far better than none at all, and would provide a starting point. Just doing those things mentioned above would be very helpful.

**Comment by borkdude** [comment]
@elenapoot I don't really know ClojureCLR or how to run it locally, but a bunch of samples, perhaps a `.cljc` / `.cljr` sample project, would be useful as a starting point to address what you described in the above text. In the sample project we can execute clj-kondo and try to reduce the false positives issue by issue.

**Comment by elenapoot** [comment]
I will be happy to put together a sample project and hit as many trouble spots as I can, but all my code is proprietary, so it’ll probably be the weekend before I have time to do it. I'm sure I can pull code from the ClojureCLR tests and examples in the wiki. In hindsight, I should maybe have done this as a series of smaller requests, as just basic support for the file extension and the reader conditional would do wonders, but I'll leave that to you as far as scheduling and priorities if some bits of it are more difficult. Copying this same response to the clojure-lsp issue, since he made the same (perfectly reasonable) request.

**Comment by borkdude** [comment]
>  but I'll leave that to you 

Please post individual issues with actionably input and expected output. I don't have any knowledge about CLR so I'd appreciate if you could make this as clear as possible without leaving any guesswork on my table.

**Comment by elenapoot** [comment]
OK, should I close this one and do them in bite-sized pieces as we progress through the process?

**Comment by borkdude** [comment]
Let's do it. I'll tag the issues with `clr` so we can see them all together.

**Comment by elenapoot** [comment]
OK, I'll close this one and post a new one tonight, and we'll go from there. I should be able to knock together a basic sample for just the file extension and reader conditional quickly enough. :)
