### ISSUE TITLE
multi-architecture docker image (arm64, amd64)

### ISSUE THREAD

**Issue by denisa** [clj-kondo/clj-kondo#2093]
[ Leave this text in if you want to promote it. ]

To upvote this issue, give it a thumbs up. See [this list](https://github.com/clj-kondo/clj-kondo/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) for the most upvoted issues.

[ To keep development of this project going, consider sponsoring. If you are
already a sponsor, thank you! You can remove this message. ]

**Is your feature request related to a problem? Please describe.**
Since the introduction of Apple’s M1 mac, the number of readily available computer with arm64 architecture is growing.
While both macOS and docker are making provide some level of support for executing amd64 binaries, they are not foolproof, and are slower.

This will also help other projects, such as super-linter, that includes clj tools.

**Describe the solution you'd like**
Please consider generating multi-architecture docker image (https://docs.docker.com/build/building/multi-platform/, https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/)

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

[ Optional: if you are interested in doing a PR yourself, please leave a note. ]

**Comment by borkdude** [comment]
The workaround for now is to just download the binary for your OS (e.g. aarch64, linux) into a Docker image I guess.

**Comment by harryzcy** [comment]
It will be added by #2289

**Comment by borkdude** [comment]
Multi-arch image added:

https://hub.docker.com/layers/cljkondo/clj-kondo/2024.02.13-SNAPSHOT/images/sha256-ea849cf18ceec156ce35c17098aab0340beb5f5eaaa515392d8f56da3e3cd152?context=explore

Please test it out.

**Comment by harryzcy** [comment]
@borkdude Can you please cut a release? Thanks

**Comment by borkdude** [comment]
Will do!

**Comment by borkdude** [comment]
Should be there now

**Comment by harryzcy** [comment]
@borkdude Thanks!
