### ISSUE TITLE
protocols and protocol methods do not include metadata

### ISSUE THREAD

**Issue by lread** [clj-kondo/clj-kondo#2097]
## version
```
❯ clj-kondo --version
clj-kondo v2023.05.26
```

## platform
all

## problem
Clj-kondo data analysis does not mark private protocol methods as private.

## repro
Given `src/testing123/proto.clj`
```Clojure
(ns testing123.proto)

(defprotocol SomeProto
  (^:private private-method [_])
  (public-method [_]))

;; a normal private fn for comparison
(defn ^:private privatefn [])
```

If we run analysis on this source:
```Clojure
❯ clj-kondo --config '{:config-paths ^:replace [] :output {:format :edn :analysis {:var-definitions {:meta true}}}}' \
        --lint src \
        | jet --query ':analysis :var-definitions' --pretty
[{:col 1,
  :defined-by clojure.core/defprotocol,
  :defined-by->lint-as clojure.core/defprotocol,
  :end-col 23,
  :end-row 5,
  :filename "src/testing123/proto.clj",
  :meta nil,
  :name SomeProto,
  :name-col 14,
  :name-end-col 23,
  :name-end-row 3,
  :name-row 3,
  :ns testing123.proto,
  :row 3}
 {:col 3,
  :defined-by clojure.core/defprotocol,
  :defined-by->lint-as clojure.core/defprotocol,
  :end-col 33,
  :end-row 4,
  :filename "src/testing123/proto.clj",
  :fixed-arities #{1},
  :meta nil,
  :name private-method,
  :name-col 14,
  :name-end-col 28,
  :name-end-row 4,
  :name-row 4,
  :ns testing123.proto,
  :protocol-name SomeProto,
  :protocol-ns testing123.proto,
  :row 4}
 {:col 3,
  :defined-by clojure.core/defprotocol,
  :defined-by->lint-as clojure.core/defprotocol,
  :end-col 22,
  :end-row 5,
  :filename "src/testing123/proto.clj",
  :fixed-arities #{1},
  :meta nil,
  :name public-method,
  :name-col 4,
  :name-end-col 17,
  :name-end-row 5,
  :name-row 5,
  :ns testing123.proto,
  :protocol-name SomeProto,
  :protocol-ns testing123.proto,
  :row 5}
 {:col 1,
  :defined-by clojure.core/defn,
  :defined-by->lint-as clojure.core/defn,
  :end-col 30,
  :end-row 8,
  :filename "src/testing123/proto.clj",
  :fixed-arities #{0},
  :meta {:private true},
  :name privatefn,
  :name-col 17,
  :name-end-col 26,
  :name-end-row 8,
  :name-row 8,
  :ns testing123.proto,
  :private true,
  :row 8}]
```

If we look at `private-method` analysis data we see that it is missing `:meta {:private true}` and `:private true`:
```Clojure
 {:col 3,
  :defined-by clojure.core/defprotocol,
  :defined-by->lint-as clojure.core/defprotocol,
  :end-col 33,
  :end-row 4,
  :filename "src/testing123/proto.clj",
  :fixed-arities #{1},
  :meta nil,
  :name private-method,
  :name-col 14,
  :name-end-col 28,
  :name-end-row 4,
  :name-row 4,
  :ns testing123.proto,
  :protocol-name SomeProto,
  :protocol-ns testing123.proto,
  :row 4}
```

## expected behavior
Protocol methods marked as private should show as private in clj-kondo analysis data.

See `privatefn` above in analysis data for comparison.

Illustration of privateness of protocol method in REPL session:
```Clojure
❯ clj
Clojure 1.11.1
user=> (require '[testing123.proto :as p])
nil
user=> (ns-publics 'testing123.proto)
{SomeProto #'testing123.proto/SomeProto, public-method #'testing123.proto/public-method}
user=> (ns-interns 'testing123.proto)
{SomeProto #'testing123.proto/SomeProto, privatefn #'testing123.proto/privatefn, public-method #'testing123.proto/public-method, private-method #'testing123.proto/private-method}
user=> (p/private-method "foo")
Syntax error (IllegalStateException) compiling p/private-method at (REPL:1:1).
var: #'testing123.proto/private-method is not public
```

## Examples in the wild
https://grep.app/search?q=%28%5E%3Aprivate&filter[lang][0]=Clojure

## Next Steps
If this is an issue you'd like to resolve, I'm happy to help.

**Comment by borkdude** [comment]
Sure. What is the use case for private protocol methods, but not a private protocol var? `(defprotocol ^:private Foo)`

**Comment by lread** [comment]
I found this in the wild when working on cljdoc, so your guess is as good as mine for the motivation. I guess the authors just wanted some protocol methods to be deemed internal implementation details of ns. 

As you can see from my grep.app link, I did not find too many usages of this pattern in the wild.

**Comment by borkdude** [comment]
OK, sounds good, fix welcome!

**Comment by lread** [comment]
## More clarity on usage
> What is the use case for private protocol methods, but not a private protocol var? `(defprotocol ^:private Foo)`

I was curious and looked into it a bit... it seems that if you mark a protocol as `^:private` it does not make its methods private. 

So a private protocol is stating: don't extend me outside my namespace.
And a private protocol method is stating: don't call me outside my namespace.

## Generalizing a bit
I've generalized this issue to cover including metadata for protocols and protocol methods instead of just covering `:private`. 

## Linting as :unused-private-var
I suppose unused private protocols and unused private protocol methods should be found to be `:unused-private-var`s, ya? I think this should probably happen naturally after I make my change. I'll verify with some tests.
