### ISSUE TITLE
Is it possible to exclude a linter by path?

### ISSUE THREAD

**Issue by jakepearson** [clj-kondo/clj-kondo#2127]
My team enabled `warn-on-reflection` on our repos. Works great. One person asked if we could disable that linter on our tests since we don't really care if there is a small perf hit in testing. I tried updating our config to look like:

```edn
{:linters {
  :warn-on-reflection {:level :warning :exclude "test"}}
```
which didn't appear to do anything. Is something like that possible?

**Describe the solution you'd like**
Be able to define a pattern in the exclude field as well as a set of namespaces like `Kondo` currently supports.

**Describe alternatives you've considered**
- add `(set! *warn-on-reflection* true)` to the requested test files (already did this, and it is fine)

I would be happy to try to work on this if someone can point me in the right direction.

**Comment by borkdude** [comment]
@jakepearson You can do this as follows:

- Create an [ns-group](https://github.com/clj-kondo/clj-kondo/blob/master/doc/config.md#namespace-groups), you can use `filename-pattern` or simply `pattern` which is based on the namespace name
- Then you can use the name of the ns-group in `:config-in-ns` to disable the linter:

``` clojure
{:config-in-ns {test-group {:linters {:warn-on-reflection {:level :off}}}}}
```

**Comment by jakepearson** [comment]
That worked perfectly. Thanks a bunch.
