### ISSUE TITLE
Cache analysis by library version

### ISSUE THREAD

**Issue by lilactown** [clj-kondo/clj-kondo#2141]
To upvote this issue, give it a thumbs up. See [this list](https://github.com/clj-kondo/clj-kondo/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) for the most upvoted issues.

**Is your feature request related to a problem? Please describe.**

At work, we have a large monorepo with many projects. Some of them may pull in different versions of libraries that have different function signatures and other things that are specific to that version. We also want the ability to share an analysis cache between projects so that linting the whole repo is fast and the cache is easy to persist in CI.

Currently, if project *Foo* in our monorepo pulls in lib *v1*, and project *Bar* pulls in lib *v2*, running the following command for each project from the root

```
clj-kondo --copy-configs --dependencies --parallel --lint $classpath
```

the cache will only persist the last ran analysis. So if *Foo* is analyzed after *Bar*, then the cache will contain the analysis for lib *v1*. This makes linting the project from the root fail for *Bar* because it depends on more recent function signatures etc. that are in lib *v2*.

**Describe the solution you'd like**

I think it may be possible to persist the analysis for each version, and clj-kondo could detect which version to use by inspecting the classpath. There may be reasons this wouldn't work, though. The cache may also grow as you upgrade, meaning that people will want to manually evict the cache if they care about the size of it. It could also 

**Describe alternatives you've considered**

Currently, we have managed to fix this for ourselves by pinning versions. This was good practice anyway in the cases we ran into, but may not be feasible for future cases when we do want to have different versions of libraries installed in different projects (e.g. incrementally migrating projects to a new service).

We could instead run the clj-kondo analysis in the context of each sub-project, meaning that each project would have its own analysis. This adds additional burden for us to maintain a list of directories that our CI should persist between runs.

**Additional context**

For more context, we use [lein-monolith](https://github.com/amperity/lein-monolith) for running commands in each project from the root of our monorepo, and have adopted the [lein-clj-kondo](https://github.com/clj-kondo/lein-clj-kondo) plugin recently.

**Comment by greglook** [comment]
Updating hook definitions for macros in an analyzed library doesn't seem to invalidate the analysis for that library either, forcing a manual cache-bust each time.

**Comment by borkdude** [comment]
The .clj-kondo directory should not be used across multiple projects, e.g. not in the parent directory of a mono-repo.
