### ISSUE TITLE
[analysis] - add gen-class info

### ISSUE THREAD

**Issue by brandonstubbs** [clj-kondo/clj-kondo#2142]
To upvote this issue, give it a thumbs up. See [this list](https://github.com/clj-kondo/clj-kondo/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) for the most upvoted issues.

**Is your feature request related to a problem? Please describe.**
It would be great to know which namespaces have `gen-class` included while using the analysis API.

**Describe the solution you'd like**
Maybe it would be good if `:namespace-definitions` could include an optional entry of `:gen-class true` if there is a `gen-class` within that namespace definition. This will keep it aligned with the analyzer `analyze-gen-class`.

**Comment by borkdude** [comment]
Can you elaborate on why you would like to know which ns forms have gen-class true?

Note that `:gen-class` can take more options than just `true`:

```
(ns com.domain.tiny
  (:gen-class
    :name com.domain.tiny
    :methods [#^{:static true} [binomial [int int] double]]))
```

**Comment by brandonstubbs** [comment]
I am building a tool to automatically build a mono-repo. The tool will need to know all the `service` entrypoints, which can be done by looking at which namespaces have a `gen-class`. From this, I can then do all the relevant tree-shaking, dependency detection, etc. walking from the services to minimise deployment impact of changes within the mono-repo.

Both `:gen-class true` or `:gen-class <gen-class-meta>` would work for what I am after.

**Comment by borkdude** [comment]
What is a "service"? Are there other ways to detect a service? Does a service have a `-main` namespace? Can you ask from users to add metadata to their ns forms to signal that it's a service?

Note that `(gen-class ..)` can also be executed as a function to just looking at the ns form might not be 100% reliable.

**Comment by brandonstubbs** [comment]
A `service` are all the main entrypoints. You are correct I could use `-main` var-definitions instead thanks! Happy for this to be closed out

**Comment by borkdude** [comment]
alright, let's close for now and we can re-open if there's other use cases
