### ISSUE TITLE
Support `=` in options

### ISSUE THREAD

**Issue by AndreaCrotti** [clj-kondo/clj-kondo#2150]
**version** 

clj-kondo v2023.07.13

**problem**

The behaviour of `--fail-level=error` and `--fail-level error` is different at the moment, which might be surprising since many other CLI tools see them as equivalent.

**expected behavior**

it should either be supported or just error when you pass something that's not expected.

**Comment by borkdude** [comment]
Alright, I think we can just split stuff that starts with `--` on `=` and then process it. Hopefully not a big change.
