### ISSUE TITLE
Parse-uuid typed wrongly

### ISSUE THREAD

**Issue by dbunin** [clj-kondo/clj-kondo#2187]
**problem**

Given

```
(parse-uuid 1)
```
You see a warning saying that parse-uuid should be either nil or string. 

**expected behavior**

Given that 

```
; eval (root-form): (parse-uuid nil)
; (err) Execution error (NullPointerException) at java.util.UUID/fromString (UUID.java:237).
; (err) Cannot invoke "String.length()" because "name" is null
```

I would expect the parse-uuid not to be nilable but just a string. So maybe something like:

```
parse-uuid {1 {:args (:string)}}
```

Open to making a PR

**Comment by borkdude** [comment]
Sure, PR welcome!
