### ISSUE TITLE
Support end-row and end-col in :pattern output format

### ISSUE THREAD

**Issue by joshgelbard** [clj-kondo/clj-kondo#2192]
As in

```
clj-kondo --lint src/foo.clj --config \
'{:output {:pattern "{{LEVEL}} {{type}} {{filename}} {{row}} {{end-row}} {{col}} {{end-col}} | {{message}}"}}'
```

Not vital, but it'd be cool.

It'd need to go in config.md#print-results-with-a-custom-format , too. (Which I think is also missing the very useful `{{type}}`.)

I'd happily submit a PR for this one — I assume it's just `impl.core` and ~~wherever the docs live (haven't yet looked)~~ config.md.

**Comment by borkdude** [comment]
Sure, PR welcome!
