### ISSUE TITLE
Expose callstack in analysis (as optional data)

### ISSUE THREAD

**Issue by borkdude** [clj-kondo/clj-kondo#2200]
clj-kondo internally uses a callstack which contains information about which functions are called at the definition or function call of a var:

```
 $ clj -M:clj-kondo/dev --lint - <<< '(comment (def x. 1))'
([clojure.core def] [clojure.core comment])
```

This could be used by clojure-lsp to determine if a var is defined within `comment`.

The format currently used in clj-kondo isn't directly suited to export as EDN since we also attach information as metadata to the symbols, etc. Probably exposing it as a list of maps is better so we can add more information later:

```
[{:ns clojure.core :name def} {:ns clojure.core :name comment}]
```

We would either have to refactor the internal format or convert from vectors to maps on analysis export.

Q: is starting with having `:callstack` in `:var-definitions` sufficient, or do we also need it in ` :var-usages`?

cc @ericdallo

**Comment by ericdallo** [comment]
For clojure-lsp is enough to have on var-definitions as our unused-public-var linter is only used applicable for var-definitions, so we just need to know the calls rack of that var-definitions to really know if it's unused inside a comment or not
