### ISSUE TITLE
Support a gitlab CI friendly output natively

### ISSUE THREAD

**Issue by toniz4** [clj-kondo/clj-kondo#2263]
[ Leave this text in if you want to promote it. ]

To upvote this issue, give it a thumbs up. See [this list](https://github.com/clj-kondo/clj-kondo/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) for the most upvoted issues.

- [x] I have read the [Clojure etiquette](https://clojure.org/community/etiquette) and will respect it when communicating on this platform.

[ To keep development of this project going, consider sponsoring. If you are
already a sponsor, thank you! You can remove this message. ]

**Is your feature request related to a problem? Please describe.**

While trying to integrate a clj-kondo into a project that is in gitlab, I found that It can't be done with just clj-kondo, and I think it would be nice if it was an option to output the clj-kondo findings in a way that gitlab would understand.

Here's the documentation of the format that gitlab expects:

https://docs.gitlab.com/ee/ci/testing/code_quality.html#implement-a-custom-tool 

**Describe the solution you'd like**

A option to change the output format to what gitlab would expect, something like `'{:output {:format :gitlab}}'`.

**Describe alternatives you've considered**

This [gist](https://gist.github.com/hansbugge/4be701d771057e8ef6bbbb0912656355) is linked in the documentation, but I think having to use another tool on top of clj-kondo should not be needed and it would be way easier to setup. 

[ Optional: if you are interested in doing a PR yourself, please leave a note. ]

If it's something relevant to clj-kondo, I can submit a PR implementing this.

**Comment by borkdude** [comment]
This is what the JSON/EDN output is for. You could use that output to make a plugin for Gitlab.

**Comment by toniz4** [comment]
> This is what the JSON/EDN output is for. You could use that output to make a plugin for Gitlab.

Fair enough
