### ISSUE TITLE
String* may also appear outside of metadata

### ISSUE THREAD

**Issue by borkdude** [clj-kondo/clj-kondo#2276]
So clj-kondo --lint - <<< 'String*' should not report an error

**Comment by puredanger** [comment]
fyi, this notation is going to change in next alpha to `String::1`, watch [CLJ-2833](https://clojure.atlassian.net/browse/CLJ-2833).  But it is actually a valid class name (and deftype can make such a thing), so it should be valid regardless.

**Comment by borkdude** [comment]
Noted, I'll open a new issue.
