### ISSUE TITLE
Array class notation will change to`String/1`, per CLJ-2833

### ISSUE THREAD

**Issue by borkdude** [clj-kondo/clj-kondo#2303]
fyi, this notation is going to change in next alpha to `String::1`, watch [CLJ-2833](https://clojure.atlassian.net/browse/CLJ-2833).  But `String*` could actually be a valid class name (and deftype can make such a thing), so it should be potentially valid regardless.

_Originally posted by @puredanger in https://github.com/clj-kondo/clj-kondo/issues/2276#issuecomment-1998538385_

**Comment by NoahTheDuke** [comment]
This has been decided against, the syntax is `String/1` as per [CLJ-2807](https://clojure.atlassian.net/browse/CLJ-2807)

**Comment by borkdude** [comment]
Thanks for the update.
