### ISSUE TITLE
Requiring the current namespace with an alias isn't marked as unused

### ISSUE THREAD

**Issue by dpassen** [clj-kondo/clj-kondo#2355]
- [X] I have read the [Clojure etiquette](https://clojure.org/community/etiquette) and will respect it when communicating on this platform.

**version**

v2024.05.24

**platform**

Native binary

**editor**

emacs w/ flycheck-clj-kondo

**problem**

If a namespace requires itself with an unused alias, it is not marked as unused.

**repro**

https://github.com/dpassen/kondo-repro-unused

**expected behavior**

Expect that the namespace is marked as 'required but never used'

**Comment by borkdude** [comment]
@dpassen What's the use case for a self-requiring namespace?

**Comment by dpassen** [comment]
As far as I know, there isn’t. I was surprised this worked, but found it in a real project, in some test code.

**Comment by borkdude** [comment]
There is a linter in clj-kondo named `:self-requiring-namespace`. IMO you shouldn't be doing that. The linter is off by default but perhaps it should be enabled by default.

**Comment by borkdude** [comment]
yeah, that might come in handy

**Comment by borkdude** [comment]
I'll make sure that'll work in the next release
