### ISSUE TITLE
`stream-` functions from Clojure 1.12 are not supported

### ISSUE THREAD

**Issue by roman-rudakov** [clj-kondo/clj-kondo#2392]
- [x] I have read the [Clojure etiquette](https://clojure.org/community/etiquette) and will respect it when communicating on this platform.

**version**

clj-kondo v2024.08.29

**platform**

MacOS, homebrew.

**editor**

Emacs 30

**problem**

Some functions from Clojure 1.12 are not supported:

- `stream-seq!`
- `stream-into!`
- `stream-reduce!`
- `stream-transduce!`

**repro**

```clojure
(ns repro)

(stream-seq! (java.util.stream.Stream/of 1))
```

Output or `clj-condo --lint repro.clj`

```
repro.clj:3:2: error: Unresolved symbol: stream-seq!
linting took 11ms, errors: 1, warnings: 0
```

**Comment by borkdude** [comment]
Already fixed on master

https://www.michielborkent.nl
https://www.eetvoorjeleven.nu

**Comment by roman-rudakov** [comment]
Nice, thanks! Waiting for the next release then.

**Comment by borkdude** [comment]
@roman-rudakov You can have this working right now by just using clojure 1.12 in your deps.edn and linting the dependencies like this:

```
clj-kondo --lint "$(clojure -Sdeps)" --dependencies 
```

**Comment by roman-rudakov** [comment]
I already have clojure 1.12 in my `deps.edn` and I run clj-kondo as `clj-kondo --lint src test env`, where `src`, `test` and `env` are just directories in my classpath.

If I run:

```
clj-kondo --lint "$(clojure -Sdeps)" --dependencies 
```

with some syntax error in the sources, it doesn't report it at all.

According to the help `-Sdeps` also expects an argument:
```
-Sdeps EDN     Deps data to use as the last deps file to be merged
```

If I run `clojure -Sdeps` in the project root, I'm getting an empty output.

Considering this I'm not really sure how to make clj-kondo using clojure 1.12 properly for my project.

**Comment by borkdude** [comment]
```
clj-kondo --lint "$(clojure -Spath)" --dependencies 
```

is what I meant.

Please follow the documentation here:

https://github.com/clj-kondo/clj-kondo?tab=readme-ov-file#project-setup

**Comment by roman-rudakov** [comment]
ah, yes, I tried it. I usually run the following to refresh the cache, it doesn't fix the problem for me:

```
clj-kondo --copy-configs --dependencies --lint "$(clojure -Spath)"
```

**Comment by roman-rudakov** [comment]
Looks like I had to manually remove `.clj-kondo/.cache` before running this. Sorry. Now it works for me.

**Comment by borkdude** [comment]
you shouldn't have had to remove the .cache, normally, so not sure what caused this

**Comment by roman-rudakov** [comment]
Michiel Borkent ***@***.***> writes:

> This seems weird, since there is no cache, it can't already be 
> linted:
>

Yes, I also noticed it. That's why I decided to try fresh minimal 
project. I also tried to cleanup .clj-kondo/.cache and .cpcache/ which 
is created in the project root, but the output is still the same.

-- 
Best regards, Roman

**Comment by borkdude** [comment]
I believe I have the solution but CI isn't co-operating.
