### ISSUE TITLE
deftype and Class/new

### ISSUE THREAD

**Issue by dpassen** [clj-kondo/clj-kondo#2400]
- [X] I have read the [Clojure etiquette](https://clojure.org/community/etiquette) and will respect it when communicating on this platform.

clj-kondo v2024.08.29

macOS native build

**problem**

Classes generated with `deftype` trip a missing require warning when using Clojure 1.12.0's `Class/new` constructor form.

**repro**

```clj
(deftype Foo [n])
(Foo. 23)
(Foo/new 23)
```

```sh
$ clj-kondo --lint repro.clj
repro.clj:3:2: warning: Unresolved namespace Foo. Are you missing a require?
linting took 23ms, errors: 0, warnings: 1
```

**Comment by borkdude** [comment]
Thanks, will fix in next release
