### ISSUE TITLE
--diagnose flag

### ISSUE THREAD

**Issue by borkdude** [clj-kondo/clj-kondo#253]
When providing the `--diagnose` flag, clj-kondo should:

- Print the effective configuration (merged config from built-in, .clj-kondo/config.edn, and --config option)
- ~Validate configuration so when breaking changes occur, people are notified with deprecation errors/warnings~ (solved as linter).
- ~List unexpected things from the configuration so typos will be detected~ (solved as linter)
- Print stacktraces in case of exceptions

**Comment by PEZ** [comment]
> * This tool can add "ignores" for macros so they will not report errors for unresolved symbols, invalid arities and private usages.
> * This tool could potentially also fix some warnings by rewriting code.

Would be wonderful if https://github.com/borkdude/clj-kondo.lsp supplied these!

**Comment by borkdude** [comment]
@PEZ I think clj-kondo.lsp could build on the helper tool and then provide that.

**Comment by PEZ** [comment]
Yeah. I was not suggesting any specific architecture. 😄 Just think that it would be very nice features for VS Code Clojurists.

**Comment by sogaiu** [comment]
Linter for a linter...? :)
