### ISSUE TITLE
warn about macro being used as value

### ISSUE THREAD

**Issue by borkdude** [clj-kondo/clj-kondo#380]
Work in progress in the [macro-as-value](https://github.com/borkdude/clj-kondo/compare/macro-as-value) branch.

E.g. `(map -> [1 2 3])`

- [ ] getting lots of false positives when just checking the usage of a macro as a non-function call. Maybe we should implement this as a feature in the type checker where :macro is-a :fn but when it's passed as an argument, you'll get an error?

**Comment by borkdude** [comment]
This can be implemented using a custom linter on top of https://github.com/borkdude/clj-kondo/tree/master/analysis by checking if a used var is a macro, but has no arity. This may result in some false positives where I forgot to emit the arity for certain built-in macros like `comment`.

**Comment by wilkerlucio** [comment]
One thing to consider here is that some libraries have both macro and fn functions of the same symbol, for example, Fulcro has macros for things like `dom/div`, but they also functions, will depend on the context in which it's being referenced (direct call vs return).

Helix also does the same with `$` macro (as another example).
