### ISSUE TITLE
What companies or projects are using clj-kondo? (at least one person counts!)

### ISSUE THREAD

**Issue by borkdude** [clj-kondo/clj-kondo#438]
This issue has several purposes:

- Your company might be mentioned in a sheet of a presentation about clj-kondo. A link to a logo would be helpful.
- This issue would be a good way to notify you of any breaking changes in clj-kondo (which we will try to prevent).

If you would like to sponsor clj-kondo, I would be happy to take your money! :)

https://opencollective.com/clj-kondo
https://github.com/sponsors/borkdude

**Comment by borkdude** [comment]
Cognician (https://www.cognician.com)
Doctor Evidence (https://drevidence.com/)
VakantieDiscounter (https://vakantiediscounter.nl)

**Comment by Deraen** [comment]
You can find Metosin logo here: https://github.com/metosin/media

**Comment by thenonameguy** [comment]
We are also using it at Ekata (formerly Whitepages Pro): 
https://ekata.com/
https://ekata.com/assets/ekata-logo-white.svg

Thanks for this great piece of software!

**Comment by liquidz** [comment]
We are also using clj-kondo. Thanks for your great job!

* TOYOKUMO,Inc.
  * https://toyokumo.co.jp
* Logo
  * https://toyokumo.co.jp/wp-content/uploads/2019/09/toyokumo_logo.png

**Comment by Kynde** [comment]
We are also using clj-kondo at Leanheat. Nice linter! Keep up the good work! See you in ClojuTre.
https://leanheat.com/
https://leanheat.com/wp-content/uploads/2019/05/LeanheatDanfossLogoMarginBigFix.png

**Comment by Juholei** [comment]
Solita is using clj-kondo in multiple projects. Thank you for your work!
https://www.solita.fi/en/
![solita_logo](https://user-images.githubusercontent.com/5576385/65430683-f6a77480-de20-11e9-858e-538be8944e6c.png)

**Comment by scramjet** [comment]
Systematic is using it. https://systematic-app.com

Thanks! Finding it very useful in combination with flycheck on Emacs.

**Comment by gwena** [comment]
Ticketless.ai is using clj-kondo. Thanks a lot. Nice integration with Emacs.
https://ticketless.ai
Logo: https://ticketless.ai/wp-content/uploads/2019/08/logo.svg

**Comment by pbalduino** [comment]
Klarna
https://klarna.com
Logo: https://www.klarna.com/se/wp-content/themes/klarna/assets/images/icons/klarna.svg

**Comment by chorin1** [comment]
Using this lovely linter on AppsFlyer
https://appsflyer.com

Thanks for building this great tool!

**Comment by DanBunea** [comment]
Happy user from Codurance, Barcelona 
https://www.codurance.com

**Comment by telekid** [comment]
You've got some happy users over here at Flexport!

https://www.flexport.com

🚢

**Comment by ericdallo** [comment]
Some users from Nubank!

https://www.nubank.com.br

**Comment by nenadalm** [comment]
Imatic is using clj-kondo

website: https://www.imatic.cz/
logo: https://avatars1.githubusercontent.com/u/568033?s=200&v=4

**Comment by yannvanhalewyn** [comment]
Brightin is using CLJ-kondo!

website: https://www.brightin.nl/
logo: https://user-images.githubusercontent.com/11170603/69530070-b4f68f80-0f71-11ea-9d95-052703cd0367.png

**Comment by kwrooijen** [comment]
Mediquest uses this, thanks for your work!

Website: https://home.mediquest.nl/
Logo: https://home.mediquest.nl/wp-content/uploads/2019/07/mq-logo-rgb-online.png

**Comment by jeroenvandijk** [comment]
Adgoji is using clj-kondo. Thank you!
website: https://www.adgoji.com/

Logo [here](https://drive.google.com/file/d/1VlUhnrodGmZZd8bQl-PFgJPBdJTf_H4M/view)

**Comment by sskorokhodov** [comment]
We use clj-kondo at [SUPREMATIC](https://suprematic.de). Thank you!

**Comment by borkdude** [comment]
Added all these companies to the list here: https://github.com/borkdude/clj-kondo/blob/master/doc/companies.md

**Comment by porkostomus** [comment]
If you are still taking names, we are using clj-kondo's analysis output in our tooling for the new Exercism platform, in order to provide automated feedback for students learning Clojure and Babashka.

[Exercism logo](https://avatars0.githubusercontent.com/u/5624255)

**Comment by gwena** [comment]
Ticketless.ai is now Kaizo (https://kaizo.com/) and still using clj-kondo. Thanks a lot @borkdude

**Comment by borkdude** [comment]
I'm still taking names and updating them here:  https://github.com/borkdude/clj-kondo/blob/master/doc/companies.md

Thanks a lot for using clj-kondo!

**Comment by rubiagatra** [comment]
We are from https://zero-one-group.com using clj-kondo for our daily workflow. the logo https://zero-one-group.com/wp-content/uploads/2019/12/ZeroOneGroup_Black_500x500_Padded.png

**Comment by borkdude** [comment]
@raymcdermott on Slack:

FYI we at Vouch are now using clj-kondo ... please feel free to add us to your list

**Comment by laurio** [comment]
Happy user from Wunderdog, Helsinki
https://wunderdog.fi/
Thank you!

**Comment by pdenno** [comment]
We like clj-kondo at the US National Institute of Standards, https://www.nist.gov/

**Comment by bfontaine** [comment]
We’re using it at Oscaro (https://www.oscaro.com/).

**Comment by jplaza** [comment]
Thanks @borkdude for building this great tool! We've been using it for a long time now at Datil ([https://datil.com](https://datil.com))

**Comment by borkdude** [comment]
Thank you all for listing your company here. I added the following to the original post and will bring it to your attention once.

**Do not feel obligated to do anything with the below message**

------------

I just want to know that this is an area I'm exploring and there are possibilities to help this project grow:

If your company is using clj-kondo and profiting from it, consider donating via OpenCollective or Github actions:

https://opencollective.com/clj-kondo
https://github.com/sponsors/borkdude

I might be able to sustain myself from open source work. Around 4000-5000 dollars/euros a month should be enough to get started and around 8000 dollars/euros a month should be sufficient to live comfortably in the long term (not that I also have to pay taxes which are quite high in my country, save for retirement, etc.). 

If you have different ideas on how to provide income from clj-kondo while also keeping it free, open source and accessible, feel free to reach out.

**Comment by tanzoniteblack** [comment]
[Yummly](https://www.yummly.com) is using it and loving it!

http://assets.whirlpoolcorp.com/logos/Yummly-Logo-2018.png

**Comment by nathanmarz** [comment]
[Red Planet Labs](https://redplanetlabs.com/) is now using it. Excellent tool.

https://redplanetlabs.com/images/red-planet-logo.png

**Comment by rdgd** [comment]
[Splash Financial](https://www.splashfinancial.com/) is using clj-kondo.

[Splash logo](https://www.splashfinancial.com/wp-content/uploads/2021/05/logo.svg)
