### ISSUE TITLE
Detect duplicate case test constants

### ISSUE THREAD

**Issue by borkdude** [clj-kondo/clj-kondo#587]
```
user=> (case 1 1 1 1 1)
Syntax error macroexpanding case at (REPL:1:1).
Duplicate case test constant: 1
```

**Comment by viesti** [comment]
This reminds me of another `case` thingy, where symbols as test constants might lead to a bit unexpected result:

```clojure
user=> (def the-answer 42)
#'user/the-answer
user=> (let [result 42]
  #_=>   (case result
  #_=>     the-answer :yay
  #_=>     :lolnay))
:lolnay
```

Symbols as test constants might be rare enough so that such use might be worthy of a warning.

**Comment by jrasanen** [comment]
@borkdude: should @viesti's case be a separate issue?

**Comment by viesti** [comment]
Yeah, most probably, I'm known to fail at communication :D

**Comment by borkdude** [comment]
Thanks. I added the clj-together label. If this project gets funded by Clojurists Together I can do it during the funding period.

**Comment by borkdude** [comment]
@jrasanen @viesti Yes, that should be a separate issue, but I expect that issue to be hard to support, as you cannot really tell whether the symbols used in case are intentional or not.
