### ISSUE TITLE
Warn then a `throw` expr is not the last form in a block

### ISSUE THREAD

**Issue by marcomorain** [clj-kondo/clj-kondo#641]
If a `(throw )` is not the last expression in a block, then the code after the `(throw )` is dead and can never be called.

**Describe the solution you'd like**
A warning about dead code found after the `throw` expression.

```Clojure
(do
  (throw (Exception.))
  (this-can-never-be-called)) ;; <- warn about dead code here
```

**Comment by marco-carvalho** [comment]
I would like to pick this up if the approach is still welcome. I propose extending the existing `:unreachable-code` linter so a `do` reports the first form after an unconditional top-level `throw`:

```clojure
(do
  (throw (Exception.))
  (cleanup))
```

The check would not descend through conditional branches, so `(if failed? (throw e) (cleanup))` would not warn. It would also skip generated forms and retain the existing default warning level. I can submit a focused PR with tests, documentation, and a changelog entry after confirmation.
