### ISSUE TITLE
Feature request: Warn if docstring lines exceed max width

### ISSUE THREAD

**Issue by serioga** [clj-kondo/clj-kondo#793]
Sometimes I meet docstrings with very long lines which are not comfortable to work with due to horizontal scroll (many or most documentation tools show it as pre-formatted text). For example documentation for this function https://github.com/metosin/reitit/blob/7f7d6e22565362ac2b1c21a413865bab38438bac/modules/reitit-core/src/reitit/core.cljc#L345 does not fit in screen even in browser.

Probably it would be useful to have a linting rule which warns about unreasonable length of docstring lines.

Discussion in slack https://clojurians-log.clojureverse.org/clj-kondo/2020-03-09/1583784590.115800

**Comment by borkdude** [comment]
@serioga Note that the history of Clojurians slack is not stored, so it's probably better to just copy past the text from Slack and paste it here.

**Comment by borkdude** [comment]
dominicm Docstring width is fine until someone needs to paste a link in and tell the CI to go away for this one function.

**Comment by serioga** [comment]
> Docstring width is fine until someone needs to paste a link in and tell the CI to go away for this one function.

I also use long links in docstrings.
I think that long strings with single word (without spaces) should be ignored.

**Comment by serioga** [comment]
There is the `Docstring fill width` option in Cursive with default value `80`.
> **Colin Fleming:** You can use the Fill Paragraph action on docstrings, and it will fill them to that width. https://clojurians.slack.com/archives/C0744GXCJ/p1583790870089500?thread_ts=1583787348.089400&cid=C0744GXCJ

**Comment by didibus** [comment]
This linter also triggers my deep hate of CheckStyle on Java. So I'd really would prefer it as an opt-in. Or as I said in another issue, if there was a level I could easily ignore, like Info or Reminder, I'd be okay with that.

Though definitely not default at 80, I'd make that 160 or even more. It's 2020 folks!

**Comment by Heliosmaster** [comment]
On a side note, Clojurian Slack Log has permalinks for slack discussions, e.g. https://clojurians-log.clojureverse.org/clj-kondo/2020-03-09/1583784590.115800

**Comment by serioga** [comment]
I'm still interested :-)

**Comment by borkdude** [comment]
We have several "controversial" docstring linters already and this can be an additional one, opt-in for sure.

**Comment by serioga** [comment]
Should not we open the ticket?

**Comment by borkdude** [comment]
We have a `:line-length` linter as well for linting the length of lines in general.
