### ISSUE TITLE
Decorate "never used" symbols and namespaces

### ISSUE THREAD

**Issue by agzam** [clj-kondo/clj-kondo#794]
- Very often you need to require a namespace (e.g. that contains specs) without explicitly using anything out of that ns.

Kondo would complain about required but never used ns. Is there a way to decorate it in the code so Kondo does not warn about those and consequently doesn't remove them automatically when linting? 

- Similar case for variables:

Sometimes in a `let` block it's useful to show all destructured values, even though some of them might not be explicitly used in the same block. Maybe if it could be made possible to decorate the block, so Kondo doesn't complain, similar to how CIDER makes it possible to indent things using metadata https://docs.cider.mx/cider/indent_spec.html?

**Comment by borkdude** [comment]
@agzam 

If you are requiring a namespace solely for side effects such as loading specs, then just don't use an alias or `:refer`. In that case clj-kondo will not mention the namespace as unused.

The second feature is supported but only for function arguments, not in lets. See https://github.com/borkdude/clj-kondo/blob/master/doc/config.md#exclude-unused-bindings-from-being-reported. Note that destructuring is not a free operation so I would avoid destructuring unused values in `let`.

**Comment by serioga** [comment]
> Sometimes in a let block it's useful to show all destructured values, even though some of them might not be explicitly used in the same block.

For such cases there should be recommendation to use `:arglists` metadata to document structure of function arguments.

**Comment by borkdude** [comment]
@agzam clj-kondo now has `#_clj-kondo/ignore` and `#_{:clj-kondo/ignore [:unused-binding]}` etc.
