### ISSUE TITLE
Warn against reflective field access of defrecord

### ISSUE THREAD

**Issue by didibus** [clj-kondo/clj-kondo#812]
As mentioned by Alex Miller here https://ask.clojure.org/index.php/9168/defrecord-could-type-hint-the-record-constructor-functions and here https://www.reddit.com/r/Clojure/comments/flal9o/record_field_access_syntax/

The fields of a defrecord should not be accessed using interop. The recommend way is to use `get` or `:key`.

When using interop, the access is actually slower, unless type hints are used.

I thought this could be a good thing to lint for. The best linter would not warn if type hinted, but warn otherwise, since I guess if you were looking for the fastest access possible you'd go for a type hinted interop. But if that's too hard, I think it's a rare use case, so living with a warning in those case seems reasonable as well.

Thanks!

**Comment by alexanderkiel** [comment]
In performance critical code, I use interop with type hints. So if type hints could be detected, it would be a good linter.
