### ISSUE TITLE
Static analysis for data

### ISSUE THREAD

**Issue by slifin** [clj-kondo/clj-kondo#843]
**Is your feature request related to a problem? Please describe.**
I'd like to have static analysis for my .edn file used as a configuration file to enable error detection to prevent mistakes during configuration

**Describe the solution you'd like**
I'd like to create a spec for a particular keyword for example `(s/def :acme/color #{:red :blue :green})` and then when creating my configuration file if I do `:acme/color :yellow` I'd like an error to appear in my editor, the same as `(s/explain)`

**Comment by borkdude** [comment]
We might be able to support this once spec 2 comes out. Since spec is still in alpha, I don't like to expose it in a clj-kondo hook API since it adds size to the binary and when spec 2 comes around we would have to support both.
