### ISSUE TITLE
Extend analysis map to contain keyword usage

### ISSUE THREAD

**Issue by didibus** [clj-kondo/clj-kondo#855]
**Is your feature request related to a problem? Please describe.**

I'm working on an Emacs package which uses clj-kondo analysis data for auto-completion and some other editor features. One thing that I'd like to be able to auto-complete right now are Keywords. This can be useful when used within Specs or for map keys and other such thing.

**Describe the solution you'd like**

If it were possible, it be nice for the analysis to contain a list of the usage of Keywords per namespace/file. Just list every Keywords used anywhere in the linted path, and for each keyword, specify what namespace it was found in, what row/col, etc. Similar to var-defs.

Ideally, this would be smart enough to expand auto-resolved keywords such as `::mykey`, and similar auto-keyword expansion in maps. Would also be nice if it could list :keys destructuring as well.

**Describe alternatives you've considered**

Haven't considered any.

**Comment by borkdude** [comment]
Some considerations:

- This should not impact the performance of clj-kondo when the analysis information is not requested
- Should we always include all the keywords, or only optionally? Maybe most tools leveraging the analysis data won't need it and it might result into a lot of data?

**Comment by borkdude** [comment]
We actually have this feature now!
