### ISSUE TITLE
Extend analysis map to contain the list of refered Vars in each namespace

### ISSUE THREAD

**Issue by didibus** [clj-kondo/clj-kondo#856]
**Is your feature request related to a problem? Please describe.**

I'm working on an Emacs package which uses clj-kondo for auto-completion and other editor features such as go-to definition and find usage.

One thing I am missing currently is that I can not list out the possible Vars that a given namespace has refered using `:refer [a b]` or `(use 'some.ns)` or `:refer :all`.

**Describe the solution you'd like**

I would like it if the analysis map could list out for every namespace what Vars they have refered on other namespaces. That way I could list them out in the auto-completion of the current namespace and also allow to jump to their definition and find all of their usage (which could also allow me to maybe add renaming refactor)

Ideally, it would also say if another namespace is being `:refer :all` or `use ns` so that I'd know to list in the auto-completion all Var from that namespace as well.

**Describe alternatives you've considered**

Haven't considered any.

**Comment by borkdude** [comment]
I think we also already have this.
