### ISSUE TITLE
Expand analysis map so it contains namespace info from `(require ...)` and `(use ...)`

### ISSUE THREAD

**Issue by didibus** [clj-kondo/clj-kondo#857]
**Is your feature request related to a problem? Please describe.**

It seems that clj-kondo currently doesn't recognize `require` and `use` outside of the `ns` macro. So if one namespace has:

```
(ns foo)

(require '[bar :as b])
```

The analysis map will not mention that their is a usage from foo to bar as b.

Same hold for `use` it seems.

**Describe the solution you'd like**

I'd like it if clj-kondo analysis map could take those into account, so it's analysis result are more accurate.

**Describe alternatives you've considered**

Did not consider any.

**Comment by borkdude** [comment]
@didibus Can you establish the feasibility of your project using the existing functionality or have you already done so? 

If you have established that your auto-complete application is feasible using clj-kondo, we can go ahead and implement this issue, then #856 and after that possibly #855.

**Comment by didibus** [comment]
I have a running prototype, I'm ironing out the quirks and planning to publish v0.1 as an Emacs package hopefully by end of the weekend.

It works pretty well as it is. I analyze the project on mode enter once, and cache it. Then on completion I only re-analyse the buffer, and update the cache. There's a command you can run to refresh the cache if you've changed your declared dependencies. Otherwise, as you edit files, they get re-analysed into the cache.

This seems to work pretty well. And Emacs has a pretty fast json parser, so parsing the analysis map doesn't seem to be a big issue.

**Comment by borkdude** [comment]
Should work now
