### ISSUE TITLE
Exception messages contain misleading line and column info

### ISSUE THREAD

**Issue by andreyorst** [clj-kondo/clj-kondo#959]
First of all, thanks for an amazing software! It saves me a lot of time every day, and the ability to extend linting to match project need in Clojure is a great property!

**version**

v2020.07.29

**platform**

Binary from GH releases

**problem**

When I was adding my custom `analyze-call` hooks, I've noticed that every message displayed from `(throw (ex-info "msg" (meta node)))` contains information of row and column of where exception happened in the hook code and looks like this in log:

```
filename:row:col: error: msg [at line X, column Y]
```

Where X and Y are coordinates of `throw` call.

**repro**
Define some hook that just throws exception:

```clojure
1| (ns hooks.vaiv)
2| 
3| (defn i-will-error-always [{:keys [:node]}]
4|   (throw (ex-info "Error message" (meta node))))
```

Register it to any macro (e.g. `{clojure.core/-> hooks.vaiv/i-will-error-always}`) and run `clj-kondo --lint somefile.clj`:

```
fisomefile.clj:10:2: error: Error message [at line 4, column 2]
```

Or simply examine screenshot that reports such error in [documentation](https://github.com/borkdude/clj-kondo/blob/master/doc/config.md#analyze-call).

**expected behavior**

Messages contain no info about where exception happened, unless we want to debug clj-kondo itself.

**Comment by borkdude** [comment]
@andreyorst This can be solved by not throwing but using `api/reg-finding!`:

``` clojure
(ns hooks.vaiv
  (:require [clj-kondo.hooks-api :as api]))

(defn i-will-error-always [{:keys [:node]}]
  (let [{:keys [:row :col]} (meta node)]
    (api/reg-finding! {:row row
                       :col col
                       :message "Something is wrong"
                       :type :type-mismatch})))
```

**Comment by andreyorst** [comment]
yes I've did that eventually, but this has two *problems*

first we have to add extra `:linters` to config.edn, which is not a problem, but adds some extra stuff to think about.

second is that it does not terminate analysis, which may not always be a desired option.

**Comment by borkdude** [comment]
@andreyorst To terminate analysis you can just call `api/reg-finding!` and exit the function, returning nothing. Am I missing something?

**Comment by borkdude** [comment]
You can just put `:type :hook` in your finding, this will be the same as when throwing.
As for the nested expressions: you can do something like this:

``` 
(try
  (when (some analysis)
    (throw (ex-data "Something is wrong" {})))
  (catch Exception e
    (api/reg-finding! {:message (ex-message e) :row ... :col ...})))
``` 
```

**Comment by andreyorst** [comment]
Ah, hm. This seems reasonable indeed, did not think of it. I guess this settless that then. Thanks for the pointing out! 

I've never seen type :hook in documentation, did I missed it, or it is a some internal feature?

**Comment by borkdude** [comment]
@andreyorst It's an implementation detail, just a general linter type for any exceptions that might happen in the hook. I do want to do something about your initial concern, but also want to preserve the information while developing hooks.
