### ISSUE TITLE
Support clj-kondo in Emacs with tramp / ssh / (cider-)nREPL

### ISSUE THREAD

**Issue by borkdude** [clj-kondo/clj-kondo#969]
The use case is that I want to be able to use clj-kondo on a remote system when I'm editing files via tramp in Emacs. Invoking clj-kondo locally isn't optimal in that case since it only gets to see the local buffer via stdin, but cannot read a .clj-kondo/config.edn and and cannot read/write .clj-kondo/.cache.

If we can leverage the remote JVM which is already running cider-nrepl, we don't have to come up with some custom server.
E.g. maybe we could use https://melpa.org/#/flycheck-clojure like https://github.com/clojure-emacs/squiggly-clojure does?

Is clojure-lsp able to run remotely? Yes, see https://emacs-lsp.github.io/lsp-mode/page/remote/#remote

Inspiration: https://gitlab.com/tvaughan/kibit-runner.

Also see: https://github.com/borkdude/flycheck-clj-kondo/issues/9

**Comment by SevereOverfl0w** [comment]
To clarify, the problem is only the lack of config.edn, it's not the local buffer?

**Comment by borkdude** [comment]
@SevereOverfl0w Flycheck-clj-kondo now uses stdin to lint and uses the current working directory to resolve config.edn, .cache, etc. and then takes it from there. I don't even know what the current working directory is when editing a file over tramp.
