### ISSUE TITLE
Add per-form Kondo config override using meta-data 

### ISSUE THREAD

**Issue by thelazydogsback** [clj-kondo/clj-kondo#990]
Kondo newbie here, so sorry if I'm missing if I can already do this somehow.

It would be nice to be able to able to override a setting for a particular form, such as:

```
^{:kondo {:skip-comments true}}
(comment
    (foo bar baz))
```

Then one could have an editor macro that could easily toggle these settings for a form.
Could also have a per-file override that's a separate call or something inside of `(ns)`.

**Comment by borkdude** [comment]
@thelazydogsback See also https://github.com/borkdude/clj-kondo/issues/872, a feature which is currently being considered.

**Comment by borkdude** [comment]
One thing that we decided against in #872 was using metadata since this is visible in the Clojure programs itself.

**Comment by thelazydogsback** [comment]
Well, the whole point of namespace qualified keywords is that they don't clash, so it shouldn't make any difference if they're there at runtime. (If you really care you can delete all `kondo/` meta-data on startup.)

```
^{:kondo/config {skip-comments true}}
(comment
    (foo bar baz))
```

**Comment by borkdude** [comment]
It's just not great to have this information in your runtime, check the discussion in #872.  If we are going to support this, it will be something like:

``` clojure
#_{:clj-kondo/config {skip-comments true}}
(comment
    (foo bar baz))
```

**Comment by borkdude** [comment]
About your last comment, which I didn't read:

> Could also have a per-file override that's a separate call or something inside of (ns).

This is already supported:

``` clojure
(ns foo
  {:clj-kondo/config '{:skip-comments true}})

(comment
  (inc))
```

**Comment by thelazydogsback** [comment]
Got it -- makes sense.

When in doubt, (ab)use reader forms :)
