### ISSUE TITLE
Discouraged var usage

### ISSUE THREAD

**Issue by borkdude** [clj-kondo/clj-kondo#996]
In most cases it might be undesirable to use e.g. `read-string` in a codebase, although in some places it might be allowed.

We can have a linter that discourages the uses of these vars

```
:discourage-vars [clojure.core/read-string]
```

Maybe you would allow it in only some functions. The ignore reader hint can be used for this, so we probably don't need additional config options?

Or we could have something like this:

```
:discourage-vars [{:var clojure.core/read-string :allowed-in [foo.bar/dangerous]}]
```

@slipset might add this to eastwood, so I'm curious how this will look. Keep me posted!

**Comment by vemv** [comment]
FWIW I really want to add this to Eastwood, I'm simply working on bugs for a while

Curious, if wanting to implement this at clj-kondo level, the ingredients are already there in terms of analysis, right?

I guess that clj-kondo can't be easily fooled with shadowing etc but I don't know the precise extent of that.

As for the linter itself, I cannot think of a lot of things to discourage OOTB (`concat`, `flatten`?). Perhaps most of the value would come in unforeseen ways from user-provided vars.

**Comment by borkdude** [comment]
> Curious, if wanting to implement this at clj-kondo level, the ingredients are already there in terms of analysis, right?

Yes, this would be pretty easy to build. I think `eval` can make since to discourage too. For GraalVM usage `requiring-resolve` etc might be suspicious. But note that you can already see all of these var usages with https://github.com/clj-kondo/clj-kondo/blob/master/analysis/README.md too and now there's a `:custom-lint-fn` in which you can define your own linters based on the analysis output as well.

**Comment by borkdude** [comment]
Added an example here:

https://github.com/clj-kondo/clj-kondo/blob/master/doc/hooks.md#disrecommend-usage-of-function-or-macro

<img width="444" alt="Screen Shot 2021-10-20 at 16 39 58" src="https://user-images.githubusercontent.com/284934/138115296-948a7e70-4b0e-4031-b815-59a57f43e6ba.png">

**Comment by borkdude** [comment]
TODO: add docs.

Demo here: https://twitter.com/borkdude/status/1517880266840285184
